### ISSUE TITLE
九宫格vue CDN方式在ie11下不能运行

### ISSUE THREAD

**Issue by duodou** [buuing/lucky-canvas#104]
vue cdn 方式

ie11中不能运行，其他浏览器征程

我看例子中的代码可以运行 但是是经过webpack打包后的 ，

找了半天没找到问题所在，代码如下，希望有人解答一下

`
<body>
<div id="app">

  <div class="luckbox">

    <lucky-grid
        ref="LuckDraw"
        width="714px"
        height="674px"
        :prizes="prizes"
        :blocks="blocks"
        :buttons="buttons"
        :default-style="defaultStyle"
        :default-config="defaultConfig"
        @start="startCallBack"
        @end="endCallBack"
    />
  </div>

</div>

js:
`
<script type="text/javascript" src="https://cdn.bootcdn.net/ajax/libs/vue/2.6.9/vue.js"></script>
<script type="text/javascript" src="js/vue-luck-draw.umd.min.js"></script>
var app = new Vue({
    el: '#app',
    data: {

      prizes: [],
      blocks: [

      ],
      buttons: [{
        x: 1, y: 1, background: 'rgba(0, 0, 0, 0)',
        imgs: [{ src: './images/luck-btn.png', width: '90%', top: '5%' }]
      }],
      defaultConfig: {
        gutter: '17px',
        speed: 15,
        accelerationTime: 1800,
        decelerationTime: 1800
      },
      defaultStyle: {
        fontColor: '#301245',
        fontSize:  '20px',
        lineHeight:  '28px',
        wordWrap: false
      }

    },

    mounted: function mounted() {
      this.getPrizesList();
    },

    methods: {

      getPrizesList: function getPrizesList() {
        var prizes = [];
        var axis = [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2], [1, 2], [0, 2], [0, 1]];
        var data = [{ name: '好运签', top: '60%' }, { name: '50仙力', top: '60%' }, { name: '么么哒*1\n（人气礼物）', top: '52%' }, { name: '15元', top: '52%' }, { name: '宠爱有加*1\n（新特效礼物）', top: '52%' }, { name: '惊喜福袋*1', top: '60%' }, { name: '10仙力', top: '60%' }, { name: '么么哒*1\n（人气礼物）', top: '52%' }];
        axis.forEach(function (item, index) {
          prizes.push({
            x: item[0], y: item[1],
            text: data[index].name,
            fonts: [{ text: data[index].name, top: data[index].top }],
            imgs: [{
              src: './images/luckbg.png',
              activeSrc: './images/luckbg-on.png',
              width: '100%',
              height: '100%'
            }, {
              // width: '100%',
              // height: '100%',
              top:  '10%',
              src: './images/luck' + index + '.png',
              activeSrc: './images/luck' + index + '.png'
            }]
          });
        });
        console.log(this);
        this.prizes = prizes;
      },
      startCallBack: function startCallBack() {
        var _this3 = this;

        this.$refs.LuckDraw.play();

      },
      endCallBack: function endCallBack(prize) {

      },

    }
  });
</body>
</html>`
[源代码.txt](https://github.com/LuckDraw/lucky-canvas/files/6899852/default.txt)

**Comment by buuing** [comment]
报的什么错

**Comment by duodou** [comment]
> 报的什么错

最开始是 报 includes 不支持 ，我加上 Array.prototype.includes profill代码，不报错了，但是也是空白的，canvas没有出来，看下源文件 txt

**Comment by duodou** [comment]
最开始是 includes 方法不支持，我加上 Array.prototype.includes  profill代码后，就又报这个错误
![image](https://user-images.githubusercontent.com/4252917/127588128-896716ee-4879-40e6-baf8-7299e86a1b95.png)
canvas再代码中是生成了，但是 页面效果一片空白，不知道是什么bug导致的
![image](https://user-images.githubusercontent.com/4252917/127589142-5285d62d-093b-4a1d-ac00-e4875fdf9c79.png)

**Comment by buuing** [comment]
额...我手上没有ie11, 我晚上回家试试, 你加我微信`new_ldq`

**Comment by buuing** [comment]
这是因为没有 `Promise` 的兼容,  把下面的CDN在插件前面引入即可

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```
