### ISSUE TITLE
设置activeSrc中奖照片后，第一次格子抽奖的时，奖品图片会消失闪现，体验效果不好，第二次正常

### ISSUE THREAD

**Issue by chrisetong** [buuing/lucky-canvas#109]
我设置5X5共16个宫格，并且奖品都设置src和activeSrc。当我第一次抽奖的时候，每个奖品会闪一下（有点像渲染卡顿，或者像是图片加载缓慢），第二次抽奖就正常了。请问这是怎么回事？

**Comment by buuing** [comment]
你是哪个框架? 小程序吗?

**Comment by chrisetong** [comment]
> 你是哪个框架? 小程序吗?

我用的是uniapp开发


						<LuckyGrid class="grid-draw" ref="luckyWheel" width="680rpx" height="696rpx"   :default-config="defaultConfig"
							:blocks="blocks" :prizes="prizes" :buttons="buttons" rows="5" cols="5"
							:active-style="activeStyle" @start="startCallBack" @end="endCallBack" />

**Comment by buuing** [comment]
我猜你请求的是网络图片吧, uniapp目前网络图片需要使用getImageInfo去请求, 所以会闪一下

**Comment by buuing** [comment]
目前uniapp的包正在使用type2d改版, 后续我会关注一下这个问题

**Comment by chrisetong** [comment]
> 我猜你请求的是网络图片吧, uniapp目前网络图片需要使用getImageInfo去请求, 所以会闪一下

是的，奖品是后台配置的，所以肯定是网络图片。

**Comment by chrisetong** [comment]
> 目前uniapp的包正在使用type2d改版, 后续我会关注一下这个问题

好的，谢谢。还有一个问题，就是activeStyle有没有办法设置倒圆角，因为奖品图片有一些是倒圆角，抽奖中奖覆盖下去有可能比较不好看。

**Comment by buuing** [comment]
暂时不能, activeStyle目前只能实现一些简单的逻辑, 如果是操作图片的话, 需要我额外进行处理, 这个等重构完成后我会思考一下该如何做

**Comment by chrisetong** [comment]
> 暂时不能, activeStyle目前只能实现一些简单的逻辑, 如果是操作图片的话, 需要我额外进行处理, 这个等重构完成后我会思考一下该如何做
好的，谢谢大佬
