### ISSUE TITLE
請問如何在輪盤轉動時調用停止

### ISSUE THREAD

**Issue by tsungche** [buuing/lucky-canvas#126]
- 版本号：v3.4.5

- 平台信息：vue2.x

- 详细描述：請問如何在輪盤轉動時置換 抽奖按钮 - buttons, 可立即停止

- 问题代码（最好同时包含 html 和 js）
```
// 在这里粘贴你的代码
```

**Comment by buuing** [comment]
什么意思, 你是指的立即停止没生效吗

**Comment by tsungche** [comment]
對 立即停止沒生效


404 ***@***.***>於 2021年8月16日 週一，下午9:10寫道：

**Comment by buuing** [comment]
好的, 稍后我看一下

**Comment by tsungche** [comment]
謝謝你

404 ***@***.***>於 2021年8月16日 週一，下午9:24寫道：

**Comment by buuing** [comment]
确实无法立即停止, 我将会在下个版本修复他, 你可以先暂时使用下面的方式, 通过重新渲染来模拟初始化的效果

```diff
<template>
  <div>
    <LuckyWheel
+     v-if="show"
!     ...
    />
+   <button @click="stop">stop</button>
  </div>
</template>

<script>
export default {
  data () {
    return {
+     show: true
    }
  },
  methods: {
+   stop () {
+     this.show = false
+     this.$nextTick(() => {
+       this.show = true
+     })
    }
  }
}
</script>
```

**Comment by tsungche** [comment]
謝謝你 我試試

404 ***@***.***>於 2021年8月16日 週一，下午10:19寫道：

**Comment by buuing** [comment]
最新版`v3.4.9`已修复该问题, 可以使用`this.$refs.myLucky.init()`方法来初始化
