### ISSUE TITLE
uniapp运行在微信小程序端时canvas层级过高问题

### ISSUE THREAD

**Issue by WeiieCn** [buuing/lucky-canvas#130]
- 用的什么框架：**uniapp** 

- 你当前插件的版本：**uni-luck-draw@1.4.3**

- 详细描述你的bug：**大转盘使用【仿京东大转盘抽京豆】运行在微信小程序端时上方指针层级低于canvas层级**

- 问题代码：
```
// 在这里开始粘贴你的代码

<view class="box">
   <img :src="require('@/components/uni-luck-draw/img/wheel/bg.png')" style="width: 100%" mode="widthFix" />
   <img :src="require('@/components/uni-luck-draw/img/wheel/btn.png')" class="pointer" mode="widthFix" />
   <LuckyWheel class="luck-draw" ref="LuckyWheel" width="275px" height="275px" :prizes="wheel.prizes" :buttons="wheel.buttons" :default-style="wheel.defaultStyle" :default-config="wheel.defaultConfig" @start="wheelStart" @end="wheelEnd"/>
</view>

// 代码结束
```

图片地址：[https://img-cdn-tc.dcloud.net.cn/uploads/questions/20210831/d50de2c0f63458705b4fe297740357bd.png](url)
![图片](https://img-cdn-tc.dcloud.net.cn/uploads/questions/20210831/d50de2c0f63458705b4fe297740357bd.png)

**Comment by buuing** [comment]
小程序里的canvas是原生组件, 是顶层渲染, 我内部无法控制, 你只能使用`cover`组件, 具体如何使用你可以百度一下

**Comment by WeiieCn** [comment]
好的，我试试
