### ISSUE TITLE
activeSrc和src绘制宽度不一致

### ISSUE THREAD

**Issue by ChenRiliang** [buuing/lucky-canvas#131]
如图，绘制activeSrc时， 底下还是先绘制了src，并且绘制activeSrc与src宽度不一致导致底部原图溢出
![image](https://user-images.githubusercontent.com/30994257/131434994-2973b652-7aa3-47e4-9c2b-434376fc4f54.png)

- 用的什么框架：Vue

- 你当前插件的版本："vue-luck-draw": "^3.4.6",

- 详细描述你的bug：

- 问题代码：
```
// 在这里开始粘贴你的代码
prizes.push({
            index: i,
            x: axis[i][0],
            y: axis[i][1],
            background: '#FFF',
            shadow: 'none',
            fonts: [],
            imgs: [{
              src: require('../assets/images/spritesGroup1/get-start-item-demo.png'),
              width: '100%',
              height: '100%',
              activeSrc: require('../assets/images/spritesGroup1/get-start-item-on-demo.png'),
            }],
          });
// 代码结束
```

**Comment by buuing** [comment]
麻烦提供一下这两张图片

**Comment by ChenRiliang** [comment]
> 麻烦提供一下这两张图片

![get-start-item-demo](https://user-images.githubusercontent.com/30994257/131435556-5574e383-0118-4728-86cc-850a80105da2.png)
![get-start-item-on-demo](https://user-images.githubusercontent.com/30994257/131435563-fc6ac33c-d86f-4cf0-a592-2171da8641ca.png)

**Comment by buuing** [comment]
那个是默认的active样式导致的, 你把他清掉就好了

```diff
+ activeStyle: {
+   background: '#fff',
+ }
```

**Comment by ChenRiliang** [comment]
> 那个是默认的active样式导致的, 你把他清掉就好了
> 
> ```diff
> + activeStyle: {
> +   background: '#fff',
> + }
> ```

可以了， 十分感谢~

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下
