### ISSUE TITLE
文字能加阴影吗

### ISSUE THREAD

**Issue by moziming888** [buuing/lucky-canvas#132]
- 用的什么框架：taro 

- 你当前插件的版本：1.0.10

- 详细描述你的bug：有多种模板，用的同一个大转盘。扇形有蓝加白间隔，蓝加黄间隔。文字想要蓝色，期望可以实现所有的文字清晰还不突兀。所以能加文字阴影吗

- 问题代码：
```
// 在这里开始粘贴你的代码

// 代码结束
```

**Comment by buuing** [comment]
具体啥样子的, 方便发个样式图片吗
