### ISSUE TITLE
打包文件中没有.d.ts 类型问题

### ISSUE THREAD

**Issue by cll123456** [buuing/lucky-canvas#133]
打包结果中没有声明的类型文件。
![image](https://user-images.githubusercontent.com/41314419/133049881-77b05a89-64d1-4a63-8a28-4c3b11bc01ee.png)
在ts中会报警告，看着有点不舒服
![image](https://user-images.githubusercontent.com/41314419/133050032-aa5a0818-c7c1-4115-94eb-28b6513e17ca.png)

**Comment by buuing** [comment]
现在我这里已经生成描述文件了, 但是遇到个阻碍性问题, 暂时无法提交新版本

**Comment by cll123456** [comment]
好的，感谢大佬。

**Comment by buuing** [comment]
> 好的，感谢大佬。

最新版`v3.4.7`已增加ts描述文件, 你看看好用呗

**Comment by cll123456** [comment]
好的，谢谢
