### ISSUE TITLE
react 修改转盘 width height 属性 转盘没有重新渲染

### ISSUE THREAD

**Issue by lvqingxiang** [buuing/lucky-canvas#134]
- 用的什么框架：

- 你当前插件的版本：

- 详细描述你的bug：

- 问题代码：
```
// 在这里开始粘贴你的代码

// 代码结束
```

<LuckyWheel
            ref={luckyWheel}
            width={outerWidth}
            height={outerHeight}
            blocks={blocks}
            prizes={newPrizes}
            buttons={buttons}
            onStart={() => {
              luckyWheel.current?.play();
              setTimeout(() => {
                luckyWheel.current?.stop(0);
              }, 1000);
            }}
            onEnd={() => {}}
          />
我在外面控制 outerwidth outerheight 改变 但是转盘没有重新渲染 我看到网站里面 可视化编辑是有变化的 是我哪里疏漏了吗

**Comment by buuing** [comment]
.....宽高属性目前是组件渲染时一次性赋值, 不是响应式的
后续会考虑加入响应式, 但是目前你只能通过三元运算符去触发一下重新渲染了...

**Comment by buuing** [comment]
最新版的宽度/高度已加入响应式

**Comment by LeeeeeeM** [comment]
> 最新版的宽度/高度已加入响应式

最新版是什么版本？没合入相关代码吧。

**Comment by buuing** [comment]
> 最新版是什么版本？没合入相关代码吧。

你用的是哪个包, 什么版本
