### ISSUE TITLE
Cannot use namespace 'LuckyGrid' as a type.

### ISSUE THREAD

**Issue by lzchina** [buuing/lucky-canvas#136]
执行 npm run build编译的时候提示下面这个，如果处理，谢谢

src/index.ts → dist/vue-luck-draw.esm.js, dist/vue-luck-draw.cjs.js, dist/vue-luck-draw.umd.js...
(!) Plugin typescript: @rollup/plugin-typescript TS2709: Cannot use namespace 'LuckyGrid' as a type.
src\components\LuckyGrid.ts: (82:23)

**Comment by buuing** [comment]
你使用的时候怎么会报这个错?

**Comment by lzchina** [comment]
编译的时候

**Comment by buuing** [comment]
> 编译的时候

我本地打包没问题, 你有什么特殊需求可以直接问我

**Comment by lzchina** [comment]
太感谢了，我fork了master分支，然后添加了个配置之后编译就出问题了，我的代码没有添加插件，直接npm run dev是好的，但是打包就过不去了，各种错误，我对lerna和rollup不熟悉，不知道问题出在哪了，我根据出错改了一些配置之后还是过不去，能给我个联系方式吗，我现在尝试获取原始fork版本编译试试。或者帮我试下我的版本编译下，感谢感谢

**Comment by lzchina** [comment]
https://github.com/lzchina/lucky-canvas

**Comment by buuing** [comment]
嗯, 你先拉取一下最新的master试试, 有的rollup-plugin包可能依赖有问题

**Comment by lzchina** [comment]
好的，有问题我再提上来

**Comment by lzchina** [comment]
打包解决了，但是发现uni-app版本有bug，一转起来就有两个转盘了，能帮忙看下吗

**Comment by buuing** [comment]
uniapp有bug, 等待他们修复

**Comment by lzchina** [comment]
好的，我也尝试修复下，我觉得是里面的异步方法的draw引起的，我试试

**Comment by lzchina** [comment]
最新版本好了，谢谢

**Comment by lzchina** [comment]
@buuing 另外我说的uniapp这个bug我修复在我的fork下了，和你说下，感谢提供个这么好用的插件
