### ISSUE TITLE
v3.4.9在vue2的低版本中打包发生报错

### ISSUE THREAD

**Issue by 1220799146** [buuing/lucky-canvas#137]
- 用的什么框架：vue 

- 你当前插件的版本：3.4.9

- 详细描述你的bug：在vue2项目中打包报错

- 问题代码：
- 打包报错截图
![191527ac4641a09df8edfd877f03b29](https://user-images.githubusercontent.com/32691200/135221009-c9007945-bf91-4180-81f1-db35dbe19788.png)

```
// 在这里开始粘贴你的代码

// 代码结束
```

**Comment by buuing** [comment]
vue2.几? 方便压缩个小demo发我吗

**Comment by buuing** [comment]
我刚找了个2.6然后build打包没有问题

**Comment by 1220799146** [comment]
vue  2.6.14
公司项目，没办法发，不能兼容3.4.9，紧急回退到3.4.6可以了

**Comment by buuing** [comment]
嗯, 3.4.9新增了概率属性range, 没有需求可以不更新

**Comment by buuing** [comment]
你们的项目是自己搭建的还是用cli脚手架搭建的

**Comment by 1220799146** [comment]
cli搭建的，cli应该比较低，webpack 2.7.0

**Comment by buuing** [comment]
你能用你那个cli创建一个空的项目压缩发我吗, 我怀疑可能是某些依赖版本冲突了?

**Comment by buuing** [comment]
你使用`v3.4.9`的时候, 安装一个依赖试试`npm i @vue/composition-api`看看还报错吗

**Comment by buuing** [comment]
最新版`vue-luck-draw@3.4.11`已规避该问题
