### ISSUE TITLE
部分手机上面无法进入end回调

### ISSUE THREAD

**Issue by songjingxiaoyu** [buuing/lucky-canvas#139]
- 用的什么框架：

- 你当前插件的版本：

- 详细描述你的bug：

- 问题代码：
```
// 在这里开始粘贴你的代码

// 代码结束
```

**Comment by songjingxiaoyu** [comment]
回调进stop但是没进end  导致最后转盘停的位置不是我想要的位置 就会有问题 求解

**Comment by Raccoon-Office** [comment]
1.5.8 有 大概8% 的用户。 我们用的jquery 版的。我们将它用在有大量用户的电商网站，希望你们能解决这个bug。

**Comment by buuing** [comment]
可以提供一个能复现问题的小demo吗

**Comment by songjingxiaoyu** [comment]
可以的 我先用1.5.4这个版本。然后可以录个屏发给你，非常感谢



在 2021-10-02 16:44:10，"404" ***@***.***> 写道：

可以提供一个能复现问题的小demo吗

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by buuing** [comment]
发我微信吧，官网有我的二维码

**Comment by songjingxiaoyu** [comment]
官方微信没找到。找到一个您的邮件。才给您发邮件的



在 2021-10-02 16:44:10，"404" ***@***.***> 写道：

可以提供一个能复现问题的小demo吗

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by songjingxiaoyu** [comment]
好的 感谢



在 2021-10-02 16:46:13，"404" ***@***.***> 写道：

发我微信吧，官网有我的二维码

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by buuing** [comment]
new_ldq

**Comment by buuing** [comment]
加一下我的微信`ldq404`

**Comment by buuing** [comment]
很奇怪, 我这里已经针对数组 `find` 方法增加了兼容, 能说一下你复现问题的机型吗

**Comment by buuing** [comment]
如果无法修复该问题, 我可以提供一个备选方案

**Comment by buuing** [comment]
排查完毕, 该问题不是 find 方法兼容问题导致的

但是刚刚这位使用者反馈说: 在end里面加了一个`setTimeout`回调就没事了
