### ISSUE TITLE
切换分辨率 不能自动适应页面

### ISSUE THREAD

**Issue by wzt-procedure** [buuing/lucky-canvas#142]
- 用的什么框架：

- 你当前插件的版本：

- 详细描述你的bug：

- 问题代码：
```
// 在这里开始粘贴你的代码

// 代码结束
```

**Comment by buuing** [comment]
你用的啥框架, 目前只有js包增加了对`resize`的监听, 其余包你可以切换分辨率之后再去刷新一下, 因为我觉得用户那里不太可能会出现屏幕变来变去的情况

**Comment by wzt-procedure** [comment]
现在对于文字过长 例如 英文  还是只能换行？不能截取吗？

**Comment by buuing** [comment]
> 现在对于文字过长 例如 英文 还是只能换行？不能截取吗？

是的, 目前只能换行, 或者你在接口里拿到文字的时候截取一下, 不过后续会考虑这个截取文字的功能

**Comment by wzt-procedure** [comment]
好的 谢谢！

**Comment by buuing** [comment]
没事, 只要是合理的需求, 我这边都会考虑的

**Comment by buuing** [comment]
最新版增加了`lineClamp`属性用来指定最多渲染多少行文字, 超出部分自动忽略为`...`
