### ISSUE TITLE
通过stop函数传递中奖索引

### ISSUE THREAD

**Issue by isfor-hhj** [buuing/lucky-canvas#143]
通过stop函数传递中奖索引

_Originally posted by @buuing in https://github.com/LuckDraw/lucky-canvas/issues/84#issuecomment-864830956_

**Comment by isfor-hhj** [comment]
prizes中设置每项奖品的range属性 设置中奖概率 好像没用

**Comment by buuing** [comment]
range属性还在测试中, 目前还未对外开放

**Comment by buuing** [comment]
stop方法你把中奖奖品的索引传递给stop即可
假设有8个商品, 那么中奖索引就是0~7

**Comment by isfor-hhj** [comment]
那是不是没法控制各个奖项的中奖概率了吗

**Comment by buuing** [comment]
这玩意不应该是后端通过接口返回中奖奖品吗，假设你家后端懒得要死让前端写，你随便写个简易的随机概率不就得了

**Comment by isfor-hhj** [comment]
我懂了。stop里面接收来自后台的中奖索引 这个索引的获取就是后台来设置的中奖概率

**Comment by buuing** [comment]
是的

**Comment by isfor-hhj** [comment]
好的，谢谢大佬

**Comment by buuing** [comment]
没事, 用着顺手可以帮我宣传宣传

**Comment by isfor-hhj** [comment]
OK
