### ISSUE TITLE
vue H5  九宫格宽高无法转Rem或VW

### ISSUE THREAD

**Issue by cai87949448** [buuing/lucky-canvas#144]
- 用的什么框架：

- 你当前插件的版本：

- 详细描述你的bug：

- 问题代码：
```
// 在这里开始粘贴你的代码

// 代码结束
```

**Comment by buuing** [comment]
vue里面的包, 好像还不能使用`vw`, 但`rem`是可以的

**Comment by buuing** [comment]
如果你认为`rem`不可用, 或没有效果, 可以复现一个小demo发给我
