### ISSUE TITLE
移动端屏幕滑动时, 部分浏览器会触发resize, 从而导致抽奖被意外重置

### ISSUE THREAD

**Issue by eat-happy** [buuing/lucky-canvas#146]
- 用的什么框架：jquery
 
 
- 详细描述你的bug：移动端九宫格，点击抽奖按钮后，滚动页面离开可视区域，抽奖直接停止
 
 官网可复现

**Comment by eat-happy** [comment]
复现视频:
https://github.com/eat-happy/lucky-canvas/blob/master/RPReplay_Final1634738618.MP4

**Comment by buuing** [comment]
你这是啥浏览器

**Comment by eat-happy** [comment]
safari , 还有一个华为浏览器，在微信环境里也可以复现

**Comment by buuing** [comment]
我看这个视频里, 也不是100%复现, 有几次的旋转没有问题, 只有两次, 好像中奖标记没有了

**Comment by eat-happy** [comment]
是的，有几率出现这个问题

**Comment by eat-happy** [comment]
离开可视区后才会出现

**Comment by buuing** [comment]
> safari , 还有一个华为浏览器，在微信环境里也可以复现

我刚才试了一下华为浏览器, 没有问题
微信里打开也没问题?

**Comment by eat-happy** [comment]
我在华为浏览器录个屏给你看看

**Comment by buuing** [comment]
最新版`lucky-canvas@1.5.12`已修复该问题, resize时不再触发init方法
