### ISSUE TITLE
Taro 框架绘制报错

### ISSUE THREAD

**Issue by dcqzy** [buuing/lucky-canvas#148]
- 用的什么框架：taro version:3.3.10

- 你当前插件的版本：1.2.2

- 详细描述你的bug：
lucky-canvas文件报错: 
window.addEventListener is not defined

以及:
ReferenceError: ctx is not defined
    at LuckyWheel.beforeCreate (._node_modules_taro-luck-draw_react_LuckyWheel.js:110)
    at new LuckyWheel (.._src_lib_wheel.ts:65)
    at LuckyWheel.drawLucky (._node_modules_taro-luck-draw_react_LuckyWheel.js:100)
    at Object.<anonymous> (._node_modules_taro-luck-draw_react_LuckyWheel.js:86)
    at a.<anonymous> (VM48 WAService.js:2)
    at :56455/appservice/<SelectorQuery callback function>
    at VM48 WAService.js:2
    at VM48 WAService.js:2
    at Array.forEach (<anonymous>)
    at VM48 WAService.js:2(env: macOS,mp,1.05.2109131; lib: 2.20.0)

- 问题代码：
[demo已上传 这是链接](https://github.com/dcqzy/lucky-draw-debug)

 个人想法:
报错是因为lucky-canvas.umd.js中的第575行报错 是否是因为api不支持的原因?

**Comment by buuing** [comment]
不应该有这个提示啊

**Comment by dcqzy** [comment]
是的 如果您有空的话可以麻烦您下载一下我的demo运行一下是否也有这种问题嘛?

**Comment by buuing** [comment]
> 是的 如果您有空的话可以麻烦您下载一下我的demo运行一下是否也有这种问题嘛?

嗯, 我正在看, 你是H5还是小程序啊

**Comment by dcqzy** [comment]
微信小程序 需要我提供什么不?

**Comment by buuing** [comment]
暂时不需要, 我这边复现问题了, 稍后我回复你最新进展

**Comment by dcqzy** [comment]
好的 谢谢

**Comment by buuing** [comment]
最新版`taro-luck-draw@v1.2.4`已修复该问题

不好意思, 变量忘记解构了(●'◡'●)

**Comment by buuing** [comment]
至于你说的这个报错`window.addEventListener is not defined`在你提供的demo里, 我这边运行时没有发现

**Comment by dcqzy** [comment]
好的 谢谢您的支持 请问1.2.4版本什么时候更新至npm或者是yarn上呢?

**Comment by buuing** [comment]
现在已经在上面了, 你试试看还有问题吗

**Comment by dcqzy** [comment]
[yarn](https://www.yarnpkg.cn/package/taro-luck-draw)上好像还没有传 能麻烦您看一下嘛

**Comment by buuing** [comment]
......yarn不用上传, 无论是cnpm还是yarn还是pnpm, 他们下载的都是npm包

而且我刚刚试了一下, 是可以下载的`yarn add taro-luck-draw@1.2.4`

**Comment by dcqzy** [comment]
好的 谢谢您

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下

**Comment by dcqzy** [comment]
安装上了 是镜像源的问题 感谢大佬

**Comment by buuing** [comment]
好的
