### ISSUE TITLE
无法获取到 CanvasContext2D 或宽高

### ISSUE THREAD

**Issue by jixianga** [buuing/lucky-canvas#152]
- 用的什么框架：vue.js

- 你当前插件的版本：3.2.1

- 详细描述你的bug：控制台提示 “无法获取到 CanvasContext2D 或宽高”，请问这是什么原因呢，刚接手的代码0.0

- 问题代码：
```
// 在这里开始粘贴你的代码

// 代码结束
```

**Comment by buuing** [comment]
代码贴一下, 难道怕我抄你代码吗

**Comment by jixianga** [comment]
`<lucky-wheel class="lucky-wheel" :blocks="blocks" ref="LuckyWheel"
                @start="startCallBack" @end="endCallBack" :prizes="prizes" 
                :default-config="defaultConfig" :buttons="buttons" />`

刚检查了一下 lucky-wheel 的高度是0，请问可能是哪些方面导致的呢

**Comment by buuing** [comment]
3.2.1大概是半年前的版本了, 代码贴全点行吗, 这么少, 流量很贵吗

**Comment by jixianga** [comment]
问题找到了，dom高度为0，导致canvas没有渲染出来。

从dom到js代码很多，单独抽离贴出来很多，我也在排查问题，我就是请教下哪些情况会出现这种问题，便于我去检查。没必要讲话这么冲吧。- -。感谢回复

**Comment by buuing** [comment]
....首先, 你这个提问让我无法定位到问题, 这个报错的可能性很多

如果每个人发代码都跟挤牙膏似的, 这无疑会浪费大量的沟通时间, **我实在是不能理解**, 为什么代码不能一次性发出来, 我的提问模板里明明都特意留出来一个代码块! 就是为了双方能够减少沟通次数, 结果有的人就非得说的模棱两可

其次, 关于我的语气问题, 很冲? 可能你理解有误吧
