### ISSUE TITLE
是否可以设置转盘中间抽奖按钮不可点击，只是一个展示的指针的作用

### ISSUE THREAD

**Issue by qyjandroid** [buuing/lucky-canvas#153]
转盘中间的抽奖按钮是否可以只是一个指针展示作用，某种情况下，UI会把真正的抽奖操作，单独在转盘下方放两个抽奖按钮，比如：抽一次，或者抽十次，这样的时候，我们就需要转盘转件的指针只是展示。点击抽一次，我们调用play方法即可。

用的什么框架：react 或者是preact

**Comment by buuing** [comment]
可以, 你直接在`startCallback`里面把逻辑用`return`打断掉, 然后在外面用dom做按钮, 异步调用`play()`不就得了

**Comment by qyjandroid** [comment]
抱歉，我的问题，没仔细看文档

**Comment by qyjandroid** [comment]
直接不注册onStart和onEnd即可

**Comment by buuing** [comment]
ok, 用着顺手可以点个`star`支持一下

**Comment by qyjandroid** [comment]
已支持
