### ISSUE TITLE
微信小程序里如何在界面提示 中奖信息

### ISSUE THREAD

**Issue by newluhuibiao** [buuing/lucky-canvas#155]
demo中后台输出是：console.log(event.detail.title)；用 alert(`恭喜你获得${event.detail}`) 报错如下：
alert is not a function; [Component] Event Listener Error @ miniprogram_npm/mini-luck-draw/lucky-wheel/index#(anonymous)

**Comment by buuing** [comment]
微信小程序里压根就没有`alert`方法, 你自己去文档里找弹窗API不就得了

**Comment by newluhuibiao** [comment]
多谢！

**Comment by dcqzy** [comment]
小程序可以使用showModal, 如果要自定义的话目前好像只能把转盘盖住然后显示一个popup(小程序canvas为最顶层)
