### ISSUE TITLE
vueDemi.defineComponent is not a function

### ISSUE THREAD

**Issue by wuxiaobin1995** [buuing/lucky-canvas#156]
![image](https://user-images.githubusercontent.com/36044379/140040312-5b483e9e-66e8-4473-9c9c-c1741081099f.png)

**Comment by buuing** [comment]
代码发一下, 我看看你咋用的

**Comment by wuxiaobin1995** [comment]
<template>
  <div class="home">
    <lucky-wheel
      width="200px"
      height="200px"
      :blocks="blocks"
      :prizes="prizes"
    />
  </div>
</template>

<script>
export default {
  data() {
    return {
      blocks: [{ padding: '10px', background: '#869cfa' }],
      prizes: [
        { fonts: [{ text: '0' }], background: '#e9e8fe' },
        { fonts: [{ text: '1' }], background: '#b8c5f2' },
        { fonts: [{ text: '2' }], background: '#e9e8fe' },
        { fonts: [{ text: '3' }], background: '#b8c5f2' },
        { fonts: [{ text: '4' }], background: '#e9e8fe' },
        { fonts: [{ text: '5' }], background: '#b8c5f2' }
      ]
    }
  }
}
</script>

**Comment by wuxiaobin1995** [comment]
![image](https://user-images.githubusercontent.com/36044379/140040638-e7cd7529-3b6c-4be0-a325-6f4548a5d660.png)

**Comment by wuxiaobin1995** [comment]
![image](https://user-images.githubusercontent.com/36044379/140040674-60afb518-5c2b-4060-aa21-a99224ec306a.png)

**Comment by buuing** [comment]
安装的时候报错了吗

**Comment by wuxiaobin1995** [comment]
没有报错，还有我用的是Electron

**Comment by buuing** [comment]
Electron我还真没试过, 你重新安装一下`npm i @lucky-canvas/vue`呢?

**Comment by buuing** [comment]
然后改成这个试试
```js
const VueLuckyCanvas  = require('@lucky-canvas/vue')
```

**Comment by buuing** [comment]
? 如何了, 还没好的话 加一下我微信`new_ldq`

**Comment by wuxiaobin1995** [comment]
解决了，估计是我其他第三方插件的影响，可以运行。
