### ISSUE TITLE
奖品配置这里，能不能添加左右间距，我想让一个格子里左右放两张图片

### ISSUE THREAD

**Issue by newscott001** [buuing/lucky-canvas#160]
### 奖品配置这里，能不能添加左右间距，我想让一个格子里左右放两张图片
```
let imgs = []
for(let i=0;i<imgsArr;i++){
imgs.push({
                    src: imgsArr[i], //图片链接
                    width: '26px',
                    height: '30px',
                    top: i == 0 ? '10%' : '30%',
                    left: //奖品配置这里，能不能添加左右间距，我想让一个格子里左右放两张图片
                  })
}
```

**Comment by buuing** [comment]
不能, 暂时没有`left`和`right`属性, 如果你想让两个奖品图片处于平行, 只能是让ui给你切好图片

**Comment by newscott001** [comment]
> 不能, 暂时没有`left`和`right`属性, 如果你想让两个奖品图片处于平行, 只能是让ui给你切好图片

让ui切好图片就不够灵活了。。。比如我这个奖项是一个大件商品，如果中了，在送一个小件的，我只是想让这两个商品的图片都显示到一个格子里，后台配置奖品的时候，就可以随意配置，哪个奖品多送一个物件。哎，只能说需求有点扯。。。

**Comment by buuing** [comment]
那你只能上下摆放了...或者你用canvas处理一下, 把小图贴到大图上去
