### ISSUE TITLE
canvas绘制包含抽奖组件的页面，如果抽奖组件里包含跨域图片，会导致绘制失败

### ISSUE THREAD

**Issue by hunterchow** [buuing/lucky-canvas#162]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：vue

- 你当前插件的版本(必填)：^3.4.5

- 详细描述你的bug：我在用html2canvas生成抽奖页面的海报时，如果抽奖组件渲染的canvas里包含跨域的图片，会导致生成的海报里抽奖组件这块是空白（测过如果是相同域下的图片就没问题），我查了一下，根本原因是canvas处理跨域图片出错导致的，所以我在想可不可以加个配置项，给抽奖组件里的所有图片都加个crossOrigin = "Anonymous"属性，这样就能避免该问题了。非常喜欢您的插件，不管结果如何都期待您的回复，谢谢

- 问题代码(重要)：

// 粘贴你的代码
![生成抽奖页面海报代码片段](https://user-images.githubusercontent.com/22702874/141886226-64883392-b946-48c9-84ea-dda3418fab43.png)

**Comment by buuing** [comment]
现在应该也是可以做到的, 我给图片加了一个formatter函数

**Comment by LinYue998** [comment]
@hunterchow 兄弟，你那个奖项是固定的还是不固定的？我不固定的奖项加了formatter后，新增删除奖项，页面就什么都不展示了
