### ISSUE TITLE
背景颜色出现多边形

### ISSUE THREAD

**Issue by ZengJiaHao001** [buuing/lucky-canvas#163]
在普通html页面上,引入官方"设置扇形区域的背景颜色"的demo后,
打开html发现背景中间出现多边形图形(最新版本)
想问一下大佬是什么原因?
(代码完全复制官方例子)

**Comment by buuing** [comment]
感谢反馈问题, 目前已优化该问题

如果你是通过cdn使用的可以替换成下面这个链接 (版本锁定在1.6.5)

```html
<script src="https://cdn.jsdelivr.net/npm/lucky-canvas@1.6.5/dist/index.umd.min.js"></script>
```

如果你是通过npm安装的, 可以通过下面的方式重新安装

```shell
npm i lucky-canvas@1.6.5
```
