### ISSUE TITLE
九宫格，当抽奖动画起来后，关手机屏或切换掉当前程序，再打开程序，最终的定位与预设的有一定概率上偏差

### ISSUE THREAD

**Issue by zjgaynes** [buuing/lucky-canvas#166]
开发环境：
HBuilder X3.29    , vue=2   ,uniapp   H5
luckydraw版本：在lucky-canvas/readme.md72行中lucky-canvas@1.5
测试代码：
let $lucky = this.selectComponent('#myLucky');
$lucky.play()
$lucky.stop(2)

理论上每次都会停留在2的位置，九宫格第一排，最右边的位置
![image](https://user-images.githubusercontent.com/42295293/143365905-717bb18b-c86f-4f60-8024-755590f945ee.png)
实际测试过过程中，正常点击没问题，
但是当动画起来后，关手机屏或切换掉当前程序，再打开程序，最终的定位与预设的2有一定的偏差（不是百分百偏差，存在一定概率）
![image](http://cdn2.zjgonline.com.cn/FvgMYadLJmqzgM7qjE2_j6_6zQuY)

**Comment by zjgaynes** [comment]
期待官方解决方案
九宫格目前临时解决办法是：如果程序有切换到后台，那么最终定位时红圈会被隐藏掉，弹窗告诉用户中的奖品
1、奖品背景色是白，转动时或最终定位的颜色是红色，标记hideFlag
2、在执行转动play前将activeStyle.background设为红
3、onHide里 将hideFlag=true
4、抽奖结束回调里，判断程序是否切换到后台过，if (hideFlag){activeStyle.background=白}

**Comment by buuing** [comment]
该问题已复现, 预计下周修复

**Comment by buuing** [comment]
最新版已修复该问题
