### ISSUE TITLE
微信小程序手机端和模拟器端渲染不一样

### ISSUE THREAD

**Issue by zyyoo** [buuing/lucky-canvas#169]
- 你当前是什么框架(必填)：
- 原生微信小程序

- 你使用的是哪个包(必填)：
- @lucky-canvas/mini@latest

- 你当前插件的版本(必填)：
  
"@lucky-canvas/mini": "0.0.3",

- 详细描述你的bug：

- 模拟器端是正常的,src填写的是七牛图片地址,安卓手机和苹果手机都一样,只能加载一张,
![image](https://user-images.githubusercontent.com/40783859/143913825-4c30a045-9c22-411c-ad7c-97b881195ed2.png)

- 问题代码(重要)：

```
// 粘贴你的代码
```

  prizes: [
      { title: '666元红包', background: '#d1cdf7',imgs: [{ src: "https://qn.zyy223.top/draw2666%20%E7%BA%A2%E5%8C%85.png", width: '33%', top: '35%' }],fonts: [{ text: '666元红包', top: '14%' }] },
      { title: '6.66元红包', background: '#fbf9ff',imgs: [{ src: "https://qn.zyy223.top/draw36.66.png", width: '40%', top: '35%' }],fonts: [{ text: '6.66元红包', top: '14%' }] },
      { title: '18.8元红包', background: '#d1cdf7',imgs: [{ src: "https://qn.zyy223.top/draw218.8%20%E7%BA%A2%E5%8C%85.png", width: '30%', top: '35%' }], fonts: [{ text: '18.8元红包', top: '14%' }] },
      { title: '1元红包', background: '#fbf9ff',imgs: [{ src: "https://qn.zyy223.top/hongbao%20%E6%8B%B7%E8%B4%9D.png", width: '25%', top: '35%' }], fonts: [{ text: '1元红包', top: '18%' }] },
      { title: '188元红包', background: '#d1cdf7',imgs: [{ src: "https://qn.zyy223.top/draw2188%20%E7%BA%A2%E5%8C%85_.png", width: '30%', top: '35%' }],fonts: [{ text: '188元红包', top: '14%' }] },
      { title: '2.88元红包', background: '#fbf9ff',imgs: [{ src: "../../media/images/2.881.png", width: '40%', top: '35%' }],fonts: [{ text: '2.88元红包', top: '14%' }]},
    ],

**Comment by buuing** [comment]
你这个是真机模拟吗? 还是体验版?

**Comment by zyyoo** [comment]
> 你这个是真机模拟吗? 还是体验版?

只是在本地开发用手机预览,不是体验版,使用微信小程序的二维码预览功能,这个上线后,是不是这个问题会消失哈

**Comment by buuing** [comment]
真机体验就是很多bug，跳过他之间看体验版的效果是否一致

**Comment by zyyoo** [comment]
> 真机体验就是很多bug，跳过他之间看体验版的效果是否一致

好的, 我之后上线测试一下,请教一个问题,微信这个奖品图片可以使用本地图片吗,就像下面一样
{ title: '2.88元红包', background: '#fbf9ff',imgs: [{ src: "../../media/images/2.881.png", width: '40%', top: '35%' }],fonts: [{ text: '2.88元红包', top: '14%' }]},

**Comment by buuing** [comment]
微信小程序引入相对路径会出错, 如果是本地图片, 你可以考虑把图片转换成base64传给我

**Comment by zyyoo** [comment]
转换成base64应该怎么使用哈

**Comment by buuing** [comment]
直接把你得到的base64的字符串放到src属性上即可

**Comment by zyyoo** [comment]
上线体验版后,还是有bug ,图片显示不全,我应该怎么修复这个问题~~

**Comment by buuing** [comment]
这样的话，你留下微信号，我晚上到家试一试，如果有问题联系你

**Comment by zyyoo** [comment]
找到问题了!!! 图片src 路径不能有空格, ,  ,,,,,,,,,fuck 腾讯
