### ISSUE TITLE
uniapp大转盘代码放在小程序上，在奖品里添加图片为啥点击抽奖没反应，就好像覆盖了抽奖按钮一样

### ISSUE THREAD

**Issue by GlanceBack** [buuing/lucky-canvas#172]
![image](https://user-images.githubusercontent.com/34115144/144201567-61e0419a-fb11-4048-8328-e7fe4aef4022.png)

**Comment by buuing** [comment]
贴你的代码, 就不能好好填写一下提问模板? 啥信息也没有, 让我猜吗

**Comment by GlanceBack** [comment]
哈哈抱歉没在这个上面提问过

<template>
	<view class="award">
		<view class="award-num">
			你还有1次抽奖机会
		</view>
		<LuckyWheel ref="luckyWheel" width="560rpx" height="560rpx" :blocks="blocks" :prizes="prizes" 
                        :buttons="buttons"
			:defaultStyle="defaultStyle" @start="startCallBack" @end="endCallBack" />
		<view class="award-bottom">
			<view>凡购买1组巴布豆尿裤即可获取1次抽奖机会</view>
			<view>价值1999元小米电视等你来抽</view>
		</view>
		<u-modal v-model="show" title="恭喜您中奖了!" :content="content"></u-modal>
	</view>
</template>

<script>
	import LuckyWheel from '../../components/@lucky-canvas/uni/lucky-wheel'
	export default {
		components: {
			LuckyWheel
		},
		data() {
			return {
				show: false,
				content: "",
				blocks: [{
					padding: '28px',
                                                src:"这里是base64图片，因为引入本地照片报错 500",
                                                width: "300px",
						height: "300px",
						rotate: true,
						top: -10
					}]
				}],
				prizes: [{
						title: '小米电视',
						background: '#fff',
						fonts: [{
							text: '小米电视',
							top: '18%'
						}],
						imgs:[{
                                                        src:"这里是base64图片，因为引入本地照片报错服务器500错误",
                                                        width:"60px",
							top:30
						}]
                                            },
                                               {
						title: '小米电视',
						background: '#fff',
						fonts: [{
							text: '小米电视',
							top: '18%'
						}],
						imgs:[{
                                                        src:"这里是base64图片，因为引入本地照片报错服务器500错误",
                                                        width:"60px",
							top:30
						}]
                                            },
                                                 {
						title: '小米电视',
						background: '#fff',
						fonts: [{
							text: '小米电视',
							top: '18%'
						}],
						imgs:[{
                                                        src:"这里是base64图片，因为引入本地照片报错服务器500错误",
                                                        width:"60px",
							top:30
						}]
                                            },
                                              {
						title: '小米电视',
						background: '#fff',
						fonts: [{
							text: '小米电视',
							top: '18%'
						}],
						imgs:[{
                                                        src:"这里是base64图片，因为引入本地照片报错服务器500错误",
                                                        width:"60px",
							top:30
						}]
                                            },
                                               {
						title: '小米电视',
						background: '#fff',
						fonts: [{
							text: '小米电视',
							top: '18%'
						}],
						imgs:[{
                                                        src:"这里是base64图片，因为引入本地照片报错服务器500错误",
                                                        width:"60px",
							top:30
						}]
                                            },
                                               {
						title: '小米电视',
						background: '#fff',
						fonts: [{
							text: '小米电视',
							top: '18%'
						}],
						imgs:[{
                                                        src:"这里是base64图片，因为引入本地照片报错服务器500错误",
                                                        width:"60px",
							top:30
						}]
                                            },
                                        ],
				buttons: [{
						radius: '50px',
					},
					{
						radius: '45px',
						background: '#fff'
					},
					{
						radius: '41px',
						background: '#f6c66f',
						pointer: false
					},
					{
						radius: '35px',
						background: '#ffdea0',
						fonts: [{
							text: "立即\n抽奖",
							fontSize: "18px",
							fontColor: "#fff",
							lineHeight: "22",
							top: -30,
						}],
						imgs: [{
							src: "base64图片',
							width: '105px',
							top: -60
						}]
					}
				],
				defaultStyle: {
					fontColor: '#d64737',
					fontSize: '14px'
				},
			}
		},
		methods: {
			// 点击抽奖按钮触发回调
			startCallBack() {
				debugger
				// 先开始旋转
				this.$refs.luckyWheel.play()
				// 使用定时器来模拟请求接口
				setTimeout(() => {
					// 3s后得到中奖索引
					let index = Math.random() * 6 >> 0
					// 缓慢停止游戏
					this.$refs.luckyWheel.stop(index)
				}, 3000)
			},
			// 抽奖结束触发回调
			endCallBack(prize) {
				// 奖品详情
				// alert(`恭喜你获得${prize.title}`)
				this.content = prize.title;
				this.show = true;
			}
		}
	}
</script>
<style lang="scss" scoped>
</style>

**Comment by buuing** [comment]
你这代码我没法看, 你拆出来一个可以复现问题的小demo发给我

**Comment by GlanceBack** [comment]
[aaa.zip](https://github.com/buuing/lucky-canvas/files/7632428/aaa.zip)

**Comment by buuing** [comment]
嗯, 晚上我到家看一下, 你留下你的微信, 方便联系你

**Comment by GlanceBack** [comment]
好的，谢谢谢谢....
sjc4430

**Comment by buuing** [comment]
我用你的demo测了一下H5和小程序, 都没有问题, 可以点击
