### ISSUE TITLE
LuckWheel在同一个DOM容器下多次实例化，之前生成的canvas未被销毁

### ISSUE THREAD

**Issue by YiChengHui** [buuing/lucky-canvas#173]
- 你当前是什么框架(必填)：普通html页面 

- 你使用的是哪个包(必填)：lucky-canvas@1.7.4

- 你当前插件的版本(必填)：1.7.4

- 详细描述你的bug： LuckWheel在同一个DOM容器下多次实例化，之前实例生成的canvas未被销毁。

- 从使用者来说，实例化之前可以使用innerHTML清空DOM容器的内容，但是这样使用体验会有所下降（个人认为）

- 建议参考echarts，单个容器只能实例化一个对象并且不会生成多个canvas。（仅个人建议，感谢大佬看完了这段废话23333）

**Comment by buuing** [comment]
可以, 但是貌似没人会多次实例化吧

**Comment by buuing** [comment]
如果你是在做可视化搭建这种需要重新渲染

建议直接调用`init`方法去重置整个抽奖组件, 而不是重新实例化

**Comment by harrisoff** [comment]
还是有这种需求的。

一个成功的抽奖流程可能会像这样：
1. `play()`
2. 调接口
3. 接口返回抽奖结果
4. `stop()`

但是如果 3 报错，比如返回”用户已经参加过抽奖“之类的业务相关错误，在 4 的时候可能会希望重置抽奖状态，而不是停留在某个选项上。。
