### ISSUE TITLE
vue调用老虎机的stop方法无法停止

### ISSUE THREAD

**Issue by Fatzong1997** [buuing/lucky-canvas#174]
点击开始按钮开始老虎机抽奖，调用下面方法，定时器5秒调用停止方法，stop()方法传不传参数都无法停止
begin() {
      this.$refs.myLucky.play();
      // 假设接口的请求速度是5s
      setTimeout(() => {
        // 然后停止游戏 (缓慢停止)
        this.$refs.myLucky.stop(0);
      }, 5000);
    },

**Comment by buuing** [comment]
我看看你的代码

你`stop(0)`, 但是如果你的奖品[0]并没有渲染到插槽内, 就无法停止在第0个奖品

**Comment by Fatzong1997** [comment]
<template>
  <div class="lottery">
    <titlebar titleName="活动抽奖"></titlebar>
    <div class="content1" :style="{ height: mmh }">
      <div class="lhzcontent"></div>
      <SlotMachine
        ref="myLucky"
        width="53vw"
        height="23vw"
        :slots="slots"
        :prizes="prizes"
        :defaultConfig="defaultConfig"
        @end="endCallBack"
        class="lhj"
      />
      <div class="btn" @click="begin"></div>
      <div class="btn1" @click="end"></div>
    </div>
  </div>
</template>

<script>
import titlebar from "../../components/index/titleBar.vue";
import { SlotMachine } from "@lucky-canvas/vue";
import apiFun from "../../servers/apiFun";
import comTool from "../../assets/js/until";
export default {
  components: {
    titlebar,
    SlotMachine,
  },
  data() {
    return {
      mmh: "",
      index: Number,
      timer: null,
      second: 0,

      slots: [
        { speed: 3, direction: -1 },
        { speed: 3, direction: 1 },
        { speed: 3, direction: -1 },
      ],
      prizes: [
        {
          background: "red",
          borderRadius: "3vw",
        },
        {
          background: "black",
          borderRadius: "3vw",
        },
        {
          background: "green",
          borderRadius: "3vw",
        },
      ],
      defaultConfig: {
        rowSpacing: "20px",
        colSpacing: "10px",
      },
      isbegin: 1,
    };
  },
  created() {
    this.index = Math.floor(Math.random() * 8) + 1;
    this.mmh = document.documentElement.clientHeight + "px";
  },
  mounted() {
    console.log(this.$refs.myLucky.stop);
  },
  methods: {
    begin() {
      this.$refs.myLucky.play();
    //   假设接口的请求速度是5s
      setTimeout(() => {
        // 5s后拿到后端返回的中奖索引
        // const index = 0;
        // 然后停止游戏 (缓慢停止)
        this.$refs.myLucky.stop();
      }, 5000);
    }
  },
};
</script>

<style lang="less"  scope>
.lottery {
  overflow: hidden;
}
.content1 {
  margin-top: 13vw;
  background-image: url("../../assets/images/lhzbanner.png");
  background-repeat: no-repeat;
  background-size: 100vw 100%;
  .lhzcontent {
    width: 100vw;
    height: 150vw;
    background-image: url("../../assets/images/lhzhz.png");
    background-repeat: no-repeat;
    background-size: 100vw 150vw;
    position: relative;
    z-index: 999;
  }
  .lhj {
    position: relative;
    top: -74.8vw;
    left: 27.8vw;
  }
  .btn {
    width: 50vw;
    height: 15vw;
    // background: red;
    position: relative;
    top: -66vw;
    left: 30vw;
    z-index: 1000;
  }
  .btn1 {
    width: 50vw;
    height: 15vw;
    background: red;
  }
}
</style>

**Comment by Fatzong1997** [comment]
<SlotMachine
        ref="myLucky"
        width="53vw"
        height="23vw"
        :slots="slots"
        :prizes="prizes"
        :defaultConfig="defaultConfig"
        @end="endCallBack"
        class="lhj"
      />


export default {
  components: {
    titlebar,
    SlotMachine,
  },
  data() {
    return {
      mmh: "",
      index: Number,
      timer: null,
      second: 0,

      slots: [
        { speed: 3, direction: -1 },
        { speed: 3, direction: 1 },
        { speed: 3, direction: -1 },
      ],
      prizes: [
        {
          background: "red",
          borderRadius: "3vw",
        },
        {
          background: "black",
          borderRadius: "3vw",
        },
        {
          background: "green",
          borderRadius: "3vw",
        },
      ],
      defaultConfig: {
        rowSpacing: "20px",
        colSpacing: "10px",
      },
      isbegin: 1,
    };
  },
  created() {
    this.index = Math.floor(Math.random() * 8) + 1;
    this.mmh = document.documentElement.clientHeight + "px";
  },
  mounted() {
    console.log(this.$refs.myLucky.stop);
  },
  methods: {
    begin() {
      this.$refs.myLucky.play();
    //   假设接口的请求速度是5s
      setTimeout(() => {
        // 5s后拿到后端返回的中奖索引
        // const index = 0;
        // 然后停止游戏 (缓慢停止)
        this.$refs.myLucky.stop();
      }, 5000);
    }
  },
};
</script>

**Comment by buuing** [comment]
你更新到这个版本就可以用了, `npm i @lucky-canvas/vue@0.1.1`

**Comment by Fatzong1997** [comment]
好像还是不行

**Comment by buuing** [comment]
> 好像还是不行

你确定你更新到这个版本了吗

**Comment by Fatzong1997** [comment]
"dependencies": {
    "@lucky-canvas/vue": "^0.1.1",
    "animate.css": "^4.1.1",
    "axios": "^0.19.2",
    "clipboard": "^2.0.8",
    "core-js": "^3.6.5",
    "jquery": "^3.6.0",
    "mobile-detect": "^1.4.5",
    "mobile-device-detect": "^0.4.3",
    "vant": "^2.12.27",
    "vue": "^2.6.11",
    "vue-cookies": "^1.7.4",
    "vue-router": "^3.2.0",
    "vuex

**Comment by Fatzong1997** [comment]
确实不行

**Comment by Fatzong1997** [comment]
可以了，加了索引才可以，不可以随机停止吗，我以为可以随机停止，谢谢了

**Comment by buuing** [comment]
你不加索引, 我哪知道你要停在哪

**Comment by buuing** [comment]
用着顺手点个star支持一下

**Comment by Fatzong1997** [comment]
哈哈哈哈
