### ISSUE TITLE
大转盘初始化后只能运行一次

### ISSUE THREAD

**Issue by vfbaspstak** [buuing/lucky-canvas#175]
- 你当前是什么框架(必填)：vue 

- 你使用的是哪个包(必填)：@lucky-canvas/vue

- 你当前插件的版本(必填)：0.1.2

- 详细描述你的bug：大转盘初始化之后只能点击一次，再次点击无反应，初步判定是运行完一次后，startTime没有重置为0，导致点击事件中断了

- 问题代码(重要)：

```
// 粘贴你的代码
```
<template>
  <div class="box">
    <img :src="require('../assets/img/bg.png')" width="100%" />
    <LuckyWheel
      class="luck-draw"
      ref="LuckyWheel"
      width="270px"
      height="270px"
      :blocks="blocks"
      :prizes="prizes"
      :buttons="buttons"
      :default-style="defaultStyle"
      :default-config="defaultConfig"
      @start="startCallBack"
      @end="endCallBack"
    />
  </div>
</template>

<script>
  export default {
    data() {
      return {
        prizes: [],
        buttons: [
          {
            radius: "40px",
            imgs: [
              {
                src: require("../assets/img/button.png"),
                width: "105%",
                top: "-180%",
              },
            ],
          },
        ],
        blocks: [
          { padding: "1px", background: "#fa3e3f" },
          { padding: "10px", background: "#f9d400" },
          { padding: "1px", background: "#e76f51" },
        ],
        defaultStyle: {
          fontColor: "#303133",
          fontSize: "10px",
        },
        defaultConfig: {
          gutter: "1px",
          stopRange: 0,
        },
      };
    },
    mounted() {
      this.getPrizesList();
    },
    methods: {
      getPrizesList() {
        const prizes = [];
        let data = [
          {
            name: "谢谢参与",
            img: require("../assets/img/00.png"),
            color: "#d7d7d7",
          },
          {
            name: "礼物",
            img: require("../assets/img/01.png"),
            color: "#fef43e",
          },
          {
            name: "抽奖券",
            img: require("../assets/img/02.png"),
            color: "#ef7683",
          },
          {
            name: "元宝",
            img: require("../assets/img/03.png"),
            color: "#d7d7d7",
          },
          {
            name: "元宝",
            img: require("../assets/img/04.png"),
            color: "#fef43e",
          },
          {
            name: "抽奖券",
            img: require("../assets/img/02.png"),
            color: "#ef7683",
          },
          // {
          //   name: "元宝",
          //   img: require("../assets/img/06.png"),
          //   color: "#d7d7d7",
          // },
          // {
          //   name: "抽奖券",
          //   img: require("../assets/img/02.png"),
          //   color: "#fef43e",
          // },
        ];
        data.forEach((item) => {
          prizes.push({
            name: item.name,
            background: item.color,
            fonts: [{ text: item.name, top: "10%" }],
            imgs: [{ src: item.img, width: "30%", top: "35%" }],
          });
        });
        this.prizes = prizes;
      },
      startCallBack() {
        this.$refs.LuckyWheel.play();
        setTimeout(() => {
          this.$refs.LuckyWheel.stop((Math.random() * 8) >> 0);
        }, 2000);
      },
      endCallBack() {
        // alert(`恭喜你获得${prize.name}`);
      },
    },
  };
</script>

<style scoped>
  .box {
    position: relative;
    width: 310px;
    height: 310px;
  }
  .luck-draw {
    width: 270px;
    height: 270px;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }
</style>

**Comment by buuing** [comment]
好的, 我看一下

**Comment by buuing** [comment]
你试一下这个版本, `npm i @lucky-canvas/vue@0.1.3`

**Comment by vfbaspstak** [comment]
没好用啊，兄弟，你改哪了呢？
`    // 游戏结束
    if (step === 0) {
      this.endCallback?.(this.prizes.find((prize, index) => index === prizeFlag) || {})
      **this.startTime = 0**
      return
    }`
在这加行代码能行不

**Comment by vfbaspstak** [comment]
没好用啊，兄弟，你改哪了呢？
```
    if (step === 0) {
      this.endCallback?.(this.prizes.find((prize, index) => index === prizeFlag) || {})
      this.startTime = 0
      return
    }
```
在这加行代码能行不

**Comment by buuing** [comment]
跟`startTime`无关, 你确定你是`v0.1.3`的版本吗

**Comment by vfbaspstak** [comment]
我试了下，加上this.startTime = 0就好了，只是不知道会不会有别的问题

**Comment by vfbaspstak** [comment]
![image](https://user-images.githubusercontent.com/38381603/144566646-5bab2886-4fa1-4a5c-bf35-2be479ae7b31.png)

**Comment by vfbaspstak** [comment]
第二次点击的时候在这个位置return掉了
![image](https://user-images.githubusercontent.com/38381603/144567133-42adc2c3-2e25-402b-8763-80fc438ebb48.png)

**Comment by buuing** [comment]
奇怪, 你留个微信, 我晚上到家看一下, 你先临时这样用着

**Comment by vfbaspstak** [comment]
nrsnrx123

**Comment by buuing** [comment]
确实有bug, 最新版已修复该问题`npm i @lucky-canvas/vue@0.1.4`

**Comment by buuing** [comment]
感谢反馈问题
