### ISSUE TITLE
每次start之后转盘会往左上角偏移

### ISSUE THREAD

**Issue by xvbing** [buuing/lucky-canvas#176]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 详细描述你的bug：
![Uploading 115截图20211204150629.png…]()

如图所示 每次执行start之后就会往左上角偏移

- 问题代码(重要)：
如图所示 每次
```
// 粘贴你的代码
```

**Comment by xvbing** [comment]
>

**Comment by buuing** [comment]
?

**Comment by xvbing** [comment]
![115截图20211204150629](https://user-images.githubusercontent.com/31508873/144702649-73507c3f-8d76-4797-b835-ea49285dd6a8.png)
就是这个样子 每次切换窗口

**Comment by buuing** [comment]
用的哪个版本

**Comment by buuing** [comment]
代码贴一下我看看

**Comment by xvbing** [comment]
版本应该是@1.7.7，uni-app装的  复现很好复现  就是切换窗口回来就变了，不过这个上线应该不会有这个吧

<template>
  <view>
    <LuckyWheel 
      ref="luckyWheel" 
      :width="width" 
      :height="height" 
      :blocks="blocks" 
      :prizes="prizes" 
      :buttons="buttons"
      :defaultStyle="defaultStyle" 
      :defaultConfig="defaultConfig"
      @start="startCallBack"
      @end="endCallBack" />
  </view>
</template>

<script>
  import LuckyWheel from '@/components/@lucky-canvas/uni/lucky-wheel'

  export default {
    components: {
      LuckyWheel,
    },
    data() {
      return {
        width: "300px",
        height: "300px",
        blocks: [{
          padding: "13px",
          background: "#d64737"
        }],
        prizes: [{
            name: "恭喜你获得1元红包",
            background: "#f9e3bb",
            fonts: [{
              text: "奥运钞一张",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/1.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得100元红包",
            background: "rgba(249, 227, 187, 1)",
            fonts: [{
              text: "免单一次",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/2.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得0.5元红包",
            background: "#f9e3bb",
            fonts: [{
              text: "一克金条",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/3.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得2元红包",
            background: "rgba(249, 227, 187, 1)",
            fonts: [{
              text: "20元红包",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/4.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得10元红包",
            background: "#f9e3bb",
            fonts: [{
              text: "5元红包",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/5.png",
              top: "50%"
            }]
          }
        ],
        buttons: [{
            radius: "50px",
            background: "#d64737"
          },
          {
            radius: "45px",
            background: "#fff"
          },
          {
            radius: "41px",
            background: "#f6c66f",
            pointer: true
          },
          {
            radius: "35px",
            background: "#ffdea0"
          }
        ],
        defaultStyle: {
          fontColor: "#d64737",
          fontSize: "14px"
        },
        defaultConfig: {
          gutter: '1px',
        },
      }
    },
    props: {
      type: {
        type: Number,
        default: 1,
      }
    },
    mounted() {
      // setTimeout(() => {
      //   this.startCallBack()
      // }, 1000)
    },
    methods: {
      // 点击抽奖按钮触发回调
      startCallBack() {
        // 先开始旋转
        this.$refs.luckyWheel.play()
        // 使用定时器来模拟请求接口
        this.$refs.luckyWheel.stop(this.type -1)
      },
      // 抽奖结束触发回调
      endCallBack(prize) {
        // 奖品详情
        // console.log(prize)
        this.$emit('close')
      }
    }
  }
</script>

<style lang="scss" scoped>

</style>

**Comment by xvbing** [comment]
版本应该是@1.7.7，uni-app装的 复现很好复现 就是切换窗口回来就变了，不过这个上线应该不会有这个吧

`<template>
  <view>
    <LuckyWheel 
      ref="luckyWheel" 
      :width="width" 
      :height="height" 
      :blocks="blocks" 
      :prizes="prizes" 
      :buttons="buttons"
      :defaultStyle="defaultStyle" 
      :defaultConfig="defaultConfig"
      @start="startCallBack"
      @end="endCallBack" />
  </view>
</template>

<script>
  import LuckyWheel from '@/components/@lucky-canvas/uni/lucky-wheel'

  export default {
    components: {
      LuckyWheel,
    },
    data() {
      return {
        width: "300px",
        height: "300px",
        blocks: [{
          padding: "13px",
          background: "#d64737"
        }],
        prizes: [{
            name: "恭喜你获得1元红包",
            background: "#f9e3bb",
            fonts: [{
              text: "奥运钞一张",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/1.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得100元红包",
            background: "rgba(249, 227, 187, 1)",
            fonts: [{
              text: "免单一次",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/2.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得0.5元红包",
            background: "#f9e3bb",
            fonts: [{
              text: "一克金条",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/3.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得2元红包",
            background: "rgba(249, 227, 187, 1)",
            fonts: [{
              text: "20元红包",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/4.png",
              top: "50%"
            }]
          },
          {
            name: "恭喜你获得10元红包",
            background: "#f9e3bb",
            fonts: [{
              text: "5元红包",
              top: "18%"
            }],
            imgs: [{
              width: "30%",
              src: "https://paifou-img.oss-cn-shanghai.aliyuncs.com/deal/other/5.png",
              top: "50%"
            }]
          }
        ],
        buttons: [{
            radius: "50px",
            background: "#d64737"
          },
          {
            radius: "45px",
            background: "#fff"
          },
          {
            radius: "41px",
            background: "#f6c66f",
            pointer: true
          },
          {
            radius: "35px",
            background: "#ffdea0"
          }
        ],
        defaultStyle: {
          fontColor: "#d64737",
          fontSize: "14px"
        },
        defaultConfig: {
          gutter: '1px',
        },
      }
    },
    props: {
      type: {
        type: Number,
        default: 1,
      }
    },
    mounted() {
      // setTimeout(() => {
      //   this.startCallBack()
      // }, 1000)
    },
    methods: {
      // 点击抽奖按钮触发回调
      startCallBack() {
        // 先开始旋转
        this.$refs.luckyWheel.play()
        // 使用定时器来模拟请求接口
        this.$refs.luckyWheel.stop(this.type -1)
      },
      // 抽奖结束触发回调
      endCallBack(prize) {
        // 奖品详情
        // console.log(prize)
        this.$emit('close')
      }
    }
  }
</script>

<style lang="scss" scoped>

</style>
`

**Comment by buuing** [comment]
切换后台, 还是切换页面, 说清楚点

**Comment by buuing** [comment]
h5还是小程序, 我也是服了, 上面的提问模板你去填一下
我这啥信息都没有, 我靠猜吗!

**Comment by buuing** [comment]
你是觉得上面的提问模板是我故意写着玩是嘛, 我闲着没事干了? 你去把上面的信息一个不差的给我填好

**Comment by xvbing** [comment]
你浏览器开两个标签页  来回切就成这样了

行了 就z这吧  GitHub一会儿就断了  想回你还得等半天

（你忽略这个吧  看你样子好像挺生气的 这问题马上就关了 就当不存在吧 大佬 消消气 不至于）

**Comment by buuing** [comment]
我是很不能理解, 为什么我上面写了那么多字, 想让你们把问题描述清楚一点, 就是装作看不到呢???
我想采访你一下, 你看到上面的提问模板的时候, 你是怎么想的

**Comment by buuing** [comment]
你们懒得填写, 就会导致我还得重复提问, 我想破脑袋我不知道为什么你们会装作看不见

**Comment by buuing** [comment]
我也懒得说的, 尊重是相互的
