### ISSUE TITLE
转盘转动时怎么禁用抽奖按钮呢？

### ISSUE THREAD

**Issue by xcdh-xx** [buuing/lucky-canvas#178]
- 你当前是什么框架(必填)：
 uniapp

- 你使用的是哪个包(必填)：
 uniapp

- 你当前插件的版本(必填)：
0.0.4

- 当前环境是小程序还是浏览器(选填)：
小程序

- 详细描述你的bug：
需要在当前抽奖结束前不能点击抽奖按钮，但是转盘转动时可以一直点击抽奖，看了文档没找到抽奖按钮的禁用方法

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
你可以把抽奖按钮理解为一个button, 你在外部加一个变量控制不就得了, 我内部又不知道你想干啥, 你点击抽奖按钮, start回调就会触发, 这很合理

**Comment by xcdh-xx** [comment]
OK啦，感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] 转盘转动时怎么禁用抽奖按钮呢？ (Issue #178)





 
你可以把抽奖按钮理解为一个button, 你在外部加一个变量控制不就得了, 我内部又不知道你想干啥, 你点击抽奖按钮, start回调就会触发, 这很合理
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下
