### ISSUE TITLE
小程序跟H5环境下，怎么让canvas根据不同机型宽高尺寸自适应？

### ISSUE THREAD

**Issue by My-Gao** [buuing/lucky-canvas#179]
因为单位都是px的，怎么修改成rpx呢？求大佬解答下

**Comment by buuing** [comment]
[提问前必看!](https://github.com/buuing/lucky-canvas/issues/177)

**Comment by My-Gao** [comment]
我用的是uniapp，hb插件市场直接引入的，目前项目是uniapp编译成小程序开发及兼容H5端

**Comment by buuing** [comment]
那你直接在插件里使用px单位的地方, 改成rpx试试, 我内部进行处理了

**Comment by My-Gao** [comment]
改成了rpx好像不生效... 直接有些地方背遮住了
![微信图片_20211207143438](https://user-images.githubusercontent.com/35724840/144978732-6a881892-0627-402d-a475-d77015f7d96c.png)

**Comment by buuing** [comment]
我看看你代码怎么用的

**Comment by My-Gao** [comment]
我直接修改了上面的宽高，但是没有占满，是我哪里写错了吗..我对canvas不是很了解..
![111](https://user-images.githubusercontent.com/35724840/144979641-79a3630c-8f29-4603-bf03-19b9b7a8e41c.png)
![222](https://user-images.githubusercontent.com/35724840/144979737-c9971621-dd32-4e3f-baf0-278786928215.png)

**Comment by buuing** [comment]
????? 不要改我源码, 你在外面直接用就行了

我再重复一遍, 我不是反感别人改我代码, 你要是有能力hold得住, 你就改, 你别改完了, 还问我为啥你改的不对

**Comment by buuing** [comment]
我真是服了, 这个包你不要动, 我里面的单位都是计算好的, 你在外面直接看文档使用就行

**Comment by My-Gao** [comment]
我错了大佬.. 我改回来了，我在外面改完了好像整体宽高是生效自适应了，但是blocks里面的padding属性我也用了rpx好像不支持？是只能用px吗？
![111](https://user-images.githubusercontent.com/35724840/144981458-5f1eb15f-b84c-4e2b-aa14-e188dd3fdd05.png)
![222](https://user-images.githubusercontent.com/35724840/144981470-e3414ed9-adcf-4a09-9a13-a0d548e819ab.png)

**Comment by buuing** [comment]
padding属性我好像忘记做适配了, 你先用px吧, 我下个版本增加一下padding响应式

**Comment by My-Gao** [comment]
好的，感谢大佬耐心解答！谢谢！

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下

**Comment by My-Gao** [comment]
已经点了哦~非常好用！
