### ISSUE TITLE
微信小程序环境下，九宫格样式问题

### ISSUE THREAD

**Issue by My-Gao** [buuing/lucky-canvas#180]
组件是用hb插件市场那边导入的，用的是uniapp编译到小程序运行看的，H5端正常，微信小程序端就出现了这个问题，并且层级过高，弹窗啥的全被遮住了
![image](https://user-images.githubusercontent.com/35724840/145137058-4f947818-682b-4961-baa3-1feee318bf5f.png)

**Comment by buuing** [comment]
[# 常见问题汇总](https://github.com/buuing/lucky-canvas/issues/181)

**Comment by My-Gao** [comment]
可为啥这个九宫格他等于是固定定位了，page标签都不包含这个宽高了，直接就悬浮了

**Comment by buuing** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html

**Comment by My-Gao** [comment]
![1](https://user-images.githubusercontent.com/35724840/145139220-3114c388-f79e-4994-a07c-b052b914c0b1.png)
我按照文档的把heightoverflow全部删掉了还是悬浮起来了，有办法解决吗？

**Comment by buuing** [comment]
开发模式 / 真机演示 / 体验版, 你现在是哪个环节
