### ISSUE TITLE
常见问题汇总

### ISSUE THREAD

**Issue by buuing** [buuing/lucky-canvas#181]
### 老虎机的奖品超过10个在苹果手机下报错

跳转相关issues [#258 ](https://github.com/buuing/lucky-canvas/issues/297)

<br />

### 在vue中页面报错`Object(...) is not a function`

跳转相关issues #258 

<br />

### 小程序里canvas的层级太高了，把弹窗挡住了怎么办

小程序内canvas是原生组件，所以默认就是顶层渲染，对此你可以百度 cover 组件或是查看 [小程序文档](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)

<br />

### 微信开发者工具的真机调试有bug

嗯, 他的真机调试就是有bug, 直接跳过去看体验版

<br />

### 微信小程序使用老虎机报错

你必须保持小程序的`基准库`大于等于 `2.17.0`, 否则低版本的基准库会报错

<br />

### 微信开发者工具中老虎机的插槽有白色的底色无法去除

![image](https://user-images.githubusercontent.com/36689704/147905881-3f07c3a6-d1e4-4c80-96cd-ce8a6fec9610.png)

插槽的滑动轨道本应该是透明的, 但是在微信开发者工具上显示为白色, 这个无需担心, 我在体验版上测试ok, 是透明的, 应该是开发者工具渲染有问题, 等待微信官方后续修复即可

<br />

### IE11显示 Promise 未定义, 怎么办

把下面的CDN在插件前面引入即可
```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```

### uniapp+vue3或taro+vue3里图片显示有问题

升级到最新版

<br />

**Comment by zhouzhangfan** [comment]
弱弱得问一下，微信小程序中可以使用老虎机了吗，我引入的"@lucky-canvas/mini": "0.0.4"里面现在只有lucky-grid和lucky-wheel

**Comment by buuing** [comment]
> 弱弱得问一下，微信小程序中可以使用老虎机了吗，我引入的"@lucky-canvas/mini": "0.0.4"里面现在只有lucky-grid和lucky-wheel

现在最新版可以了

**Comment by kratospan** [comment]
想问一下，因为好像也不是bug，我就在这里问了。
就是，可以开始抽奖之后，但是结束的时候不传index什么的吗？？
因为有时候接口会报错，但是我看stop()这个好像必须传一个值，我原本是以为如果什么都不传的话就会停下来。
其实最重要的就是不要变成那种，抽奖成功的效果，就让用户觉得自己已经中奖了。

**Comment by buuing** [comment]
试试 `init()` 方法, 重置抽奖

**Comment by kratospan** [comment]
谢了，已经解决了

**Comment by yzk214806293** [comment]
小程序里canvas的层级太高了，把弹窗挡住了怎么办

**Comment by buuing** [comment]
> 小程序里canvas的层级太高了，把弹窗挡住了怎么办

上面不是说了吗, 百度 cover 组件如何使用!

**Comment by yzk214806293** [comment]
是要写到你的组件里面吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月10日(星期三) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] 常见问题汇总 (Issue #181)





  
小程序里canvas的层级太高了，把弹窗挡住了怎么办
  
上面不是说了吗, 百度 cover 组件如何使用!

**Comment by buuing** [comment]
@yzk214806293 如果是要写到我的组件里, 我为什么自己不加上呢, 还要让用户去加, 这不符合逻辑! 所以他肯定是要加载你的页面里!
