### ISSUE TITLE
请问老虎机三列有办法控制分别停留在哪个图片上吗？

### ISSUE THREAD

**Issue by tjswk2008** [buuing/lucky-canvas#182]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
目前还不能, 预计下周才能支持这个功能, 我还在构思应该如何传参

**Comment by tjswk2008** [comment]
感谢大佬

**Comment by fondadam** [comment]
老虎机可以设置未中奖吗？ 比如三个slot分别不同

**Comment by buuing** [comment]
> 老虎机可以设置未中奖吗？ 比如三个slot分别不同

可以, 等下周发版

**Comment by buuing** [comment]
最新版已增加该需求, 可以停在不同奖品位置了, @tjswk2008 @fondadam

| js | vue | react |
| :-: | :-: | :-: |
| `lucky-canvas@1.7.11` | `@lucky-canvas/vue@0.1.6` | `@lucky-canvas/react@0.1.4` |

需要传入一个数组`stop([x, x, x, ....])`, 数组长度必须要跟slots的长度保持一致

假设3个插槽
  - 如果你想三个插槽都停在第0个奖品, 那你可以传`stop(0)`或`stop([0, 0, 0])`
  - 如果你想三个插槽分别停在第0, 1, 2个奖品, 那你可以传入`stop([0, 1, 2])`
  - 如果你想三个插槽分别停在第2, 1, 2个奖品, 那你可以传入`stop([2, 1, 2])`

**Comment by tjswk2008** [comment]
666

**Comment by a354123417** [comment]
> 最新版已增加该需求, 可以停在不同奖品位置了, @tjswk2008 @fondadam
> 
> js	vue	react
> `lucky-canvas@1.7.11`	`@lucky-canvas/vue@0.1.6`	`@lucky-canvas/react@0.1.4`
> 需要传入一个数组`stop([x, x, x, ....])`, 数组长度必须要跟slots的长度保持一致
> 
> 假设3个插槽
> 
> * 如果你想三个插槽都停在第0个奖品, 那你可以传`stop(0)`或`stop([0, 0, 0])`
> * 如果你想三个插槽分别停在第0, 1, 2个奖品, 那你可以传入`stop([0, 1, 2])`
> * 如果你想三个插槽分别停在第2, 1, 2个奖品, 那你可以传入`stop([2, 1, 2])`

如果传入数组 end 的结果是 undefined ，咋整

**Comment by buuing** [comment]
end里拿到`undefined`, 那说明你没中奖啊, 你问我咋整? 中没中奖不应该是你自己控制的吗, 你来问我?

**Comment by a354123417** [comment]
@buuing stop传入了奖品索引呢

**Comment by buuing** [comment]
那说明你传的不对, 按照当前的抽奖逻辑, 我抽不到这个奖品的时候, 也会返回`undefined`

**Comment by buuing** [comment]
你去官网的 `playground` 里复现一个小 demo 发给我

**Comment by a354123417** [comment]
https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlFQAZXAShwofAKYB3KGPwoAwgEM%2BENXQB0AZQw82AWTU4AFmFkAKAOQBiVJnEpbAGigBvKly5zYbOYAXFC2AEwALAAMLAAe7j6%2B5jJgAObmbCG2AIwAHDHxbolcAEaG%2BHQhANrFvp5QLGog4HypWdkF7lAlZnipjDxYfCBZ9rkAbACcOABmarZQAL5FvnUNTS1toR1xXT34-YPDozKTMrkzMgvLtQC6K750hmyVUDWrXPU8jCAyjNVRDzZDxhDwAZg8EQ8AFYPOMPAB2Dy5DyTe5QcCMGQ4NhgfghbJLB6rL4-P7VYFQUFQCFQKFQWFQeFQJFQFFQSYeKLozHY3H4qBoQk3D5eKDfX7-N7U2n0xnM1nszlQQFQbI8sBYnF4vgEol3YkNZgALxkr3eH3qM34L2q9TYMlimVCUS6bB4LHa0IApNdbvrRVabeb7Y7nTk3R6vb6lv6RZaoNa%2BLa3qGnVkwpHPdsfX6Awmkymqmnw2Cs9G8-GSYng3aoA706EIuWczHFnHDZ8a8mQ-Ww1loS2crnY-nq4Xew3w%2BMh9kR%2B2x2sJ3Wp1kEbP5x3al3l6m%2B43bLkN22t4Hu0WS1lJsfK4b7rVfnMsBg2Ho2CgMDIQt5RSUJX8ACUmjALBXgAST4GYrDAd9O26XpDiGEZQnsfZoRkK44MLPQwFNLIwTCXYsJtFQeEMKUHDBKjbFqKsMRkJ8X1IyC0m-bcoAGOQ9EaHArC2cJOjg3gMG4sw%2BPaTpaMNGRhigawWBNGQAEovHY0hSG4fg6DImQdEMVJ5MUpTaMSRZjK4dSoEAAH1AGnNQAOO0AeCNEl4AQhBYDA1BQABxNQkBkSQ5JUuAiFU1ZRBcHR3M86xzMeGQ2AAFTAPzBjYawYskEKfw%2BSzAHEFQA%2B6LpKBAFnPQBlv0AHPN2JcwQOLNAKLVFKplWVcZ71FLgqlVVUETa9qqmZAbesa9kRtudixtFSzAHi0wAuc0ANeVAAA5QARv0AB1NADtjKqtKEKxfliAKsToKpTECHRGA0EAeCQDKACoiqIELuTUjTAGAYwAKVygQQPSgQBO00AVZtAB0FQAja0c9jwuUHRPpYawdsdWKuGWBkoiiJSAG5TMSSzACr9QB650AFHtAC5PRIou83yZBixI6HiiCHUYLQMHSoKstqYmfL88n4bhJHkdoUgGGYdhqCAA

39行的注释打开，有概率出现 undefined，还有个问题，设置了多个中奖，只返回了一个奖品

**Comment by buuing** [comment]
你给我逗笑了, 这个叫老虎机抽奖! 谢谢, 你去百度一下[老虎机抽奖在什么情况下是中奖的](https://www.baidu.com), 可以吗
<img width="481" alt="image" src="https://user-images.githubusercontent.com/36689704/161733764-022b92cf-95cb-4941-bdc4-73dc390e5421.png">

**Comment by a354123417** [comment]
自掌三十巴掌

**Comment by MakeBetterMe** [comment]
如果每个插槽里面，奖品有重复的话，这种场景请问支持吗？
现在希望插槽出现重复奖品的话（其实主要是产品想拉低中奖率，类似每个插槽会有重复的哭脸），我是改插槽order来实现重复的，比较纠结的时候，像这种场景下，停止的时候，如何传参
