### ISSUE TITLE
vue2中使用按需引入报错

### ISSUE THREAD

**Issue by ChestnutNeko** [buuing/lucky-canvas#184]
vue2
"vue": "^2.6.11",
"@lucky-canvas/vue": "^0.1.5",
Google浏览器
报错后已删node_modules、package-lock.json文件重新下载
![image](https://user-images.githubusercontent.com/49029763/145175157-e7f59de3-98f4-413a-b91b-c8123cbace69.png)
系统运行正常，页面空白
![image](https://user-images.githubusercontent.com/49029763/145175260-aadb6716-053b-40a2-981c-c9fe443ecfc7.png)
```
import { LuckyWheel } from '@lucky-canvas/vue';
Vue.components('LuckyWheel', LuckyWheel)
```
大佬帮忙看下，非常感谢

**Comment by ChestnutNeko** [comment]
已解决，完整引入可以了

**Comment by buuing** [comment]
好的, 晚上我到家看一下这个问题
