### ISSUE TITLE
大转盘游戏，奖品名称超长可以展示省略号吗

### ISSUE THREAD

**Issue by ChestnutNeko** [buuing/lucky-canvas#186]
大转盘游戏，奖品名称超长默认折行显示，或设置不折行（如图），但是无省略号，导致文字重叠。这边需求奖品名称最多50个字符，该怎么调整呢
![image](https://user-images.githubusercontent.com/49029763/145355747-82fac989-2ef6-489b-8bcd-53587555955a.png)

"@lucky-canvas/vue": "^0.1.5",
"vue": "^2.6.11",
```
this.prizes[i].fonts[0].fontSize = 20;
this.prizes[i].fonts[0].wordWrap = false;
this.prizes[i].fonts[0].lengthLimit = "90%";
```

**Comment by buuing** [comment]
可以, 用`lineClamp: 1`

**Comment by buuing** [comment]
文档我晚上补充一下, 上次忘了加了

**Comment by ChestnutNeko** [comment]
真是太感谢了！！
