### ISSUE TITLE
大转盘文字是否支持圆形环绕效果

### ISSUE THREAD

**Issue by ChestnutNeko** [buuing/lucky-canvas#187]
how old am I，怎么老是我……
和设计互相折磨的一天

文字可以实现贴边环绕吗？
需求
![image](https://user-images.githubusercontent.com/49029763/145383577-c05bdd31-3eb4-426b-9b25-455fcf4a00bc.png)
我的
![image](https://user-images.githubusercontent.com/49029763/145383776-eea59c34-45ea-47d6-a0c9-9bbc4ed438e0.png)

**Comment by buuing** [comment]
暂时不能, 后续或许会考虑

目前你要是想达到这个效果, 只能让ui把文字切成图片

**Comment by ChestnutNeko** [comment]
嗯嗯好的

**Comment by ChestnutNeko** [comment]
![image](https://user-images.githubusercontent.com/49029763/145558120-9203b19a-2f75-42ac-a9f6-1c04d7ca496c.png)
大佬打扰啦~按钮和转盘之间z-index可以加多少呢？想加个指针，但是好像不是按钮。不好加的话我让设计都切成按钮

**Comment by buuing** [comment]
你加我微信得了`new_ldq`

**Comment by ChestnutNeko** [comment]
加了，感谢大佬！
