### ISSUE TITLE
stop()里不传索引号，传id可以实现吗

### ISSUE THREAD

**Issue by gf0120** [buuing/lucky-canvas#188]
- 你当前是什么框架(必填)：
vue

- 你使用的是哪个包(必填)：
@lucky-canvas/vue

- 你当前插件的版本(必填)：
0.1.5

- 当前环境是小程序还是浏览器(选填)：
浏览器

- 详细描述你的bug：
- 大佬求指教
stop()里不放索引号换成存放后端给的id可以吗，我这边试了使用从后端返回的id放到stop()里是不行的；
刚开始我的转盘里的奖品的数据是后端返回的，点击抽奖后端随机返回一个奖品，把奖品的id放进去试了是不能停在指定的奖品上的。
奖品id例子：id: "4028819f7db6f897017db6fab5ba0004"
![image](https://user-images.githubusercontent.com/79499066/146133219-a9007f97-b9b2-4680-9c86-4b70497ea3cb.png)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by ChestnutNeko** [comment]
让后端传奖品数据带id，中奖id和奖品list中id比较就能找到index

**Comment by buuing** [comment]
你自己拿着id去prizes数组里找索引不就得了吗, 连一个数组遍历都懒得做吗?

**Comment by gf0120** [comment]
好的谢谢两位大佬，有思路了
