### ISSUE TITLE
如何在同一页面设置多个，并且相互独立

### ISSUE THREAD

**Issue by yang302** [buuing/lucky-canvas#189]
- 你当前是什么框架(必填)：taro

- 你使用的是哪个包(必填)：lucky-canvas/taro/react

- 你当前插件的版本(必填)： "@lucky-canvas/taro": "^0.0.4",

- 当前环境是小程序还是浏览器(选填)：小程序

- 详细描述你的bug：在同一页面设置多个大转盘抽奖，页面只会显示一个

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
{/*转盘*/}
        <Swiper className="luckyWheelSwiper"
                indicatorDots
                autoplay={false}>
          <SwiperItem>
            <LuckyWheel/>
          </SwiperItem>
          <SwiperItem>
            <LuckyWheel1/>
          </SwiperItem>
        </Swiper>
// 代码结束
```

**Comment by buuing** [comment]
安装最新版 `npm i @lucky-canvas/taro@latest`

新增 canvasId 属性, 防止同一个页面出现多个 canvas 时, 无法正常渲染的问题

同一个页面 canvasId 必须唯一
