### ISSUE TITLE
Cannot delete property 'toString' of function () { [native code] }

### ISSUE THREAD

**Issue by akkobb** [buuing/lucky-canvas#192]
- 你当前是什么框架(必填)：taro raect

- 你使用的是哪个包(必填)：npm install @lucky-canvas/taro@latest

- 你当前插件的版本(必填)：
-  "@babel/runtime": "^7.7.7",
    "@lucky-canvas/taro": "0.0.5",
    "@tarojs/cli": "3.3.15",
    "@tarojs/components": "3.3.15",
    "@tarojs/react": "3.3.15",
    "@tarojs/runtime": "3.3.15",
    "@tarojs/taro": "3.3.15",
    "lodash": "4.17.15",
    "react": "^16.10.0",
    "react-dom": "^16.10.0",
    "taro-plugin-canvas": "^1.0.10",
    "taro-ui": "^3.0.0-alpha.3"

- 当前环境是小程序还是浏览器(选填)：小程序 taro开发

- 详细描述你的bug：按照文档引入后 报错 不知道改哪里
- 
![image](https://user-images.githubusercontent.com/29198583/146890979-23dfa05b-8fdb-4a64-be03-52f3612df229.png)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
![image](https://user-images.githubusercontent.com/29198583/146890788-f78f6da7-28c0-4d42-aa5e-a4d586a9ea52.png)

// 代码结束
```

**Comment by buuing** [comment]
加我微信`new_ldq`吧, 你拆个小demo发给我

**Comment by buuing** [comment]
问题排查完毕, 该用户引入了一个kivicube插件, 才出现了这个奇怪的报错

去掉kivicube之后, 抽奖显示正常

不能去掉kivicube的情况下, 就只能嵌套webview了

**Comment by stcer** [comment]
我们项目也遇到时样的错误， 未使用kivicube插件
"@tarojs/cli": "3.3.15",
"@lucky-canvas/taro": "0.0.6",

**Comment by buuing** [comment]
也可能是别的插件影响, 你可以新开一个小 demo 用来测试, 看看新项目里是否可以正常运行

**Comment by stcer** [comment]
开了新项目，只建一个demo文件没有出现类似错误

**Comment by stcer** [comment]
"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@lucky-canvas/taro": "^0.0.6",
    "@tarojs/components": "3.3.15",
    "@tarojs/react": "3.3.15",
    "@tarojs/runtime": "3.3.15",
    "@tarojs/taro": "3.3.15",
    "laco": "^1.2.1",
    "md5": "^2.2.1",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "taro-ui": "^3.0.0-alpha.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.3.15",
    "@tarojs/mini-runner": "3.3.15",
    "@tarojs/webpack-runner": "3.3.15",
    "@types/react": "^17.0.2",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "babel-preset-taro": "3.3.15",
    "cross-env": "^7.0.2",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.3.15",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "stylelint": "9.3.0",
    "typescript": "^4.1.0"
  }

**Comment by stcer** [comment]
我把相同的依赖放在新项目，也是正常的

**Comment by buuing** [comment]
> 我把相同的依赖放在新项目，也是正常的

两个项目的 taor-cli 的版本也是一致的吗

**Comment by stcer** [comment]
是的， 完全拷贝的

**Comment by buuing** [comment]
既然完全一样, 那你在新项目上开发不就得了, 把页面目录都粘贴过来

**Comment by stcer** [comment]
好主意， 我们试试

**Comment by buuing** [comment]
我怀疑之前的老项目, 在生成模板的时候, 可能出现了 bug, 但是 taro 团队在新的模板里修复了这个问题?

**Comment by stcer** [comment]
还是不行， 我们在dev开发模式上是可用的
build出来不行， 我们使用了腾讯的直播插件， 
如果去掉直播插件build出来就没有问题
使用插件的状态下build的代码有何区别？

**Comment by buuing** [comment]
那结果似乎很明显, 腾讯的直播插件影响的我?
 
按理说 `toString` 是原型方法, 不应该

那你只能嵌套一个 webview 了

**Comment by stcer** [comment]
好的， 多谢

**Comment by stcer** [comment]
将项目clone下来， 把需要文件拷贝到taro项目src中引入，如
`import { LuckyWheel } from '../../components/luckDraw' `
项目build出来可以正常运行， 

可能是开发者工具或是taro生成的代码，在引入npm包时出了问题？

**Comment by buuing** [comment]
那就奇怪了, 不都是一样的代码吗

**Comment by stcer** [comment]
是的， 感觉是腾讯开发工具或是taro使用webpack生成代码时哪儿出问题
我这里src/app.config.ts, 把plugins配置上就重现这个错误
```
# src/app.config.ts
export default {
  pages: [
    'pages/index/index',
    'pages/index/demo'
  ],
  plugins: {
    'live-player-plugin': {
      version: '1.3.2',
      provider: 'wx2b03c6e691cd7370'
    }
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}
```

**Comment by buuing** [comment]
那很大概率问题出在taro上面, 因为uniapp那边从没出现过这个报错

**Comment by aBian9394** [comment]
用的 cli 搭建的 uniapp 项目 也有这个问题 插件版本是 v0.0.5.0

**Comment by buuing** [comment]
> 用的 cli 搭建的 uniapp 项目 也有这个问题 插件版本是 v0.0.5.0

你确定是这个报错吗

**Comment by aBian9394** [comment]
> > 用的cli搭建的uniapp项目也有这个问题插件版本是v0.0.5.0
> 
> 你确定是这个报错吗

是的

**Comment by buuing** [comment]
这个关于 toString 的报错好像是没问题了, 保持核心依赖`lucky-canvas`大于等于`1.7.16`即可
