### ISSUE TITLE
大转盘错位

### ISSUE THREAD

**Issue by zxzyoutlook** [buuing/lucky-canvas#195]
框架：uniapp 

安装包：lucky-canvas-1.7.13.tgz，使用 npm install @lucky-canvas/uni@latest 命令安装

版本：1.7.13

环境：浏览器

问题描述：首次进入抽奖页面正常，点击抽奖也正常，刷新浏览器再点击抽奖出现二个转盘

问题代码：

```
// 代码开始

// 代码结束
```

**Comment by buuing** [comment]
项目是用 hbx 创建的还是用 cli 创建的

**Comment by zxzyoutlook** [comment]
hbx

**Comment by buuing** [comment]
hbx 是否是稳定版的最新版

**Comment by zxzyoutlook** [comment]
hbx 版本3.1.9

**Comment by buuing** [comment]
更新最新版试试
