### ISSUE TITLE
直接调用stop方法会导致程序崩溃

### ISSUE THREAD

**Issue by motongbike** [buuing/lucky-canvas#196]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：1.7.13

- 当前环境是小程序还是浏览器(选填)：
谷歌浏览器-Chrome
版本 92.0.4515.131（正式版本） （64 位）

- 详细描述你的bug：
使用的大转盘抽奖，每个奖品配置了中奖权重
prizes:[{range:10},{range:0}...]
类似这样配置。
使用stop方法停止转盘的时候，传入了停止的索引，能够正常停止，不传入参数，会导致程序崩溃。
详细的可以看我下面贴的代码，谢谢。

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
      console.log("转盘开始");
      // 开始游戏
      this.$refs.myLucky.play()
      // 假设接口的请求速度是5s
      timeOut = setTimeout(() => {
        // 5s后拿到后端返回的中奖索引
        // const index = 0;
        // 然后停止游戏 (缓慢停止)
        // this.$refs.myLucky.stop(index);
        // this.$refs.myLucky.stop((Math.random() * 6) >> 0); //能正常停止
        // this.$refs.myLucky.stop(null);//能正常停止
        this.$refs.myLucky.stop();//卡死
      }, 3000);

// 代码结束
```

**Comment by buuing** [comment]
提供一个可以复现问题的小demo发一下

**Comment by motongbike** [comment]
`<template>
  <div class="container" id="container">
    <lucky-wheel
      ref="myLucky"
      width="10rem"
      height="10rem"
      :blocks="blocks"
      :prizes="prizes"
      :buttons="buttons"
      :default-style="defaultStyle"
      @start="click"
      @end="end"
    />
  </div>
</template>

<script>
export default {
  name: "baji",
  data() {
    return {
        blocks: [{ padding: '13px', background: '#d64737' }],
        prizes: [
          { title: '1元红包', background: '#f9e3bb', fonts: [{ text: '1元红包', top: '18%' }], range: 0.1 },
          { title: '100元红包', background: '#f8d384', fonts: [{ text: '100元红包', top: '18%' }], range: 0.2 },
          { title: '0.5元红包', background: '#f9e3bb', fonts: [{ text: '0.5元红包', top: '18%' }] },
          { title: '2元红包', background: '#f8d384', fonts: [{ text: '2元红包', top: '18%' }] },
          { title: '10元红包', background: '#f9e3bb', fonts: [{ text: '10元红包', top: '18%' }] },
          { title: '50元红包', background: '#f8d384', fonts: [{ text: '50元红包', top: '18%' }] },
        ],
        buttons: [
          { radius: '50px', background: '#d64737' },
          { radius: '45px', background: '#fff' },
          { radius: '41px', background: '#f6c66f', pointer: true },
          {
            radius: '35px', background: '#ffdea0',
            fonts: [{ text: '开始\n抽奖', fontSize: '18px', top: -18 }]
          }
        ],
        defaultStyle: { fontColor: '#d64737', fontSize: '14px' },
    };
  },
  props: {},
  components: {},
  mounted() {
    // this.$refs.myLucky.play();
  },
  methods: {
        click () {
          this.$refs.myLucky.play()
          setTimeout(() => {
            // this.$refs.myLucky.stop() //卡死
            this.$refs.myLucky.stop(0) //正常
          }, 100)
        },
        end (prize) {
          console.log(prize.fonts[0].text)
        }
  },
};
</script>

<style lang="less" scoped >
.container {
  height: 100vh;
  display: flex;
  // justify-content: center;
  align-items: center;
  flex-direction: column;
}
</style>
`

**Comment by motongbike** [comment]
```<template>
  <div class="container" id="container">
    <lucky-wheel
      ref="myLucky"
      width="10rem"
      height="10rem"
      :blocks="blocks"
      :prizes="prizes"
      :buttons="buttons"
      :default-style="defaultStyle"
      @start="click"
      @end="end"
    />
  </div>
</template>

<script>
export default {
  name: "baji",
  data() {
    return {
        blocks: [{ padding: '13px', background: '#d64737' }],
        prizes: [
          { title: '1元红包', background: '#f9e3bb', fonts: [{ text: '1元红包', top: '18%' }], range: 0.1 },
          { title: '100元红包', background: '#f8d384', fonts: [{ text: '100元红包', top: '18%' }], range: 0.2 },
          { title: '0.5元红包', background: '#f9e3bb', fonts: [{ text: '0.5元红包', top: '18%' }] },
          { title: '2元红包', background: '#f8d384', fonts: [{ text: '2元红包', top: '18%' }] },
          { title: '10元红包', background: '#f9e3bb', fonts: [{ text: '10元红包', top: '18%' }] },
          { title: '50元红包', background: '#f8d384', fonts: [{ text: '50元红包', top: '18%' }] },
        ],
        buttons: [
          { radius: '50px', background: '#d64737' },
          { radius: '45px', background: '#fff' },
          { radius: '41px', background: '#f6c66f', pointer: true },
          {
            radius: '35px', background: '#ffdea0',
            fonts: [{ text: '开始\n抽奖', fontSize: '18px', top: -18 }]
          }
        ],
        defaultStyle: { fontColor: '#d64737', fontSize: '14px' },
    };
  },
  props: {},
  components: {},
  mounted() {
    // this.$refs.myLucky.play();
  },
  methods: {
        click () {
          this.$refs.myLucky.play()
          setTimeout(() => {
            // this.$refs.myLucky.stop() //卡死
            this.$refs.myLucky.stop(0) //正常
          }, 100)
        },
        end (prize) {
          console.log(prize.fonts[0].text)
        }
  },
};
</script>

<style lang="less" scoped >
.container {
  height: 100vh;
  display: flex;
  // justify-content: center;
  align-items: center;
  flex-direction: column;
}
</style>
```

**Comment by motongbike** [comment]
就很简单的一个，stop不传参数就会卡死，传了参数（数字类型），正常。

**Comment by buuing** [comment]
我这边测试了一下, 没问题

**Comment by motongbike** [comment]
你用的是哪个版本呢？

**Comment by buuing** [comment]
`@lucky-canvas/vue@0.1.6` `lucky-canvas@1.7.13`

**Comment by motongbike** [comment]
谢谢，重新安装了一个，貌似没有那个问题了，谢谢了。
