### ISSUE TITLE
Taro 2.4.5能支持吗

### ISSUE THREAD

**Issue by LeeFlower** [buuing/lucky-canvas#199]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
不知道, 应该不支持
