### ISSUE TITLE
奖品之间的分割线显示不出来

### ISSUE THREAD

**Issue by 861621821** [buuing/lucky-canvas#200]
- 你当前是什么框架(必填)：vue2.6

- 你使用的是哪个包(必填)：@lucky-canvas/vue

- 你当前插件的版本(必填)：0.1.6

- 当前环境是小程序还是浏览器(选填)：浏览器（微信H5）

- 详细描述你的bug：奖品之间的分割线显示不出来
![image](https://user-images.githubusercontent.com/38489305/148877247-478df855-3013-40d4-9c89-a57bb483238c.png)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
你这个是背景图片吗, 背景图片就是会盖在缝隙上面, 你懂得
