### ISSUE TITLE
kbone + React 开发小程序

### ISSUE THREAD

**Issue by Alimanman** [buuing/lucky-canvas#202]
用的是 React 的代码模式
引用 import { LuckyGrid } from '@lucky-canvas/react' 就报错
在正常 React 下开发是没有问题的，只有在kbone + React 开发小程序转译会这样如下图。

![image](https://user-images.githubusercontent.com/24752506/149308173-0100787f-1bd5-4470-9bef-7ae8eca1a20e.png)

感谢回复噢~~~

**Comment by buuing** [comment]
我没弄过`kbone`, 不过你既然是在小程序中使用, 可以尝试一下`@lucky-canvas/mini`这个包

`@lucky-canvas/mini`本身是在原生微信小程序中使用的, 所以不确定是否可以做到开箱可用的状态

**Comment by Alimanman** [comment]
> 我没弄过`kbone`, 不过你既然是在小程序中使用, 可以尝试一下`@lucky-canvas/mini`这个包
> 
> `@lucky-canvas/mini`本身是在原生微信小程序中使用的, 所以不确定是否可以做到开箱可用的状态

好的好的，谢谢兄弟～
我自己再探索下，找到好方法再share到这里喔3
