### ISSUE TITLE
如何在小程序中使用老虎机

### ISSUE THREAD

**Issue by zhouzhangfan** [buuing/lucky-canvas#203]
- 你当前是什么框架(必填)：原生微信小程序

- 你使用的是哪个包(必填)："@lucky-canvas/mini"

- 你当前插件的版本(必填)： "0.0.4"

- 当前环境是小程序还是浏览器(选填)：小程序

- 详细描述你的bug：包里面没有slot-machine？只有lucky-grid和lucky-wheel

![image](https://user-images.githubusercontent.com/30466232/149462092-8da6768e-41ac-4bb7-a172-3089dbde6e94.png)

如何在小程序中使用老虎机？

**Comment by buuing** [comment]
年后再发布, 不着急

**Comment by zhouzhangfan** [comment]
。。。设计图都给老总了orz

**Comment by buuing** [comment]
练个star都不点, 催啥催, 年后

**Comment by zhouzhangfan** [comment]
马上点 能不能给个压缩包

**Comment by buuing** [comment]
周末我发个版

**Comment by zhouzhangfan** [comment]
感谢大佬

**Comment by buuing** [comment]
最新版已增加老虎机抽奖, `npm i @lucky-canvas/mini@0.0.5`, 同时基准库不能低于`2.17.0`, 否则会报错

**Comment by zhouzhangfan** [comment]
感谢，新年快乐！

**Comment by zhouzhangfan** [comment]
确实不好意思，还有点问题需要大佬帮忙看下
![1642354346(1)](https://user-images.githubusercontent.com/30466232/149671161-fa20d35b-cffe-47c1-ab45-04e5ad747bbb.jpg)
引入0.0.5版本后微信开发者工具的控制台就报了如上图所示的warning
![1642354098(1)](https://user-images.githubusercontent.com/30466232/149671223-e7d32eb7-e0f0-40d1-9dfe-f369002488e8.jpg)
然后页面上引入，配置好，运行后页面上无显示，渲染出来的wxml，dom树见上面
![image](https://user-images.githubusercontent.com/30466232/149671287-e11ea944-3cb5-438e-836c-e45c56546269.png)
image没生成出来？麻烦大佬看下

**Comment by zhouzhangfan** [comment]
我的基础库是2.21.2，我的配置
```
machine: {
      blocks: {
        borderRadius: '4px',
        background: 'red',
        padding: '5px'
      },
      prizes: [
        {
          borderRadius: '4px',
          background: 'green',
          fonts: {
            text: '111'
          }
        },
        {
          borderRadius: '4px',
          background: 'red',
          fonts: {
            text: '222'
          }
        },
        {
          borderRadius: '4px',
          background: 'blue',
          fonts: {
            text: '333'
          }
        }
      ],
      slots : [
        { speed: 30, direction: -1 },
        { speed: 30, direction: 1 },
        { speed: 30, direction: -1 },
      ],
      defaultConfig : {
        colSpacing: "1vw",
      },
      // defaultStyle
    }
```
```
 <slot-machine
        id="machine" class="machine_inner"
        width="300px" height="300px"
        slots="{{machine.slots}}" prizes="{{machine.prizes}}"
        />
```

**Comment by zhouzhangfan** [comment]
![image](https://user-images.githubusercontent.com/30466232/149673069-9178bbf5-a3ea-46ec-b920-72d8ea4dc96e.png)
捣鼓了一晚上 就只把blocks显示出来了，prizes和slots出不来

**Comment by zhouzhangfan** [comment]
```
<slot-machine
        id="machine" class="machine_inner"
        width="300px" height="300px"
        blocks="{{machine.blocks}}"
        slots="{{machine.slots}}" prizes="{{machine.prizes}}"
        defaultConfig="{{machine.defaultConfig}}"
        defaultStyle="{{machine.defaultStyle}}"
        bindend="end"
        />
```
不知道是组件问题还是配置问题

**Comment by buuing** [comment]
加一下我微信, `new_ldq`

**Comment by buuing** [comment]
该问题排查完毕, 最新版已修复
