### ISSUE TITLE
基础示例→九宫格抽奖→使用图片作为背景→未弹起代码；

### ISSUE THREAD

**Issue by woniu6162** [buuing/lucky-canvas#204]
基础示例 九宫格 中的  使用图片作为背景，点击没有弹出代码，不知道是不是报错bug了。我按照 配置项 中配置背景图，确实没有生效，转盘的是可以生效的。

**Comment by buuing** [comment]
感谢反馈, 是我忘了提交代码了, 你可以先参考大转盘的背景使用方式

**Comment by buuing** [comment]
晚上我更新一下文档

**Comment by woniu6162** [comment]
> 晚上我更新一下文档

感谢，等你更新了我明天再试试效果；
