### ISSUE TITLE
抽奖过程中很大几率会渲染第一个格子

### ISSUE THREAD

**Issue by KAROTT7** [buuing/lucky-canvas#205]
- 你当前是什么框架(必填)：Vue

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：v0.1.6

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
![lottery](https://user-images.githubusercontent.com/21054747/150990076-3e7b9394-3d24-4b5f-9005-5004ce49620c.gif)
package/core/src/lib/grid.ts 有问题
在加速和匀速之间有比较大的几率渲染第一个格子（也就是 this.currIndex 会为 0）,看动图

- 问题代码(重要)：
文件 package/core/src/lib/grid.ts 中 this.draw 方法有问题，是因为在抽奖过程中 this.currIndex = 0 导致的，直接打开项目示例，打印 this.currIndex ，你会看到  this.currIndex = 0
暂时可以通过下列代码解决问题
```js
616 if (this.currIndex !== 0 && this.step !== 0) {
617    this.draw()
618 }
```

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
什么意思, 我看你的 gif 图片上点的不是 `stop(0)`吗

**Comment by KAROTT7** [comment]
你看图片里前三秒，渲染不正确
九宫格渲染示例里多跑几次抽奖，有一定几率会在加速过程中渲染其他格子的同时也会渲染一次第一个格子

**Comment by KAROTT7** [comment]
对了 speed 设置成 10 出现 bug 的时候会看的明显一点

**Comment by buuing** [comment]
哦, 这是因为程序判断, 在你设置的停止时间内, 以当前的速度无法停在你想要的索引, 才出现的瞬间加速, 目的是为了保证停止时间的毫秒级控制

**Comment by buuing** [comment]
你晒一下你设置的 `defaultConfig` 我看看是怎么配置的

**Comment by KAROTT7** [comment]
![image](https://user-images.githubusercontent.com/21054747/150992657-680805c2-6bbb-4210-ad5a-1ae689d0c61e.png)
对，所以要加上我上面说的那行代码，在抽奖过程中，this.currIndex === 0 的时候不要执行 this.draw()
-----------------
我跑的就是 core 里的九宫格示例，只是把 speed 改成了 10，和配置没关系，speed 设置成 10 也是为了让抽奖跑慢点好看清bug

**Comment by buuing** [comment]
我这里速度改成 10 并没有复现你这个情况....?

**Comment by KAROTT7** [comment]
多跑几次，你跑个十次，一直盯着看，百分之 20-30的几率会出现

**Comment by buuing** [comment]
加一下我的微信`new_ldq`

**Comment by buuing** [comment]
该问题已修复, 更新到最新版即可

```diff
+ lucky-canvas@1.7.19
+ @lucky-canvas/vue@0.1.7
```
