### ISSUE TITLE
江湖救急：onStart 方法里 为啥拿不到当前组件的最新数据

### ISSUE THREAD

**Issue by Clycheng** [buuing/lucky-canvas#224]
![image](https://user-images.githubusercontent.com/30332511/126613567-333d3021-8609-4e31-95db-1870eaef3c86.png)

react Hook

**Comment by beifang721** [comment]
@Clycheng 嗨大佬，你是如何解决的？

**Comment by pingping2116** [comment]
解决了吗？我用react也遇到了这个问题，最后通过暂时使用重新setState时取上一次的值解决了

**Comment by beifang721** [comment]
在组件填上需要更新数据的 key

**Comment by Clycheng** [comment]
> @Clycheng 嗨大佬，你是如何解决的？

我把最新数据放到sessionStorage里了
