### ISSUE TITLE
[建议]老虎机抽奖添加中奖指示器（箭头/线段等）

### ISSUE THREAD

**Issue by Itswag** [buuing/lucky-canvas#227]
- 类似这种多列横向滚动，抽奖结束后没办法表示中奖奖品位置，且其余位置顺序未打乱（竖向滚动如果超出三行同理）
![1](https://user-images.githubusercontent.com/39112652/153736486-488b0d1d-e1a3-4bc9-aaf1-9d42dc391333.gif)

- 下图是csgo游戏中抽奖界面，黄线在停止滚动后落在奖品上，还有边缘模糊功能
![2](https://user-images.githubusercontent.com/39112652/153736635-fe3aa02d-4f2d-4cd1-90e5-ff21db8b7301.gif)

- 仅仅是建议，自己用css实现会被canvas遮挡，也不懂能不能直接用canvas实现 - 。 -

**Comment by buuing** [comment]
嗯, 一般大家都是用图片盖在上面, 我想想在小程序里如何优化这个问题

**Comment by buuing** [comment]
你可以看一下官网 => 示例 => 完整示例 => 最后一个仿滴滴的demo, 那个指针是通过图片的方式在blocks里面引入的

**Comment by Itswag** [comment]
![QQ截图20220214110653](https://user-images.githubusercontent.com/39112652/153793485-60248120-7642-48bc-8e01-93c9b2ce7ef6.png)
确实可以,之前有一瞬间想过用背景图片……

还有就是非中奖项乱序显示应该会更好点

**Comment by buuing** [comment]
可以乱序显示, 请仔细看老虎机提供的`测试Demo`

**Comment by Itswag** [comment]
![image](https://user-images.githubusercontent.com/39112652/153794717-5a0cdd3f-808b-434f-9e4b-f4cf900c3981.png)
我的意思是如果是多列显示的情况，非中奖行/列（上图的电影票和放映带）乱序，可能让滚动逻辑更复杂了...

**Comment by buuing** [comment]
而且奖品位置也是可以打乱的, 只是你没有配置而已, 也请参考文档!

**Comment by buuing** [comment]
你去看看order属性, 这个就是为了打乱奖品排序做的

**Comment by buuing** [comment]
不过你确实提醒到我了, 现在官网缺少一个打乱奖品排序的demo, 今晚我补充一个

**Comment by Itswag** [comment]
感谢指教🤡

**Comment by Itswag** [comment]
那这样是不是可以在自定义顺序的前提下做个默认的乱序配置

**Comment by buuing** [comment]
没必要, 你这就把简单的事搞复杂了, order你们可以随便配置
