### ISSUE TITLE
可以增加圆形的9宫格吗

### ISSUE THREAD

**Issue by clyan** [buuing/lucky-canvas#229]
如下：
奖励摆放是一个圆形，抽奖的形式跟九宫格的形式一样
![image](https://user-images.githubusercontent.com/46644748/154013749-832da068-08d5-4767-a8d4-0e7ea7bb2ce5.png)

**Comment by buuing** [comment]
在现有的基础上, 通过配置应该是可以实现的

**Comment by buuing** [comment]
你加我微信`new_ldq`

**Comment by TinsFox** [comment]
```
blocks: [{ padding: '10px', background: '#F5F5F5', borderRadius: width/2 }],
```
配置borderRadius为 width/2 ，width=height的情况下就可以变成圆了
![image](https://user-images.githubusercontent.com/33956589/154037639-21463e4e-0fad-4df7-b069-9f1d6fc98a98.png)
![image](https://user-images.githubusercontent.com/33956589/154037727-ba6584aa-e4a0-416f-a49e-fe2be94e5c76.png)

**Comment by buuing** [comment]
不是, 你没发现他的奖品格子也都是圆形排列的吗

**Comment by buuing** [comment]
官网新增加了圆形九宫格的示例
