### ISSUE TITLE
[feat] ts 类型提示支持

### ISSUE THREAD

**Issue by TinsFox** [buuing/lucky-canvas#230]
- 你当前是什么框架(必填)：
react + vite

- 你使用的是哪个包(必填)：
@lucky-canvas/react

- 你当前插件的版本(必填)：
    "@lucky-canvas/react": "^0.1.5",

希望可以增加在ts下的类型提示

**Comment by buuing** [comment]
你先用`lucky-canvas`这个包吧, react包有另一个小伙伴在尝试支持ts

**Comment by TinsFox** [comment]
> 

好嘞，谢谢

**Comment by codedart2018** [comment]
正在等　react ts

**Comment by codedart2018** [comment]
@lucky-canvas/taro　这个包里也没ts types文件。好久能支持呀
