### ISSUE TITLE
支援傳遞自定的隨機數生成器來取代 `Math.random()`

### ISSUE THREAD

**Issue by bluelovers** [buuing/lucky-canvas#232]
希望能支援傳遞自定的隨機數生成器來取代 `Math.random()`
有兩種形式可以參考

1. 具有 `.next()` 方法的物件

![image](https://user-images.githubusercontent.com/167966/154824750-c88bd075-ab81-4a3a-ba63-7782becd663d.png)

2. 會回傳一個隨機數的函數

如此一來 就能支援類似這種可以自訂算法或重現隨機結果過程
https://github.com/bluelovers/ws-random/blob/master/packages/%40lazy-random/generators-seedrandom/dist/index.d.ts

**Comment by buuing** [comment]
如果你是想在前端自定义中奖概率, 你可以看一下`prizes[x].random`属性, 可以用来单独设置某个奖品的中奖概率
