### ISSUE TITLE
老虎机的插槽配置为单个对象不渲染吗？

### ISSUE THREAD

**Issue by AhYiaaa** [buuing/lucky-canvas#233]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：@lucky-canvas/vue

- 你当前插件的版本(必填)："^0.1.8"

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：slots选项配置为单个对象时不渲染显示

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
你是想让我猜吗? 代码都不贴一个?

**Comment by AhYiaaa** [comment]
这边需求是单列抽奖，作者大大这边slots配置最少必须为两个对象吗？求支招

**Comment by buuing** [comment]
谁说的最少配置两个? 你自己猜的吗?

**Comment by AhYiaaa** [comment]
> 谁说的最少配置两个? 你自己猜的吗?

但是我配置为单个对象页面不渲染欸
代码部分这样的啊：
 blocks: [
        {
          imgs: [
            {
              src: require("../assets/images/chouqukuang.png"),
              width: "100%",
              height: "100%",
            },
          ],
        },
      ],
      slots: [{ order: [0, 1, 2], direction: 1 }],
      prizes: [
        { fonts: [{ text: "四川xxxx有限公司", top: "15%" }] },
        { fonts: [{ text: "xxxxxxxxxxx", top: "15%" }] },
        { fonts: [{ text: "xxxxxxxxxxxssss", top: "15%" }] },
      ],
      defaultStyle: {
        borderRadius: 0,
        fontSize: "32px",
        fontColor: "#333",
      },
      defaultConfig: {
        rowSpacing: "0px",
        colSpacing: "0px",
      },

**Comment by buuing** [comment]
这不挺好的吗, [点这个地址查看](https://100px.net/playground.html?code=JTNDZGl2JTIwaWQlM0QlMjJteS1sdWNreSUyMiUzRSUzQyUyRmRpdiUzRSUwQSUwQSUzQ3NjcmlwdCUzRSUwQSUyMCUyMGNvbnN0JTIwbXlMdWNreSUyMCUzRCUyMG5ldyUyMEx1Y2t5Q2FudmFzLlNsb3RNYWNoaW5lKCclMjNteS1sdWNreSclMkMlMjAlN0IlMEElMjAlMjAlMjAlMjB3aWR0aCUzQSUyMCcyMDBweCclMkMlMEElMjAlMjAlMjAlMjBoZWlnaHQlM0ElMjAnMjAwcHgnJTJDJTBBJTIwJTIwJTIwJTIwYmxvY2tzJTNBJTIwJTVCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaW1ncyUzQSUyMCU1QiUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1RCUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMCU3RCUyQyUwQSUyMCUyMCUyMCUyMCU1RCUyQyUwQSUyMCUyMCUyMCUyMHNsb3RzJTNBJTIwJTVCJTdCJTIwb3JkZXIlM0ElMjAlNUIwJTJDJTIwMSUyQyUyMDIlNUQlMkMlMjBkaXJlY3Rpb24lM0ElMjAxJTIwJTdEJTVEJTJDJTBBJTIwJTIwJTIwJTIwcHJpemVzJTNBJTIwJTVCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTIwZm9udHMlM0ElMjAlNUIlN0IlMjB0ZXh0JTNBJTIwJTIyJUU1JTlCJTlCJUU1JUI3JTlEeHh4eCVFNiU5QyU4OSVFOSU5OSU5MCVFNSU4NSVBQyVFNSU4RiVCOCUyMiUyQyUyMHRvcCUzQSUyMCUyMjE1JTI1JTIyJTIwJTdEJTVEJTIwJTdEJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTIwZm9udHMlM0ElMjAlNUIlN0IlMjB0ZXh0JTNBJTIwJTIyeHh4eHh4eHh4eHglMjIlMkMlMjB0b3AlM0ElMjAlMjIxNSUyNSUyMiUyMCU3RCU1RCUyMCU3RCUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMCU3QiUyMGZvbnRzJTNBJTIwJTVCJTdCJTIwdGV4dCUzQSUyMCUyMnh4eHh4eHh4eHh4c3NzcyUyMiUyQyUyMHRvcCUzQSUyMCUyMjE1JTI1JTIyJTIwJTdEJTVEJTIwJTdEJTJDJTBBJTIwJTIwJTIwJTIwJTVEJTJDJTBBJTIwJTIwJTIwJTIwZGVmYXVsdFN0eWxlJTNBJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwYm9yZGVyUmFkaXVzJTNBJTIwMCUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMGZvbnRTaXplJTNBJTIwJTIyMzJweCUyMiUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMGZvbnRDb2xvciUzQSUyMCUyMiUyMzMzMyUyMiUyQyUwQSUyMCUyMCUyMCUyMCU3RCUyQyUwQSUyMCUyMCUyMCUyMGRlZmF1bHRDb25maWclM0ElMjAlN0IlMEElMjAlMjAlMjAlMjAlMjAlMjByb3dTcGFjaW5nJTNBJTIwJTIyMHB4JTIyJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwY29sU3BhY2luZyUzQSUyMCUyMjBweCUyMiUyQyUwQSUyMCUyMCUyMCUyMCU3RCUyQyUwQSUyMCUyMCU3RCklMEElMjAlMjBteUx1Y2t5LnBsYXkoKSUwQSUzQyUyRnNjcmlwdCUzRSUwQQ==)

**Comment by AhYiaaa** [comment]
> 这不挺好的吗, [点这个地址查看](https://100px.net/playground.html?code=JTNDZGl2JTIwaWQlM0QlMjJteS1sdWNreSUyMiUzRSUzQyUyRmRpdiUzRSUwQSUwQSUzQ3NjcmlwdCUzRSUwQSUyMCUyMGNvbnN0JTIwbXlMdWNreSUyMCUzRCUyMG5ldyUyMEx1Y2t5Q2FudmFzLlNsb3RNYWNoaW5lKCclMjNteS1sdWNreSclMkMlMjAlN0IlMEElMjAlMjAlMjAlMjB3aWR0aCUzQSUyMCcyMDBweCclMkMlMEElMjAlMjAlMjAlMjBoZWlnaHQlM0ElMjAnMjAwcHgnJTJDJTBBJTIwJTIwJTIwJTIwYmxvY2tzJTNBJTIwJTVCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaW1ncyUzQSUyMCU1QiUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1RCUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMCU3RCUyQyUwQSUyMCUyMCUyMCUyMCU1RCUyQyUwQSUyMCUyMCUyMCUyMHNsb3RzJTNBJTIwJTVCJTdCJTIwb3JkZXIlM0ElMjAlNUIwJTJDJTIwMSUyQyUyMDIlNUQlMkMlMjBkaXJlY3Rpb24lM0ElMjAxJTIwJTdEJTVEJTJDJTBBJTIwJTIwJTIwJTIwcHJpemVzJTNBJTIwJTVCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTIwZm9udHMlM0ElMjAlNUIlN0IlMjB0ZXh0JTNBJTIwJTIyJUU1JTlCJTlCJUU1JUI3JTlEeHh4eCVFNiU5QyU4OSVFOSU5OSU5MCVFNSU4NSVBQyVFNSU4RiVCOCUyMiUyQyUyMHRvcCUzQSUyMCUyMjE1JTI1JTIyJTIwJTdEJTVEJTIwJTdEJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTIwZm9udHMlM0ElMjAlNUIlN0IlMjB0ZXh0JTNBJTIwJTIyeHh4eHh4eHh4eHglMjIlMkMlMjB0b3AlM0ElMjAlMjIxNSUyNSUyMiUyMCU3RCU1RCUyMCU3RCUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMCU3QiUyMGZvbnRzJTNBJTIwJTVCJTdCJTIwdGV4dCUzQSUyMCUyMnh4eHh4eHh4eHh4c3NzcyUyMiUyQyUyMHRvcCUzQSUyMCUyMjE1JTI1JTIyJTIwJTdEJTVEJTIwJTdEJTJDJTBBJTIwJTIwJTIwJTIwJTVEJTJDJTBBJTIwJTIwJTIwJTIwZGVmYXVsdFN0eWxlJTNBJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwYm9yZGVyUmFkaXVzJTNBJTIwMCUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMGZvbnRTaXplJTNBJTIwJTIyMzJweCUyMiUyQyUwQSUyMCUyMCUyMCUyMCUyMCUyMGZvbnRDb2xvciUzQSUyMCUyMiUyMzMzMyUyMiUyQyUwQSUyMCUyMCUyMCUyMCU3RCUyQyUwQSUyMCUyMCUyMCUyMGRlZmF1bHRDb25maWclM0ElMjAlN0IlMEElMjAlMjAlMjAlMjAlMjAlMjByb3dTcGFjaW5nJTNBJTIwJTIyMHB4JTIyJTJDJTBBJTIwJTIwJTIwJTIwJTIwJTIwY29sU3BhY2luZyUzQSUyMCUyMjBweCUyMiUyQyUwQSUyMCUyMCUyMCUyMCU3RCUyQyUwQSUyMCUyMCU3RCklMEElMjAlMjBteUx1Y2t5LnBsYXkoKSUwQSUzQyUyRnNjcmlwdCUzRSUwQQ==)

谢谢大佬可以了

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下
