### ISSUE TITLE
组件在vue3中渲染的问题

### ISSUE THREAD

**Issue by Shay7sev** [buuing/lucky-canvas#235]
- 你当前是什么框架(必填)：taro

- 你使用的是哪个包(必填)："@lucky-canvas/taro": "^0.0.11",

- 你当前插件的版本(必填)："@lucky-canvas/taro": "^0.0.11",

- 当前环境是小程序还是浏览器(选填)：小程序

- 详细描述你的bug：
- setup之后mounted中组件使用play方法提示报错：play of undefined，console是有值的。我设置setTimeout1秒给play，就不会报错，我猜测是setup时组件没有完全渲染吗？导致mounted中ref.value是null？但为什么console出来的ref.value不是null

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
<template>
  <view>
    <LuckyWheel ref="myLucky" width="600rpx" height="600rpx" :prizes="prizes" :blocks="blocks"></LuckyWheel>
  </view>
</template>

<script>
import { ref, reactive, toRefs, onMounted, } from 'vue'
import { LuckyWheel } from '@lucky-canvas/taro/vue'
export default {
  components: { LuckyWheel },
  setup() {
    const myLucky = ref(null)
    const state = reactive({
      blocks: [{ padding: '33px', background: '#617df2' },
      ],
      prizes: [
        { fonts: [{ text: '0', top: '10%' }], background: '#e9e8fe' },
        { fonts: [{ text: '1', top: '10%' }], background: '#b8c5f2' }
      ],

    })
    onMounted(() => {
      // setTimeout(() => {
      console.log('myLucky.value', myLucky.value)
      myLucky.value.play()
      // }, 0)
    })
    return {
      ...toRefs(state),
      myLucky,
    }
  },
}
</script>
// 代码结束
```
<img width="1217" alt="截屏2022-02-23 下午4 26 01" src="https://user-images.githubusercontent.com/69033911/155283743-3ac72761-68d4-47e7-8967-d4c3bcd7e6bc.png">
<img width="1217" alt="截屏2022-02-23 下午4 29 05" src="https://user-images.githubusercontent.com/69033911/155284120-bf8fa9fd-76a1-436d-915f-29f68436a071.png">

setTimeout 1s后
<img width="1217" alt="截屏2022-02-23 下午4 26 45" src="https://user-images.githubusercontent.com/69033911/155283842-5c5aff02-c5da-4f72-9e1f-4f82f021273e.png">

**Comment by buuing** [comment]
是的呀, setup不是相当于created吗, 我的组件内部需要创建canvas, 所以你至少也要在mounted之后才能调用play

**Comment by JakeWoki** [comment]
请教下taro+vue3怎么用画布的？
`<canvas style="width: 100%; height: 200px" type="2d" canvas-id="test" ref="test" />`

const ctx = Taro.createCanvasContext('test', this)
绘制不了东西

**Comment by buuing** [comment]
@JakeWoki 抽奖无法绘制了?

**Comment by JakeWoki** [comment]
@buuing 不好意思，这个我还没开始用，只是我在taro+vue3用不了画布，想问一下怎么用还是taro的bug什么的

**Comment by buuing** [comment]
你去看一下我的代码不就得了, 源码都在这个仓库里

**Comment by JakeWoki** [comment]
你的是vue2的写法，我在taro物料市场找到了个vue3的，我研究研究，打扰了
