### ISSUE TITLE
在Vue中调用play()失败，转盘没有启动

### ISSUE THREAD

**Issue by anytinz** [buuing/lucky-canvas#239]
- 你当前是什么框架(必填)： Vue

- 你使用的是哪个包(必填)：@lucky-canvas/vue

- 你当前插件的版本(必填)：^0.1.8

- 当前环境是小程序还是浏览器(选填)：浏览器 & Electron

- 详细描述你的bug：在Vue中调用play()失败，转盘没有启动，控制台没有报错，插入console.log可以打印

- 问题代码(重要)：

```
// 代码开始
<script lang="ts" setup>
import { ref } from 'vue'
const myLucky = ref(null)

const state = {
  blocks: [{ padding: '13px', background: '#617df2' }],
  prizes: [
    { fonts: [{ text: '0', top: '10%' }], background: '#e9e8fe' },
    { fonts: [{ text: '1', top: '10%' }], background: '#b8c5f2' },
    { fonts: [{ text: '2', top: '10%' }], background: '#e9e8fe' },
    { fonts: [{ text: '3', top: '10%' }], background: '#b8c5f2' },
    { fonts: [{ text: '4', top: '10%' }], background: '#e9e8fe' },
    { fonts: [{ text: '5', top: '10%' }], background: '#b8c5f2' },
  ],
  buttons: [
    { radius: '50px', background: '#617df2' },
    { radius: '45px', background: '#afc8ff' },
    {
      radius: '40px', background: '#869cfa',
      pointer: true,
      fonts: [{ text: '开始\n抽奖', top: '-20px' }],
    }
  ]
}

//点击抽奖按钮会触发star回调
const startCallBack = () => {
  // 调用抽奖组件的play方法开始游戏
  myLucky.value?.play()
  // 模拟调用接口异步抽奖
  setTimeout(() => {
    // 假设后端返回的中奖索引是0
    const index = 0
    // 调用stop停止旋转并传递中奖索引
    myLucky.value?.stop(index)
  }, 3000)
}

// 抽奖结束会触发end回调
const endCallBack = (prize: any) => {
  console.log(prize)
}

</script>

<template>
  <LuckyWheel
    ref="myLucky"
    width="200px"
    height="200px"
    :blocks="state.blocks"
    :prizes="state.prizes"
    :buttons="state.buttons"
    @start="startCallBack"
    @end="endCallBack"
  />
</template>

<style>
</style>
// 代码结束
```
![Snipaste_2022-02-26_23-37-38](https://user-images.githubusercontent.com/24619961/155849356-6a6ae369-e42f-4099-98f0-77758b1869cc.png)
![Snipaste_2022-02-26_23-37-12](https://user-images.githubusercontent.com/24619961/155849359-3782c8cc-db36-451a-bbd1-bfd396d9fc45.png)

**Comment by buuing** [comment]
我看不到你是在什么时候调用 play 方法的

**Comment by anytinz** [comment]
点击抽奖按钮的时候

**Comment by buuing** [comment]
可以复现一个小 demo 发给我吗

**Comment by anytinz** [comment]
[lucky-canvas-demo.zip](https://github.com/buuing/lucky-canvas/files/8146960/lucky-canvas-demo.zip)

**Comment by buuing** [comment]
我测试了一下 vue-cli 搭建的项目是可以正常运行的, 而你发的这个 vite 搭建的项目则无法开启游戏

如果你执意想要使用这个 vite , 那你只能直接使用 `lucky-canvas` 这个包了

- 安装

```shell
npm i lucky-canvas@1.7.20
```

- 使用

```html
<script lang="ts" setup>
import { ref, onMounted } from 'vue';
import { LuckyWheel } from 'lucky-canvas'

const myLucky = ref(null);

onMounted(() => {
  const $lucky = new LuckyWheel(myLucky.value as any, {
    width: '300px',
    height: '300px',
    blocks: [{ padding: '13px', background: '#617df2' }],
    prizes: [
      { fonts: [{ text: '0', top: '10%' }], background: '#e9e8fe' },
      { fonts: [{ text: '1', top: '10%' }], background: '#b8c5f2' },
      { fonts: [{ text: '2', top: '10%' }], background: '#e9e8fe' },
      { fonts: [{ text: '3', top: '10%' }], background: '#b8c5f2' },
      { fonts: [{ text: '4', top: '10%' }], background: '#e9e8fe' },
      { fonts: [{ text: '5', top: '10%' }], background: '#b8c5f2' },
    ],
    buttons: [
      { radius: '50px', background: '#617df2' },
      { radius: '45px', background: '#afc8ff' },
      {
        radius: '40px', background: '#869cfa',
        pointer: true,
        fonts: [{ text: '开始\n抽奖', top: '-20px' }],
      }
    ],
    start: function () {
      $lucky.play()
      setTimeout(() => {
        const index = 0;
        $lucky.stop(index);
      }, 3000);
    },
    end: function (prize) {
      console.log(prize);
    }
  })
})
</script>

<template>
  <div ref="myLucky"></div>
</template>

<style>
</style>
```

**Comment by buuing** [comment]
另外, 用着顺手可以点个 star 支持一下

**Comment by anytinz** [comment]
可否发你用vue-cli的搭的demo看一下

**Comment by anytinz** [comment]
&emsp;&emsp; 我怀疑我们运行的差异与vue版本有关而不是webpack/vite，我在使用vue-cli的情况下，默认安装版本为3.2.31且使用官网文档下的示范代码，这个时候打印play()下的this指针，并没有$lucky，切换到3.1.5后一切恢复正常；下面是我用vue-cli搭建的demo以及两个版本下this指针的对比

[test-luckycanvas-vuecli-3.2.31.zip](https://github.com/buuing/lucky-canvas/files/8159494/test-luckycanvas-vuecli-3.2.31.zip)

^vue@3.1.5

![image](https://user-images.githubusercontent.com/24619961/156121847-e73afa1e-ada6-436c-8b3d-e2ca8c3f6161.png)

^vue@3.2.31

![image](https://user-images.githubusercontent.com/24619961/156121855-817aaef6-a4c4-4d0b-97fd-3d666c1033d4.png)

**Comment by buuing** [comment]
这个`$lucky`是`new LuckyCanvas.LuckyWheel()`返回的实例对象, 我只能认为是vite在构建时出现了问题, 才导致的

不然, 我这个是已经打包好的, 按理说, 不应该出现这种不同项目下拿不到实例对象的结果

**Comment by anytinz** [comment]
可是vue-cli下也出了问题了，而且通过更换vue的版本也确实能稳定复现问题

**Comment by buuing** [comment]
你觉得是rollup打包出了问题, 还是vue出了问题

**Comment by anytinz** [comment]
感觉会不会是vue在3.2对ref()所做的优化导致的？..[https://github.com/vuejs/core/pull/3995](https://github.com/vuejs/core/pull/3995)

**Comment by buuing** [comment]
.....这根ref有啥关系.....他影响的是我package内部的class构造函数, 我特意打了一个没编译的包, 然后运行发现class的返回值竟然变成了undefined

**Comment by buuing** [comment]
@edison1105 大佬, 你看看, 我感觉是vue构建时候的问题?

**Comment by anytinz** [comment]
我从3.2.21到3.2.31都测了一遍，只有3.2.31有这个问题...可能需要提个issue去vue那边

**Comment by buuing** [comment]
可以的, 估计是最新版不太稳定

**Comment by weijunliang23** [comment]
我用vite运用您写的代码报nodetype 的错是咋回事啊

**Comment by anytinz** [comment]
我目前升级到vue@^3.2.32，问题依然没解决，依旧不返回$lucky实例..

**Comment by anytinz** [comment]
> 我用vite运用您写的代码报nodetype 的错是咋回事啊

@weijunliang23 可以看一下代码吗

**Comment by buuing** [comment]
解决方案: ~~你们直接使用`lucky-canvas`这个包不就得了~~ => **最新版已修复该问题**

**Comment by heartccace** [comment]
vue禁用了以$和_开头的属性命名，vue3使用代理创建对象的时候，在拷贝$lucky属性的时候默认忽略了该属性，建议不要使用_和$来对变量命名.修改方案是修改了vue核心包属性拷贝里面对变量$lucky进行放行。

**Comment by buuing** [comment]
> vue禁用了以$和_开头的属性命名，vue3使用代理创建对象的时候，在拷贝$lucky属性的时候默认忽略了该属性，建议不要使用_和$来对变量命名.修改方案是修改了vue核心包属性拷贝里面对变量$lucky进行放行。

确实是这个问题导致的, 感谢提醒, 最新版`@lucky-canvas/vue@0.1.11`已修复该bug
