### ISSUE TITLE
奖励文字能否设置多行，并且单独设置大小与颜色

### ISSUE THREAD

**Issue by ztyhal** [buuing/lucky-canvas#241]
- 你当前是什么框架(必填)：vue 

- 你使用的是哪个包(必填)：1.7.20

- 你当前插件的版本(必填)：1.7.20

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
-  奖励文字能不能设置两行，并且单独设置样式
![image](https://user-images.githubusercontent.com/39219035/156750776-24eb20ca-e6a8-45dc-85eb-2b0bd12d65f6.png)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
可以, 因为fonts是数组
