### ISSUE TITLE
[question] 九宫格跑马灯滚动方向

### ISSUE THREAD

**Issue by TinsFox** [buuing/lucky-canvas#243]
- 你当前是什么框架(必填)：react

- 你使用的是哪个包(必填)：@lucky-canvas/react

- 你当前插件的版本(必填)：0.1.5

- 当前环境是小程序还是浏览器(选填)：浏览器
 
跑马灯的滚动方向可以暴露属性出来自定义吗？现在是一列一列的跑，有没有顺时针或者是逆时针的配置方式呀

**Comment by buuing** [comment]
顺时针和逆时针其实就是根据`prizes`列表的顺序去渲染的

这里给你个 [顺时针+逆时针的demo](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlFQAZXAShwofAKYB3KGPwoAwgEM%2BENXQB0SggHFmIABQByAMSpM4lGYA0UAN5UuXObDYALAFxQzAEwADEEsAB4Orm5eMmAA5l5sfoEh4ZFuUIw8cnR%2BAfZRXLwYuVD5hVAARhg8%2BKUA2hVcTlAsaiDgfHHJAIyhEY6VavhxWVh8IMkWABwAbACcOABmamZQAL4FGc2t7Z3d-n1pg8N4ozzjk-4WMvMy00sya5sVALpbbizMAF4yDVCkUhQQBeGYA300AESlNZxQMJ%2BIKOFBwjYfDItWFQHoIpEvbbQ9GYqCIjHIqFouFY4k4tzvCqA1o-P5%2BeoAoGAMASIbSgTt0fDCdiUSy3GSoLyiT0SRk6dy-ASxRK3FK8TKKUF5Vw6TSMsM2JAZABlNgoDAyPwuXFDEZjCZTRaLDpmCpUrggGQrLAYNgGo0m5xQi1nK1XSyVaY4ACsSwCDoyTqgLrdHpU-CW8VNULoLBkMiuPUdH3WAEoonTAAD6gGnNKKiWw6FgYNQoExFsgMZjsahUIA)

**Comment by buuing** [comment]
也就是说, 你只需要排列好`prizes`数组的顺序, 就可以控制方向
