### ISSUE TITLE
wepack or Vue-Cli imgs not work 

### ISSUE THREAD

**Issue by onepisYa** [buuing/lucky-canvas#245]
- 你当前是什么框架(必填)：Vue 2

- 你使用的是哪个包(必填)：lucky-canvas

- 你当前插件的版本(必填)：    "@lucky-canvas/vue": "^0.1.8",

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：LuckyWheel 配置之后，imgs 里面的 图片无法解析出来。我使用的是 Vue-Cli 版本为 5.0.1  ，我将我的图片放置在 assets 文件夹中，但是在使用 Vue-Cli 的时候 无法访问图片，请问有什么建议或者方案吗？不管是否能够帮助到我都非常感谢您的辛勤付出。

- 问题代码(重要)：
- ```javascript
  buttons: [
          { radius: "50px", background: "#ff7726" },
          { radius: "45px", background: "#ffefc1" },
          // { radius: "45px", background: "#ffefc1" ,pointer:true},
          {
            fonts: [{ text: "", top: "-20px", fontColor: "#FFFFFF" }],
            imgs: [{ src: "~@/src/assets/lottery/pointer.png", top: "-75" }],
          },
        ],
```
<!-- 看到下面的三个小点了吗, 那个叫做代码块, 总有人把代码放在外面... 我都无语了 -->
```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
这样不行, 你最好用`require()`, 比如: `{ src: require('./imgs/1.png') }`

**Comment by onepisYa** [comment]
> 这样不行, 你最好用`require()`, 比如: `{ src: require('./imgs/1.png') }`

非常感谢您的耐心解答， 此方案可行。给您比个 小心心！！

**Comment by buuing** [comment]
没事
