### ISSUE TITLE
[question] 九宫格未中奖设置

### ISSUE THREAD

**Issue by TinsFox** [buuing/lucky-canvas#247]
- 你当前是什么框架(必填)：react

- 你使用的是哪个包(必填)：    "@lucky-canvas/react": "^0.1.5"

在九宫格的情况下，设置了奖品里面是没有未中奖的，如果要stop提示用户未中奖的时候要怎么做呢？stop之后宫格上还是会有某一个宫格会有激活状态的？
需求是调用stop方法，把抽奖暂停，并且宫格里面的奖品格子没有激活显示，或者是让激活状态回到中间的抽奖按钮格子

**Comment by TinsFox** [comment]
[demo](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlFQAZXAShwofAKYB3KGPwoAwgEM%2BENXQB0SggHFmIABQByAMSpM4lGYA0UAN5UuXObDYALAFxQzAEwADEEsAB4Orm5eMmAA5l5sfoEh4ZFuUABGGDz4dH4A2lEZTlAsaiDgfHHJAIyhEY6ZavhxjDxYfCDJFgAcAGwAnDgAZmpmUAC%2B9sVupeWVYNV1DQ5ZLXhtHV09MoMyvSMyE9OzALozGSzMAF4y%2BVBFGVylYX5BjijvjiP8bA8FUpsGRhJL%2BIJrNg8FjJAIAVgApCczlNLs9Xn5ap9vlBfnx-oUgSCwWZapDobDEcjUbMXlA3lAAtioB9cX8AUTQbDyTD-PCkVMUadns56X4mVAvlAsWz8RyoMCuf4AMw8ykCyZCtElMWM5kSvEEx6ckkAFjVfKpgppIox0v1P3ZhIVxOScItgStmpt6N1rKlBqdxpdSrM-Q9-Opwt9DP9mMdcudipJAHYI16tedtVksGwoQJCbTdTKpVii81Wu1Ot1-BYUyNBnCQGTs1xDfLk8lAAD6gGnNdMas6zTXZkAyMZYDBsADKbBQGBkfhcIormyrO1rmV6ODhIwCZiH2cEakYYJGnRwbDA-BMAEpnEXSKQoL3ABx2gHgjIuiWw6FgYNQoW8HyfQBxBUAPujAFLjQBj5UAELdAHfowAhG0AfATADK9QB6M1qOgizoGQ2AAFTAJAZA6NgTFvSQiHvEUuEfKBAB0FQAja3fIsuC-ZQdEEaETCCG8i2maUQm4g9Zhkdczz4C8rz4ExrjAO471KGj30AZb9AH1zQAzyMAReUoBEkAoEAPbVAGAYos1HnE9zEAWwNABzVQBaOUANU1kigABqMpbhkHR2wKIIzh0ZMeIySYokmHiyAYZh2GoIA) 在这demo下，一个奖品都没中的话，stop()方法怎么调用，或者是其他的配置呢

**Comment by buuing** [comment]
`init()`可以重置抽奖, 取消当前中奖标记
