### ISSUE TITLE
如何设置奖品的位置？

### ISSUE THREAD

**Issue by beifang721** [buuing/lucky-canvas#248]
react：
我的第一个奖品如何设置才能在最上方

**Comment by beifang721** [comment]
@buuing

**Comment by buuing** [comment]
偏移角度, 你没设置偏移角度

**Comment by beifang721** [comment]
问题解决了，但是onStart为什么触发不了？log不执行   @buuing 
![image](https://user-images.githubusercontent.com/19699178/159877699-efaacf3d-2de1-4e33-a09a-ae00fd5f635d.png)

**Comment by beifang721** [comment]
底部这个b白色变是什么原因？谢谢 大佬还请指点 @buuing @qingtiantongxie 
![image](https://user-images.githubusercontent.com/19699178/159878999-41e51154-f9fc-4ae6-8818-da9a70df99ab.png)

**Comment by buuing** [comment]
这个你得加我一下微信, 我需要看看dom的位置, 感觉这个白色像是你的背景图片

**Comment by buuing** [comment]
ldq404

**Comment by buuing** [comment]
排查完毕, 1按钮没设置半径, 2背景图片不是矩形
