### ISSUE TITLE
九宫格 开始按钮图片使用动态gif。 显示出来不会动，部分手机end 函数调用失败，没有效果

### ISSUE THREAD

**Issue by lkd3063601** [buuing/lucky-canvas#250]
[九宫格.zip](https://github.com/buuing/lucky-canvas/files/8385244/default.zip)

- 你当前是什么框架(必填)：
 普通html页面

- 你使用的是哪个包(必填)：
1.7.20

- 你当前插件的版本(必填)：
1.7.20

- 当前环境是小程序还是浏览器(选填)：
浏览器(

- 详细描述你的bug：
九宫格 开始按钮图片使用动态gif 显示出来不会动，另外部分手机end 函数调用失败，没有效果

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
微信`ldq404`

**Comment by buuing** [comment]
gif你需要在外面用img标签引入, 然后定位到想要的位置上, 具体请参考基础示例中的 [用dom做为按钮]

**Comment by lkd3063601** [comment]
好的 多谢

**Comment by buuing** [comment]
end回调失败的情况, 我这边无法复现, 所以没办法修复

该加的polyfill我都加了, 我不可能闭着眼改bug

你可以在自己算好时间, 在开始的时候加一个定时器, 然后手动模拟一个end回调

因为 `加速时间 | 匀速时间 | 减速时间` 都是可以设置到固定的毫秒值

**Comment by buuing** [comment]
我看你不愿意加我微信, 那就算了, 还想着能协助我修复一下bug

**Comment by lkd3063601** [comment]
不是不愿意 刚去改代码了 抱歉啊

**Comment by buuing** [comment]
`ldq404`

**Comment by lkd3063601** [comment]
辛苦大佬 已解决

**Comment by buuing** [comment]
![image](https://user-images.githubusercontent.com/36689704/160968500-ede409b5-b65b-405b-b069-343b6f6c9080.png)

**Comment by buuing** [comment]
没事, 修复好就ok

根据反馈, 这位使用者在end回调里加了一个`setTimeout`回调就好了
