### ISSUE TITLE
微信小程序老虎机奖品图片过多时显示不出来

### ISSUE THREAD

**Issue by YoooooO-o** [buuing/lucky-canvas#251]
- 你当前是什么框架(必填)：uniapp 

- 你使用的是哪个包(必填)：uniapp插件—HM-slotMachine 老虎机抽奖模板

- 你当前插件的版本(必填)：v0.0.10.0

- 当前环境是小程序还是浏览器(选填)：小程序

- 详细描述你的bug：奖品图片过多时，canvas宽度或高度超过了4096，小程序会报错
```MiniProgramError"The width 5190 has exceeded the limit 4096."String```

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
你这个到底是放了多少, 设计图我瞅瞅, 不可能有这么多吧

**Comment by YoooooO-o** [comment]
红框圈出来的是用的这个插件，基本超过25个奖品就报错了，开发者工具中有的机型不报错，但是真机基本都报错了。
![1648823016(1)](https://user-images.githubusercontent.com/42170761/161282885-11a508a6-ae9d-4599-8233-c9c961328f06.png)

**Comment by buuing** [comment]
哦, 我知道了, 你用的是老虎机是吧

**Comment by YoooooO-o** [comment]
是的

**Comment by buuing** [comment]
你这个奖品太多了, 为啥会这么多? 都是不重复的吗

**Comment by YoooooO-o** [comment]
好的！

**Comment by buuing** [comment]
排查完毕, 小程序的 canvas 有最大限制, 无法放置大量图片

可以尽可能的减小老虎机的尺寸, 或改为多列插槽
