### ISSUE TITLE
prizes的imgs的宽高都为 100%时，borderRadius失效，显示为直角

### ISSUE THREAD

**Issue by pingping2116** [buuing/lucky-canvas#254]
- 你当前是什么框架(必填)："react": "^16.8.6"

- 你使用的是哪个包(必填)："@lucky-canvas/react": "^0.1.7",

- 你当前插件的版本(必填)："0.1.7",

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：prizes的imgs的宽高都为 100%时，borderRadius失效

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
const size8Px = '8px'
giftList.push({
			borderRadius: size8Px,
			x: giftOrder[index].x,
			y: giftOrder[index].y,
			imgs: [{ width: '100%', height: '100%', src: pictureUrl }, { width: '100%', height: '100%', src: pictureUrl, activeSrc: Image }],
		});
setPrizes(() => giftList);


					<LuckyGrid width={`${luckyGridWidth}px`} height={`${luckyGridWidth}px`} ref={myLucky} blocks={blocks} prizes={prizes} onStart={() => { handleStart() }} onEnd={handleEnd} buttons={buttons} defaultStyle={defaultStyle} defaultConfig={defaultConfig} activeStyle={activeStyle}></LuckyGrid>

// 代码结束
```

**Comment by buuing** [comment]
`borderRadius`只对背景生效, 图片圆角的话需要单独用其他api进行裁剪

**Comment by pingping2116** [comment]
好的 感谢回复

**Comment by buuing** [comment]
没事, 晚点我补充一个图片裁剪圆角的示例

**Comment by pingping2116** [comment]
我还有个问题，就是使用图片是不是也不支持shadow呀？

**Comment by pingping2116** [comment]
不好意思，我shadow设置的有问题，又试了一下，图片是支持shadow 的，只是不支持rgb格式的颜色，只能用十六进制的。打扰了，最后再次感谢！

**Comment by buuing** [comment]
图片还能设置shadow? 你贴一下代码, 我瞅瞅你咋设置的

**Comment by pingping2116** [comment]
图片设置 shadow 的代码
https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlBbMAXgFMAkkgDmUOFADeVLlzqMcALigByABZs2LOptKkcIPgDoAVnRDiMkRlb7i2pGXtIAjLFjA%2BGXNLcnEkHlIRMAkrFiCdABoVVQB3WDY9bR0AVgAGAFIklK42HhZsgCYcopSAXxTeASEcRwxpOQVlVSh1LV0DIxMzC2s7BycIFzcPL19-QODRsIjzNrQADjy4hOSe9JBM7IBGPMLinr1xMC82E7PargaUgEgmwSgAQxw2SHEAZTYKAw4nkSioLxePm%2BeBkjB4WD4IGyAGJPp9KpV0cVIXQ9J8QDxUtk8lAclBjlAUeINgBOHwAFgAZsUIQ03vwPg4mZ8sBg2IDgaCuhCoTC4Qikaj0ZjsclcfjCcTdKTyZTqXTGSz5Q0uI1OUJUAAZXAEMFuVJQE34FAAYU%2BfAgnzoVmtBAA4swQAAKHQo1CYU0oJLg-YZLK6SpnFgADwuqiuNwMVWjcb2qh8GB4%2BBMUAA2iVVIphATwEF7rGQ9D8BLEcjdCimU3mzooHV0z1iyxS4sK2moNXYfC66jmy22x2oABdSfRCS5gs9LjFmPaPKJKAoNcbsCyBetDDtWQbudSWQzvEEomaHQANig99vpJRlQAzG-xOJW%2B3C8uoKuKQ3LcoHXGA920PMDyPGQTzEM8ZCnCdfyUf9tEqIDtzAmR9zaDpYJieDEJ-JcUIA9DN20Y4d3A-MoLw4Q4I6IjJz-MiMKgcjd2wiC6OPBiCKYpCSJXSj2M4mjINwvjT0E4ilxEkCxOo7jaKkmD%2BIkWSWNIzDgKorCcMPeiZPPITVBnQtuV5flBRBTQrL5AUgRBeoAEpaFIBhmHYaggA




<div id="my-lucky"></div>

<script>
  const prizeImg = {
    src: 'https://cdn.jsdelivr.net/gh/buuing/cdn/demo/prize.png',
    width: '50%',
    top: '25%'
  }
  const cellImg = {
    src: 'https://cdn.jsdelivr.net/gh/buuing/cdn/demo/cell-80.png',
    width: '100%',
    height: '100%'
  }

  	const activeStyle = {
		background: '#aa22aa',
		shadow: '0 5 1 #e89b4f',

	}
	const defaultStyle = {
		background: '#aa22aa',
		shadow: '0 5 1 #e89b4f',
	}
  
  const myLucky = new LuckyCanvas.LuckyGrid('#my-lucky', {
    width: '200px',
    height: '200px',
    blocks: [
      { padding: '10px', background: '#ffffff' },
      { padding: '10px', background: '#ffffff' },
    ],
    prizes: [
      { x: 0, y: 0, imgs: [cellImg, prizeImg],shadow:'6 6 60 #2323ee' },
      { x: 1, y: 0, imgs: [cellImg, prizeImg] },
      { x: 2, y: 0, imgs: [cellImg, prizeImg] },
      { x: 2, y: 1, imgs: [cellImg, prizeImg] },
      { x: 2, y: 2, imgs: [cellImg, prizeImg] },
      { x: 1, y: 2, imgs: [cellImg, prizeImg] },
      { x: 0, y: 2, imgs: [cellImg, prizeImg] },
      { x: 0, y: 1, imgs: [cellImg, prizeImg] },
    ],
    defaultStyle:defaultStyle
  })
</script>

**Comment by ZhanghaoH** [comment]
官网上找到的都是直接图片圆角了 @buuing ，这种控制圆角用哪个api

**Comment by xwLyc** [comment]
> 没事, 晚点我补充一个图片裁剪圆角的示例

这个api支持了吗，我是在小程序里面使用的。
修改源码可以实现图片圆角效果，但是我不知道怎么发布到小程序里使用。。

**Comment by buuing** [comment]
思路是用canvas裁剪圆角, 搭配imgs里有个formatter属性

**Comment by buuing** [comment]
```js
{
  width: '80%',
  top: '20%',
  src: 'https://xxx/WechatIMG2720230111102023.jpeg',
  formatter(img) {
    const { width, height } = img
    const canvas = Taro.createOffscreenCanvas({ // 这里最好不要用离屏canvas
      type: '2d',
      width,
      height,
    })
    const ctx = canvas.getContext('2d') as any
    roundRectByArc(ctx, 0, 0, width, height, 50)
    ctx.clip()
    ctx.drawImage(img, 0, 0, width, height)
    return canvas
  },
},
```
参考一下这个人的用法, 但小程序里是否兼容这个方式, 我不确定, 没在小程序里试过

**Comment by xwLyc** [comment]
> ```js
> {
>   width: '80%',
>   top: '20%',
>   src: 'https://xxx/WechatIMG2720230111102023.jpeg',
>   formatter(img) {
>     const { width, height } = img
>     const canvas = Taro.createOffscreenCanvas({
>       type: '2d',
>       width,
>       height,
>     })
>     const ctx = canvas.getContext('2d') as any
>     roundRectByArc(ctx, 0, 0, width, height, 50)
>     ctx.clip()
>     ctx.drawImage(img, 0, 0, width, height)
>     return canvas
>   },
> },
> ```
> 
> 参考一下这个人的用法, 但小程序里是否兼容这个方式, 我不确定, 没在小程序里试过

哇哦，感谢，我先试试

**Comment by xwLyc** [comment]
> ```js
> {
>   width: '80%',
>   top: '20%',
>   src: 'https://xxx/WechatIMG2720230111102023.jpeg',
>   formatter(img) {
>     const { width, height } = img
>     const canvas = wx.createOffscreenCanvas({ // 这里最好不要用离屏canvas
>       type: '2d',
>       width,
>       height,
>     })
>     const ctx = canvas.getContext('2d') as any
>     ctx.drawImage(img, 0, 0, width, height)
>     return canvas
>   },
> },
> ```

删除其他代码，直接drawImage，在原生小程序里面使用报错，

我使用 `npm install @lucky-canvas/mini@latest`安装的， 看了下 `@lucky-canvas/mini ` 版本号为 `0.0.7`，依赖的`"lucky-canvas": "~1.7.24"`。

<img width="665" alt="image" src="https://github.com/buuing/lucky-canvas/assets/14286912/c13d34a0-9a9a-4622-9ad6-d611b5e8e8df">

<img width="570" alt="image" src="https://github.com/buuing/lucky-canvas/assets/14286912/3525e7c1-217a-4879-a8b8-107f7066a388">

**Comment by xwLyc** [comment]
昨晚做梦都梦见这个问题了 😂

有没有计划新增一个imgs.borderRaduis 属性支持呢？

**Comment by buuing** [comment]
哦, 我知道了, 小程序的img里好像没有宽高

**Comment by buuing** [comment]
你打印一下, 看看width和height 有值吗

**Comment by xwLyc** [comment]
> 你打印一下, 看看width和height 有值吗

有的，我后面还用了，img.load结束后再进行drawImg 也无效。
后来看你源码里面其实也是在img load 结束之后再调用的 formatter函数。

刚开了一上午会，两列奖项，每列奖池列表还不一样，还要给选中的图片加描边，还想做选中放大动效😂😂😂
