### ISSUE TITLE
官网不知道什么原因，加载完之后，官网首页滚动不了，而且会导致浏览器卡死

### ISSUE THREAD

**Issue by cMing1997** [buuing/lucky-canvas#255]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：浏览器，版本： 97.0.4692.71（正式版本） （32 位）

- 详细描述你的bug：
  - 官网不知道什么原因，加载完之后，官网首页滚动不了，而且会导致浏览器卡死
  - 当页面还没完全加载完的时候，可以滚动，当页面加载完之后，滚动就会卡住

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
.....电脑啥配置的, 有没有可能是电脑太卡了

**Comment by cMing1997** [comment]
> .....电脑啥配置的, 有没有可能是电脑太卡了
```
设备名称	WIN-NU4HQGF7B4G
设备全名	WIN-NU4HQGF7B4G.sino.sz
处理器	Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz   3.60 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
设备 ID	FF9FEE42-3270-49B3-B88D-C435D8F98942
产品 ID	00331-10000-00001-AA696
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
```
关键是就 浏览器卡死了，我操作其他的软件都可以，而且 在没操作官网首页的时候，浏览器也是很流畅的，而且只有首页滚动的时候会这样

**Comment by buuing** [comment]
不知道为啥...猜不出来
