### ISSUE TITLE
点击抽奖动态改变抽奖按钮文本

### ISSUE THREAD

**Issue by niubg** [buuing/lucky-canvas#257]
场景：抽奖按钮上添加文字抽奖次数，点击抽奖成功后实时更新抽奖按钮中的抽奖次数的文本
![image](https://user-images.githubusercontent.com/50099479/163908045-54a806c2-9a72-4d37-85fb-2e9d17f9d87d.png)

**Comment by buuing** [comment]
现在忙, 下午给你发个小demo

**Comment by niubg** [comment]
> 现在忙, 下午给你发个小demo

记得抽时间发个demo哟

**Comment by buuing** [comment]
[点这个链接](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFBgKZtQA7LEihwoAZipccAewF1%2BqADK4CowTwDuUFfhQBhAIYCIhugDpdBAOoALHjwwAKAOQBiVJlUoXAGigA3lJcUJqwbLYAXFAuAEwADPEsAB5%2BwVz2YADmtmzRcYkpaSFQAEYYMvh00QDaAVAshiDgAln5AIxJqf6lhvhZjDJYAiD5bgAcAGwAnDgAZoYuUAC%2BALq%2B6Q3MAF481VA1m1z1vf2Dw6MxbjzTPONzPH5Qc3Js%2B3VQbDzJeTHxS2sVhsSscyn08AMhiMxqVxjgAKxzWJPF4CN61epfH4dAGrIFHQJgs5Qy7uG53B4o17vTHfX5xXH4kGE04Q87Qq6whFIqlommfOn5cSM5bAkEncGQi5jcn3R7%2BVHog607ExAAsIrFJQlxOlnLhiORCupGIFqpc8M1m3Wm1KWDYbDk7wJQWZXEYTTAWH2LjV8QApE9WVKOe4prMFsU3SwZGA0TxGNE2IwsDwtSDFfysb8AAaADfjAJZKABIAkIkMtAITWOf8jpY%2BTQnSKK1WBNF1vTCkMjF%2Bc2GODYYDkTgAlIECWA5lAnGWoMAxPFR4w%2BFhGAIoIZeN3XBXAA6mgFg5QDNsS5hwSy2g0ATlN5zHaHU6avFVuZMw%2Bn9n1Pni6XhJWcwTSKQUCAAD6gDTmoAHHaAPBGl4oFYKDmCwGCGCgI7-oBgDiCoAfdGAKXGgDHyoAIW6AO-RgBCNoA%2BAmAGV6gD0Zu0dAEnQfAACpgEgPBDGwTgAPqiEQY5ulAAFQIAOgqAEbWkEElwV56OYCgyCwTgLq2-idIkJ4lG2JQ8ByvYCP2g4CE4LA7Dwo71PxkHCYAb6aAGeRgCLygSG4JmxLiALYGgA5qoAtHKAGqa%2BRQAA1FsYC7M%2B1KvuY2YqSEyzBMsJ5kAwzDsNQQA)

**Comment by niubg** [comment]
> [点这个链接](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFBgKZtQA7LEihwoAZipccAewF1%2BqADK4CowTwDuUFfhQBhAIYCIhugDpdBAOoALHjwwAKAOQBiVJlUoXAGigA3lJcUJqwbLYAXFAuAEwADPEsAB5%2BwVz2YADmtmzRcYkpaSFQAEYYMvh00QDaAVAshiDgAln5AIxJqf6lhvhZjDJYAiD5bgAcAGwAnDgAZoYuUAC%2BALq%2B6Q3MAF481VA1m1z1vf2Dw6MxbjzTPONzPH5Qc3Js%2B3VQbDzJeTHxS2sVhsSscyn08AMhiMxqVxjgAKxzWJPF4CN61epfH4dAGrIFHQJgs5Qy7uG53B4o17vTHfX5xXH4kGE04Q87Qq6whFIqlommfOn5cSM5bAkEncGQi5jcn3R7%2BVHog607ExAAsIrFJQlxOlnLhiORCupGIFqpc8M1m3Wm1KWDYbDk7wJQWZXEYTTAWH2LjV8QApE9WVKOe4prMFsU3SwZGA0TxGNE2IwsDwtSDFfysb8AAaADfjAJZKABIAkIkMtAITWOf8jpY%2BTQnSKK1WBNF1vTCkMjF%2Bc2GODYYDkTgAlIECWA5lAnGWoMAxPFR4w%2BFhGAIoIZeN3XBXAA6mgFg5QDNsS5hwSy2g0ATlN5zHaHU6avFVuZMw%2Bn9n1Pni6XhJWcwTSKQUCAAD6gDTmoAHHaAPBGl4oFYKDmCwGCGCgI7-oBgDiCoAfdGAKXGgDHyoAIW6AO-RgBCNoA%2BAmAGV6gD0Zu0dAEnQfAACpgEgPBDGwTgAPqiEQY5ulAAFQIAOgqAEbWkEElwV56OYCgyCwTgLq2-idIkJ4lG2JQ8ByvYCP2g4CE4LA7Dwo71PxkHCYAb6aAGeRgCLygSG4JmxLiALYGgA5qoAtHKAGqa%2BRQAA1FsYC7M%2B1KvuY2YqSEyzBMsJ5kAwzDsNQQA)

转盘初始化的角度可以控制吗？
场景：想让指针默认指向某一个奖品

**Comment by buuing** [comment]
文档上有

**Comment by niubg** [comment]
> 



> 文档上有

嗯 看到了。感谢
