### ISSUE TITLE
vue2引用无法运行，出现Object(...) is not a function

### ISSUE THREAD

**Issue by Alan-222** [buuing/lucky-canvas#258]
- 你当前是什么框架(必填)：vue: 2.6.11

- 你使用的是哪个包(必填)："@lucky-canvas/vue": "^0.1.9",

- 你当前插件的版本(必填)： "@vue/cli-service": "~4.5.15",

- 详细描述你的bug：
- 
![image](https://user-images.githubusercontent.com/66811041/164170832-0b21f2fd-8d24-47ef-869c-682fb76ad989.png)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
<template>
  <LuckyWheel
    ref="myLucky"
    width="300px"
    height="300px"
    :prizes="prizes"
    :blocks="blocks"
    :buttons="buttons"
    @start="startCallback"
    @end="endCallback"
  />
</template>

<script>
export default {
data () {
    return {
      blocks: [{ padding: '13px', background: '#617df2' }],
      prizes: [
        { fonts: [{ text: '0', top: '10%' }], background: '#e9e8fe' },
        { fonts: [{ text: '1', top: '10%' }], background: '#b8c5f2' },
        { fonts: [{ text: '2', top: '10%' }], background: '#e9e8fe' },
        { fonts: [{ text: '3', top: '10%' }], background: '#b8c5f2' },
        { fonts: [{ text: '4', top: '10%' }], background: '#e9e8fe' },
        { fonts: [{ text: '5', top: '10%' }], background: '#b8c5f2' },
      ],
      buttons: [
        { radius: '50px', background: '#617df2' },
        { radius: '45px', background: '#afc8ff' },
        {
          radius: '40px', background: '#869cfa',
          pointer: true,
          fonts: [{ text: '开始\n抽奖', top: '-20px' }]
        },
      ],
    }
},
methods: {
    // 点击抽奖按钮会触发star回调
    startCallback () {
      // 调用抽奖组件的play方法开始游戏
      this.$refs.myLucky.play()
      // 模拟调用接口异步抽奖
      setTimeout(() => {
        // 假设后端返回的中奖索引是0
        const index = 0
        // 调用stop停止旋转并传递中奖索引
        this.$refs.myLucky.stop(index)
      }, 3000)
    },
    // 抽奖结束会触发end回调
    endCallback (prize) {
      console.log(prize)
    },
}
}
</script>

<style>

</style>
// 代码结束
```

**Comment by buuing** [comment]
复现个小demo压缩发给我

**Comment by Alan-222** [comment]
[vue-test.zip](https://github.com/buuing/lucky-canvas/files/8519221/vue-test.zip)

**Comment by buuing** [comment]
我这里启动你的demo可以运行, 无报错?

**Comment by buuing** [comment]
node什么版本, 检查`npm install`是否有报错

**Comment by Alan-222** [comment]
![image](https://user-images.githubusercontent.com/66811041/164173246-a61a5d12-e6df-49af-9abc-d016968f19ae.png)
我也不清楚  编译时就有warn了  完整引入项目都启动不了。。。

**Comment by buuing** [comment]
你这个包都没安上

```
npm i vue-demi @vue/composition-api
```

**Comment by Alan-222** [comment]
node的版本是14.17.0

**Comment by buuing** [comment]
算了, 你把 node_modules 删掉, 重新 `npm install` 得了

**Comment by Alan-222** [comment]
额  我有删掉 node_modules 再安装这样试过挺多次了  还是不行 。我就是按官网的执行`npm install @lucky-canvas/vue@latest`安装的，我按你npm i vue-demi @vue/composition-api这个安装了 在启动还是编译报错

**Comment by buuing** [comment]
你那个依赖安装有问题, 用这种方式吧: https://100px.net/usage/js.html

**Comment by Alan-222** [comment]
好吧 谢谢

**Comment by buuing** [comment]
我这边 node 版本是 12.22.7

你要是想用 vue组件版本的话, 可以试试这个版本, 然后把 `node_modules` 和 `package-lock.json` 都删掉, 再重新 `npm install` 尝试

**Comment by buuing** [comment]
因为你发送的demo, 我在本地是可正常启动的, 那个`vue-demi`的警告明显是没安装上, 他有个钩子必须得和`lucky-canvas`一起触发

**Comment by buuing** [comment]
如果你不想尝试了, 就直接按 js 的方式使用就可以

**Comment by Alan-222** [comment]
好的 我试试

**Comment by buuing** [comment]
还是不行是嘛

**Comment by Alan-222** [comment]
降低node版本就可以了 我降低到了你那个版本12.22.7

**Comment by Alan-222** [comment]
谢谢！

**Comment by buuing** [comment]
ok

**Comment by DuYr** [comment]
为什么我这边打包会出错啊，vue3说是
![1655818109501](https://user-images.githubusercontent.com/45650358/174811291-a3de944b-9f20-4ab0-afc8-98a0721a9702.png)

**Comment by buuing** [comment]
你这个看着像是 ts 的报错? 你怎么用的

**Comment by DuYr** [comment]
> 你看这个好像是 ts 的报错？你怎么用的

现在解决了

**Comment by buuing** [comment]
@DuYr 哪里的问题, 组件内部需要调整吗

**Comment by DuYr** [comment]
> @DuYr 哪里的问题, 组件内部需要调整吗

我在tsconfig里面少加个东西  "skipLibCheck": true

**Comment by DuYr** [comment]
话说你们这个prizes执行的顺序会比vue的生命周期优先吗

**Comment by buuing** [comment]
prizes执行? 你是说绘制吗, 绘制最起码要等到`mounted`拿到canvas的dom才能绘制

**Comment by DuYr** [comment]
![image](https://user-images.githubusercontent.com/45650358/174936653-2e9e9465-4645-4a2f-a646-1d5705c54cff.png)
我这么写的，总是undefined

**Comment by buuing** [comment]
你的代码有问题? 接口回调是异步的, 你在哪里去赋值的?????

**Comment by DuYr** [comment]
.then()里面

**Comment by DuYr** [comment]
然后把值再给这个抽奖的参数

**Comment by DuYr** [comment]
![image](https://user-images.githubusercontent.com/45650358/174937239-2c9e8df9-d8a2-4801-950f-b0ec833fe8b9.png)

**Comment by buuing** [comment]
你就不能把初始化`prizes`数据也放在then里面?

**Comment by DuYr** [comment]
额 抱歉，敲麻痹了。

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下

**Comment by DuYr** [comment]
okok
