### ISSUE TITLE
原生微信小程序方式创建大转盘抽奖，动画结束后会有闪动

### ISSUE THREAD

**Issue by wuhaoworld** [buuing/lucky-canvas#260]
- 你当前是什么框架(必填)：原生微信小程序
- 你使用的是哪个包(必填)：npm 方式最新版
- 当前环境是小程序还是浏览器(选填)：小程序
- 详细描述你的bug：原生微信小程序方式创建大转盘，真机测试动画结束后会有闪动，像是重新渲染 ，iOS、Android 最新版微信均可重现
- 问题代码：官方示例代码即可重现，具体见：https://100px.net/usage/wx.html

**Comment by buuing** [comment]
真机调试是嘛, 上传体验版试试, 另外说一下基础库版本!!!

**Comment by wuhaoworld** [comment]
> 真机调试是嘛, 上传体验版试试, 另外说一下基础库版本!!!

npm 安装最新版 "@lucky-canvas/mini": "^0.0.6"

**Comment by wuhaoworld** [comment]
> 真机调试是嘛, 上传体验版试试, 另外说一下基础库版本!!!

上传体验版后问题不再复现，感谢解答

**Comment by buuing** [comment]
用着顺手点个star支持一下
