### ISSUE TITLE
在Vue中，老虎机模式横向无法使用，点击开始依旧是竖向转动，

### ISSUE THREAD

**Issue by xiaolele188** [buuing/lucky-canvas#261]
<div id="app">
  
  <div class="da">
    <slot-machine
      ref="myLucky"
      width="500px"
      height="80px"
      :prizes="prizes"
      :blocks="blocks"
      :slots="slots"
      :defaultConfig="defaultConfig"
    >
    </slot-machine>
    <div class="dsaddsa">
      <button @click="startCallback">按钮</button>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>

<script src="https://cdn.jsdelivr.net/combine/npm/@vue/composition-api@1.2.4,npm/vue-demi@0.11.4/lib/index.iife.min.js,npm/@lucky-canvas/vue@0.1.8"></script>
<script>
  new Vue({
    el: '#app',
    data() {
      return {
        blocks: [
          { padding: '10px', background: '#869cfa' },
          { padding: '10px', background: '#e9e8fe' }
        ],
        slots: [{ order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], direction: 1 }],
        prizes: [
          { fonts: [{ text: '0', top: '15%' }] },
          { fonts: [{ text: '1', top: '15%' }] },
          { fonts: [{ text: '2', top: '15%' }] },
          { fonts: [{ text: '3', top: '15%' }] },
          { fonts: [{ text: '4', top: '15%' }] },
          { fonts: [{ text: '5', top: '15%' }] },
          { fonts: [{ text: '6', top: '15%' }] },
          { fonts: [{ text: '7', top: '15%' }] },
          { fonts: [{ text: '8', top: '15%' }] },
          { fonts: [{ text: '9', top: '15%' }] }
        ],
        defaultConfig: {
          mode: 'horizontal',
          rowSpacing: '10px',
          colSpacing: '10px'
        }
      }
    },
    methods: {
      // 点击抽奖按钮会触发star回调
      startCallback() {
        // 调用抽奖组件的play方法开始游戏
        this.$refs.myLucky.play()
        // 模拟调用接口异步抽奖
        setTimeout(() => {
          // 假设后端返回的中奖索引是0
          const index = 3
          // 调用stop停止旋转并传递中奖索引
          this.$refs.myLucky.stop(index)
        }, 3000)
      },
      // 抽奖结束会触发end回调
      endCallback(prize) {
        console.log(prize)
      }
    }
  })
</script>

![image](https://user-images.githubusercontent.com/69999001/166400774-a6d647fc-1b3b-4fb6-9671-ebc2b209e088.png)

**Comment by buuing** [comment]
代码写的不对, [参考这个示例](https://100px.net/playground.html?code=DwEwlgbgBGILwCICGAHFCB8AoKVgGcAbAewBcBaAWyQGMALMAOwFMdcoAnZgM0UoE8AMgFcaAa34I2uAO6xSdRACYALAAYUADynsodZmADmdUogCMADg3bpUAFwAjEuPyInxFzvZ2UHMAC9mVwRfAKCvXDsiMmDo0nwI%2BxAeJGFCChpiRm4jRGTuVPSAYSycwy8AemxgCvAIavwaPxRSKHwOGkQTUhR8OwqKmhBGADoAK3xkwkgOEZZSCsYUSgqIYWYAASURgDYRsxVasHwFteZxhIwaxubSBqawFraOrtIevoGh0YmpmbnmBaZSgOJjMRbLCobM6DYiUFDEfBgUhgLLkVBgDZmEbbFQAGiWKzO5GSlAxan2WMO0wcFSYyU0IzAYG451J33w%2BIhG0Iogk5BoSEYECQ%2BFW6w25KxFkw1weLXut2wuGFHCgEEoUDgUBYMigADV1gAKADetmYhDsUAA5ABiVAoK242wgJCkJCW026XDuFyWgDatl0xqgKCQIHAjEMlqtZmsjqgDloYkMHGIwkYIGjNosOwAnDQClaoABfJ1e9jB0PhphR62xrTxxPiFNpjNZ5i55gWFlF0uBqAAXTLXrifSgAfLuGD%2BBQzGYmagAFYS8Py9PZ-PLWYV-2p20Nwvl33y0P%2B6FAmOJ5PPZPvUmW%2BmF7am4u547d%2BwHMQOMkOAAlMMwGEMcYzjVcvWPa8PzvZtU0fLMXzfcDyy-H9mH-QDgOjetNHfW9IN0U9y3yQpSBKbIjA9D9KGIZJozob8AiyN1CDwydUxkABlUMaBrbCwI-TJCG42g%2BLrON%2B2LWwCKgGj01IecoENABKKAb10BRjhGAASLhuHwEYBBEcR%2BBGFBCCQfgVOkthi2UrBZUVIA)
