### ISSUE TITLE
转盘内加载奖品图片时，时常会加载不出来

### ISSUE THREAD

**Issue by jpx5028254** [buuing/lucky-canvas#264]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
#177

**Comment by buuing** [comment]
补充一下提问模板, 我啥信息都没有, 怎么排查问题?

**Comment by jpx5028254** [comment]
prizes字段里imgs字段传入的图片url时，会时常出现canvas绘制不出来图片，然后奖品区域空白

**Comment by jpx5028254** [comment]
图片是http是url地址的远程图片不是本地图片

**Comment by jpx5028254** [comment]
图片是http的远程图片不是本地的，本地图片没问题，远程有问题

**Comment by buuing** [comment]
你先把提问模板给补充好

**Comment by jpx5028254** [comment]
1、vue3
2、我直接引用了lucky-canvas插件，自己用vue3写法封装了
3、版本：lucky-canvas^1.7.20
4、是以h5页面的形式被小程序和app嵌入的
5、传入http远程图片时，会出现canvas加载不出来，奖品区域空白的情况，不是每次是间隔出现

**Comment by buuing** [comment]
试一下我封装的组件`@lucky-canvas/vue`也会出现这个问题吗

**Comment by jpx5028254** [comment]
你那个用插件转的vue3写法，之前有个实时修改参数不同步刷新的问题，然后我就直接引用插件封装了

**Comment by buuing** [comment]
你看看 https://100px.net/playground.html 上面能否复现这个问题

**Comment by jpx5028254** [comment]
这个是没图的prizes啊

**Comment by buuing** [comment]
你自己把数据结构写一下不就得了? 我还把饭喂到你嘴里?

**Comment by jpx5028254** [comment]
方便加个微信吗，我稍微展示一下代码给你看下

**Comment by buuing** [comment]
ldq404
