### ISSUE TITLE
大佬，可以指点一下迷津吗？跑马灯初次加载的时候，canvas里面没有东西，刷新就有了。

### ISSUE THREAD

**Issue by GongZhuoYing** [buuing/lucky-canvas#266]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
把提问模板补充上 #177
