### ISSUE TITLE
小程序设置背景图片无效

### ISSUE THREAD

**Issue by zhiouv** [buuing/lucky-canvas#267]
微信小程序原生设置背景图片无效
1，原生微信小程序
2，"@lucky-canvas/mini": "^0.0.6"
3，使用的是十二宫格 
4，设置了背景图片，但是页面上不出来。图片路径没问题，奖品的图片都可以访问
```
 blocks: [{
      padding: '10px',
      imgs: [{ src: '/images/turntable/a.png', width: '100%', height: '100%' }],
      background: '#ac0d27',
      borderRadius: '20rpx',
    }]
```

**Comment by buuing** [comment]
把提问模板补充上 #177

**Comment by CNMrZhouGit** [comment]
> 把提问模板补充上 #177

已补充

**Comment by buuing** [comment]
啥时候安装的, 你看一下node_modules里的依赖是什么版本 => `lucky-canvas`

**Comment by buuing** [comment]
之前的版本里, 九宫格抽奖的blocks确实没加imgs选项, 但是最新版已经补充了背景图, 如果你的依赖是`lucky-canvas@1.7.23`, 那就要排除你的图片是不是太大了, 才导致绘制失败?

**Comment by CNMrZhouGit** [comment]
> 之前的版本里, 九宫格抽奖的blocks确实没加imgs选项, 但是最新版已经补充了背景图, 如果你的依赖是`lucky-canvas@1.7.23`, 那就要排除你的图片是不是太大了, 才导致绘制失败?
![1653008570(1)](https://user-images.githubusercontent.com/34094293/169428591-3edd9ccc-1528-41dc-b1ab-78b49a41c2a0.png)

**Comment by buuing** [comment]
不是这个, 我都说了, 你去node_modules里看, `lucky-canvas`是`@lucky-canvas/mini`的依赖包!!!

**Comment by zhiouv** [comment]
> 不是这个, 我都说了, 你去node_modules里看, `lucky-canvas`是`@lucky-canvas/mini`的依赖包!!!

是1.7.23版本的，图片大小限制是多少？这个图片是40多k
![1653014327(1)](https://user-images.githubusercontent.com/34094293/169437794-cc0de3c2-439c-4ae2-8265-53d2df35e81e.png)

我写了一个微信小程序的代码片段，帮我看一下，谢谢。
https://developers.weixin.qq.com/s/eZfVnom972zM

**Comment by buuing** [comment]
好, 晚上我看看

**Comment by buuing** [comment]
我知道咋回事了, 我的锅, 微信小程序这个包, 我忘记更新了

最新版`@lucky-canvas/mini@0.0.7`已修复该问题

**Comment by hehefamous** [comment]
> 我知道咋回事了, 我的锅, 微信小程序这个包, 我忘记更新了
> 
> 最新版`@lucky-canvas/mini@0.0.7`已修复该问题

嗯，现在可以，谢谢。

**Comment by zhiouv** [comment]
> 我知道咋回事了, 我的锅, 微信小程序这个包, 我忘记更新了
> 
> 最新版`@lucky-canvas/mini@0.0.7`已修复该问题


现在背景图是可以了，又出现新的问题了，无法play了

![1653270019(1)](https://user-images.githubusercontent.com/34094293/169727661-d9556368-8938-4bcd-92f8-a9c95ff7f4db.png)
![1653270027(1)](https://user-images.githubusercontent.com/34094293/169727673-9d13575d-af48-47ff-b804-3970c209deef.png)

**Comment by buuing** [comment]
`child.$lucky` => `child.lucky`
