### ISSUE TITLE
老虎机控件在uniapp微信小程序上无法显示奖品图片等（模拟器上正常）

### ISSUE THREAD

**Issue by houpai** [buuing/lucky-canvas#268]
- 你当前是什么框架(必填)：uniapp

- 你使用的是哪个包(必填)：老虎机

- 你当前插件的版本(必填)：0.0.10

- 当前环境是小程序还是浏览器(选填)：小程序

- 详细描述你的bug：老虎机在小程序模拟器上正常显示 但是在真机上貌似是canvas没有获取到

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
微信小程序? 你说的真机是真机调试还是发布的体验版

**Comment by buuing** [comment]
vue2还是vue3, 多来点信息!

**Comment by houpai** [comment]
> 真机调试还是发布的体验版都不行 vue2

**Comment by buuing** [comment]
你复现个小demo压缩成zip发给我, 我看看你怎么用的

**Comment by houpai** [comment]
> vue2还是vue3, 多来点信息!
![image](https://user-images.githubusercontent.com/35244664/169514388-6d11cbb0-ed86-456c-87d5-71cbe1600b6b.png)
逻辑正常 但就是奖品图片什么的显示不了

**Comment by houpai** [comment]
组件文件&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] 老虎机控件在uniapp微信小程序上无法显示奖品图片等（模拟器上正常） (Issue #268)





 
你复现个小demo压缩成zip发给我, 我看看你怎么用的

**Comment by houpai** [comment]
老哥别嫌麻烦哈 我没时间起个项目压缩给你了 把组件文件发你了&nbsp; 你把地址发我 我给你弄杯咖啡喝把 略表谢意




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] 老虎机控件在uniapp微信小程序上无法显示奖品图片等（模拟器上正常） (Issue #268)





 
你复现个小demo压缩成zip发给我, 我看看你怎么用的

**Comment by houpai** [comment]
老哥 有头绪了嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] 老虎机控件在uniapp微信小程序上无法显示奖品图片等（模拟器上正常） (Issue #268)





 
你复现个小demo压缩成zip发给我, 我看看你怎么用的

**Comment by buuing** [comment]
???你也没发我啊

**Comment by houpai** [comment]
> ???你也没发我啊

···

<template>
  <view class="machinepopup popup" v-if="active">
    <div class="pre-load-img"></div>
    
    <div class="slotMachine-srceen">
      <u-notice-bar
          mode="horizontal"
          :list="['⚡ 幸运大抽奖 ⚡']"
          :font-size="'40'"
          color="#FFDD6E"
          type="none"
          :padding="'0rpx 20rpx'"
          :volume-icon="false"
          class="screen-notice"
      />
    </div>
    <div class="slotMachine-bg-box">
      <div class="slotMachine-bg-center">
        <SlotMachine
            class="SlotMachine"
            ref="SlotMachine"
            :width="width"
            :height="height"
            :defaultConfig="defaultConfig"
            :defaultStyle="defaultStyle"
            :blocks="blocks"
            :prizes="prizes"
            :slots="slots"
            @end="endCallBack"
        />
      </div>
      
      <div class="play-btn" :class="[{'active': isActive}]" @click.stop="play"></div>
    </div>
    
    <div class="slotMachine-num">
       剩余抽奖次数 {{ lucky.action_nums || 0 }} 次
    </div>

    <img
        class="close"
        :src="`${baseOss}/image/close.png`"
        @click="close(false)"
    />
  </view>
</template>

<script>

import { baseOss } from "@/config";
import Common from "@/utils/common";
// eslint-disable-next-line import/extensions
import SlotMachine from "@lucky-canvas/uni/slot-machine";

export default {
  name: "slot-machine-popup",
  // eslint-disable-next-line vue/no-unused-components
  components: { SlotMachine },
  data() {
    return {
      listData: ['幸运大抽奖'],
      classOption: {
        limitMoveNum: 2,
        direction: 3,
      },
      baseOss,
      active: false, // 是否展示弹窗
      callback: null, // 回调函数
      lucky: null,
      award: null,
      lieutenantGeneral: false,
      activityId: null,
      didNotWin: false,
      width: '240px',
      height: '120px',
      blocks: [
        {
          borderRadius: '8px',
          padding: '10px',
          background: '#A82A2E',
        },
        { padding: '10px', background: '#741A32', borderRadius: '8px' },
      ],
      slots: [
        { order: [0, 1, 2], direction: 1 },
        { order: [1, 2, 0], direction: -1 },
        { order: [2, 1, 0], direction: 1 },
      ],
      prizes: [
        {
          imgs: [
            {
              width: '100%',
              height: '100%',
              top: 0,
              src: 'https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_scroll_center.png',
            },
            {
              width: '60%',
              top: '20%',
              src: `${baseOss}/image/circular_icon3.png`,
            },
          ],
        },
        {
          imgs: [
            {
              width: '100%',
              height: '100%',
              src: 'https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_scroll_center.png',
            },
            {
              width: '60%',
              top: '20%',
              src: 'https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine-prize1.png',
            },
          ],
        },
        {
          imgs: [
            {
              width: '100%',
              height: '100%',
              src: 'https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_scroll_center.png',
            },
            {
              width: '60%',
              top: '20%',
              src: 'https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine-prize2.png',
            },
          ],
        },
      ],
      defaultStyle: {
        // background: "#fff",
      },
      defaultConfig: {
        rowSpacing: '10px',
        colSpacing: '10px',
      },
      isActive: false,
      canClick: true,
    };
  },
  methods: {
    /** 打开 */
    open(data, id) {
      if (!data || !id) return false;
      this.lucky = data;
      this.activityId = id;
      return new Promise((resolve) => {
        this.active = true;
        this.callback = resolve;
      });
    },

    /** 关闭 */
    close(back) {
      this.active = false;
      this.$emit('closeDetailFixed');
      this.callback?.(back);
    },

    /** 点击抽奖按钮触发回调 */
    // async startCallBack() {
    //
    // },

    /** 转盘结束回调 */
    endCallBack() {
      this.canClick = true;
      if (JSON.stringify(this.award) !== "{}") {
        this.lieutenantGeneral = true;
        this.close({
          popup: "isPrize",
          award: { ...this.award, activityId: this.activityId },
        });
      } else {
        this.didNotWin = true;
        this.close({ popup: "didNotWin" });
      }
    },
    async play() {
      const data = { award: "", taskShow: false };
      if (this.lucky.action_nums !== 0) {
        const message = await Common.requestSubscribeMessage([
          "YEeZtf7heK8FCSTZqhBdIJKvonbh1PwTXmmbBo7jLrI",
          "A33rIptepqQay30GNZDQo83q8Lm1arvkqMCKl4ERMwE",
        ]);
        if (!message) return false;
        const result = await this.$apis.openTheBox(
          {
            activity_id: this.activityId,
          },
          false,
        );
        this.isActive = true;
        this.canClick = false;
        // 定时器控制按钮点击动画 1s后按钮浮起
        setTimeout(() => {
          this.isActive = false;
        }, 150);
        this.$refs.SlotMachine.play();
        let index;
        // 假设 3 种中奖结果
        const res = [
          [1, 1, 1],
          [0, 0, 0],
          [2, 2, 2],
        ];
        if (JSON.stringify(result.data) !== "{}") {
          this.award = result.data;
          data.award = result.data;
          // eslint-disable-next-line no-bitwise
          index = res[Math.random() * 3 >> 0];
        } else {
          this.award = {};
          index = [1, 2, 3];
        }
        setTimeout(() => {
          this.$refs.SlotMachine.stop(index);
        }, 1500);
      } else {
        this.award = {};
        if (this.lieutenantGeneral || this.didNotWin) return;
        this.close({ popup: "isExhausted" });
      }
    },
  },
};
</script>

<style lang="scss" scoped>
.machinepopup {

  .slotMachine-num {
    position: relative;
    margin-top: -116rpx;
    height: 110rpx;
    width: 70%;
    background-repeat: no-repeat;
    background-size: 100% 100%;
    background-image: url("https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_num.png");
    color: #FDD600;
    font-size: 32rpx;
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: bold;
  }

  .slotMachine-srceen {
    overflow: hidden;
    box-sizing: border-box;
    padding-top: 18rpx;
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
    top: 90rpx;
    background-repeat: no-repeat;
    height: 110rpx;
    width: 54%;
    background-size: 100% 100%;
    background-image: url("https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_screen.png");

  }

  .slotMachine-bg-box {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 90%;
    height: 768rpx;
    background-image: url("https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_bg1.png");
    background-repeat: no-repeat;
    background-size: 100% 100%;

    .slotMachine-bg-center {
      width: 240px;
      height: 120px;
      margin-top: 140rpx;
      border-radius: 8px;
      overflow: hidden;
      background-color: #741A32;
    }

    .play-btn {
      margin-top: 80rpx;
      width: 400rpx;
      height: 140rpx;
      background-repeat: no-repeat;
      background-size: 100% 100%;
      background-image: url("https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_btn.png");
    }

    .play-btn.active {
      background-image: url("https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_btn_active.png");
    }

    .pre-load-img {
      background-image: url("https://wemark.oss-cn-shenzhen.aliyuncs.com/uniapp_activity_planet/image/slotMachine_btn_active.png");
      width: 10rpx;
      height: 10rpx;
      visibility: hidden;
    }
  }
}

.close {
  width: 72rpx;
  height: 72rpx;
  margin-top: 80rpx;
  right: calc(50% - 36rpx);
}
</style>

···

**Comment by houpai** [comment]
> ???你也没发我啊

你给我个邮箱呗 我发你

**Comment by houpai** [comment]
> ???你也没发我啊

发你邮箱了

**Comment by buuing** [comment]
加我微信吧`ldq404`

**Comment by buuing** [comment]
排查完毕, 是**微信小程序把离屏canvas的属性偷偷改了, 导致无法绘制奖品区域

最新版已修复该问题, 保持核心依赖 `lucky-canvas >= 1.7.24` 即可

**Comment by raisezhang** [comment]
好像离屏渲染的会一直会在左上角？

**Comment by buuing** [comment]
@raisezhang 如果你有什么问题的话, 直接去开个issues并填好提问模板

**Comment by raisezhang** [comment]
好  我这就整理
