### ISSUE TITLE
转盘背景不居中的问题

### ISSUE THREAD

**Issue by xinglee23** [buuing/lucky-canvas#269]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/11779203/169644802-0c6c9202-df1d-4cc1-8862-e79040dcff60.png">
转盘在背景里面不居中

你当前是什么框架(必填)：
React

- 你使用的是哪个包(必填)：
 0.1.7

- 你当前插件的版本(必填)：
<img width="487" alt="image" src="https://user-images.githubusercontent.com/11779203/169644905-bfb1c410-31e4-497f-a07d-df0c3cc6c77c.png">

- 当前环境是小程序还是浏览器(选填)：
浏览器

- 详细描述你的bug：
转盘设置背景，但是画出来的转盘在背景中无法居中

- 问题代码(重要)：
demo 地址
https://codesandbox.io/s/proud-violet-yn3x5g

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
他是居中的, 我只能说是你的背景图没有居中, 你这个背景图里的圆心明显靠上........

比如, 你试试这个图片 https://100px.net/assets/img/bg.2daf906c.png 这个才是正确居中的图片

当然了, 你要是不想麻烦 UI 你可以使用 top 属性进行微调, 比如: `top: '1%'`

<img width="381" alt="image" src="https://user-images.githubusercontent.com/36689704/169652940-9c2d41ba-2364-44f1-974a-fea7580f5d98.png">

**Comment by xinglee23** [comment]
> 

收到，非常感谢
