### ISSUE TITLE
小程序老虎机渲染问题，一直在屏幕左上角

### ISSUE THREAD

**Issue by raisezhang** [buuing/lucky-canvas#271]
- 你当前是什么框架(必填)：
原生微信小程序

- 你使用的是哪个包(必填)：
mini

- 你当前插件的版本(必填)：
0.0.7

- 当前环境是小程序还是浏览器(选填)：
小程序

- 详细描述你的bug：
左上角会有离屏渲染的内容

- 问题代码(重要)：
<img width="340" alt="image" src="https://user-images.githubusercontent.com/1481983/169660598-63a7265f-7bbb-42c6-9736-6356b88ae22c.png">

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by raisezhang** [comment]
小程序版本库为 ： 2.24.3

**Comment by buuing** [comment]
好的, 明天我瞅瞅咋回事

**Comment by buuing** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/36689704/169660988-376c773a-9262-4ac9-9034-b0f993f88657.png">

我这里显示没有问题啊

**Comment by buuing** [comment]
哦, 我明白了, 你别用`2.24.3`, 这个版本还在灰度中, 你使用稳定版`2.24.2`

<img width="208" alt="image" src="https://user-images.githubusercontent.com/36689704/169661094-3518aabd-6370-4c10-96e8-25472c9d8a74.png">

**Comment by raisezhang** [comment]
现在已经有线上用户是   2.24.3 了

**Comment by buuing** [comment]
用着顺手可以点个star支持一下

**Comment by buuing** [comment]
你不要管他, 他写的`灰度中`明白吗, 灰度就是还没正式发布的意思

**Comment by raisezhang** [comment]
你的意思是 小程序的 bug 么？

**Comment by buuing** [comment]
是的, 离屏canvas之所以叫做离屏, 就是因为他不会显示出来, 他是一个虚拟的, 所以不需要担心这个问题, 他如果把这个问题带到线上去, 就一定会有无数人喷死他

**Comment by raisezhang** [comment]
ok 多谢~

**Comment by buuing** [comment]
没事哈, 老哥加一下我微信`ldq404`
