### ISSUE TITLE
vue2.0+ts打包报错

### ISSUE THREAD

**Issue by onlySparrow** [buuing/lucky-canvas#272]
- 你当前是什么框架(必填)：vue2.6.14

- 你使用的是哪个包(必填)： "@lucky-canvas/vue": "^0.1.11"

- 你当前插件的版本(必填)： "@lucky-canvas/vue": "^0.1.11",

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug： 执行npm run serve时不报错，npm run build 报错
- 
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/26291459/169931300-d024805f-21ed-4221-a115-342f048f8bc1.png">

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
demo 压缩地址：https://pan.baidu.com/s/1Ejzi6JaRl2JJMxv-AGiU-g      提取码：dc3a
// 代码结束
```

**Comment by buuing** [comment]
排查完毕, vue2+ts 打包时`@vue/composition-api`报错

解决方案: node使用12.22.7, @vue/composition-api降到1.0.0可以正常打包
