### ISSUE TITLE
如何处理没有抽到奖

### ISSUE THREAD

**Issue by nininini-1** [buuing/lucky-canvas#274]
- 你当前是什么框架(必填)：react

- 你使用的是哪个包(必填)： "@lucky-canvas/react": "^0.1.10",

- 你当前插件的版本(必填)： "@lucky-canvas/react": "^0.1.10",

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：如何处理没有抽到奖

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
放置一个名叫谢谢惠顾的奖品

**Comment by nininini-1** [comment]
抽奖按钮能都支持设置 disabled 呢

**Comment by buuing** [comment]
? 没太懂, 什么时候开始游戏你可以用js控制
