### ISSUE TITLE
九宫格背景图能否支持gif图？

### ISSUE THREAD

**Issue by kongta** [buuing/lucky-canvas#276]
- 你当前是什么框架(必填)：
  vue

- 你使用的是哪个包(必填)：
  "@lucky-canvas/vue": "^0.1.11",

- 你使用插件的版本(必填)：
  0.1.11
 
- 当前你使用的是哪个抽奖类型(必填)：
 九宫格

九宫格背景图能否支持gif图？

**Comment by buuing** [comment]
暂时不支持, 但是你可以用img标签引入gif图片, 然后css定位到抽奖组件的下面

**Comment by kongta** [comment]
好的，谢谢

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下
