### ISSUE TITLE
九宫格游戏执行stop后立刻停止转动，并未缓慢停止

### ISSUE THREAD

**Issue by elfman** [buuing/lucky-canvas#277]
- 你当前是什么框架(必填)：uniapp

- 你使用的是哪个包(必填)：@lucky-canvas/uni": "^0.0.10

- 你当前插件的版本(必填)：0.0.10

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
在九宫格游戏里，执行stop方法，转动就立刻停止了，并没有缓慢停下的过程，修改decelerationTime没作用

- 问题代码(重要)：

```
    this.$refs.luckyGrid.play()
    const index = this.lotteryConfig.prizes.findIndex(t => t.id === res.id)
    setTimeout(() => {
      this.$refs.luckyGrid.stop(index)
    }, 3000)
```

**Comment by buuing** [comment]
打印一下index, 因为stop(-1)是立即停止

**Comment by elfman** [comment]
是index = -1的原因，忘了从这方面找原因了。。。
