### ISSUE TITLE
大转盘出现奇怪的形状，不知是哪里配置错了

### ISSUE THREAD

**Issue by elfman** [buuing/lucky-canvas#278]
- 你当前是什么框架(必填)：uniapp

- 你使用的是哪个包(必填)：lucky-canvas/uni

- 你当前插件的版本(必填)：0.0.10

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
- 转盘显示的形状很奇怪，中心点移到左上角了。转到是时候也是左上角部分在转。
- 
![image](https://user-images.githubusercontent.com/948001/172049293-ac8d9dd5-9113-413e-8da2-7cd4482e8c68.png)

- 问题代码(重要)：
<img width="461" alt="image" src="https://user-images.githubusercontent.com/948001/172049307-be5666c4-ce3d-4291-8ae3-33af6d4a9154.png">

![image](https://user-images.githubusercontent.com/948001/172049341-4579d666-8c2f-48b8-b46b-d859748905e3.png)

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by elfman** [comment]
修改node_modules里的lucky-wheel.vue源码，在LuckyWheel的初始化参数里，添加beforeDraw, afterDraw两个回调函数，执行ctx.translate后显示正常了。但这肯定不是长久的解决方法，不知这是bug，还是我哪里配错了？

```Javascript
beforeDraw: function () {
  ctx.translate(Radius, Radius)
},
afterDraw: function () {
  ctx.translate(-Radius, -Radius)
},
```

**Comment by buuing** [comment]
你是uniapp编译的h5?

**Comment by elfman** [comment]
是的

**Comment by buuing** [comment]
修改`ctx.translate`是我以前的方案, 我不知道你从哪看到的, 因为后面我看到编译正常了就删掉了, 建议你检查一下你的hbx版本

**Comment by buuing** [comment]
这个是一个uniapp的渲染bug, 他会在图片onload之后重置圆心

- 具体issues请参考: https://github.com/dcloudio/uni-app/issues/2847

**Comment by buuing** [comment]
麻烦你说一下你现在使用的hbx版本, 以及你更新之后的hbx时候还出现了这个问题

**Comment by elfman** [comment]
```
"@dcloudio/types": "*",
"@dcloudio/uni-automator": "^2.0.0-28620200814003",
"@dcloudio/uni-cli-i18n": "^2.0.0-32920210927002",
"@dcloudio/uni-cli-shared": "^2.0.0-28620200814003",
"@dcloudio/uni-i18n": "^2.0.0-32920210927002",
"@dcloudio/uni-migration": "^2.0.0-28620200814003",
"@dcloudio/uni-template-compiler": "^2.0.0-28620200814003",
"@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-28620200814003",
"@dcloudio/vue-cli-plugin-uni": "^2.0.0-28620200814003",
"@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-28620200814003",
"@dcloudio/webpack-uni-mp-loader": "^2.0.0-28620200814003",
"@dcloudio/webpack-uni-pages-loader": "^2.0.0-28620200814003",
"@vue/cli-plugin-babel": "~4.5.0",
"@vue/cli-service": "~4.5.0",
"babel-plugin-import": "^1.11.0",
"cross-env": "^7.0.2",
"eslint": "^7.7.0",
"eslint-plugin-vue": "^6.2.2",
"jest": "^25.4.0",
"less-loader": "^6.2.0",
"mini-types": "*",
"miniprogram-api-typings": "*",
"postcss-comment": "^2.0.0",
"sass-resources-loader": "^2.1.0",
"vma-assist": "^1.0.52",
"vue-template-compiler": "^2.6.11"
```

**Comment by elfman** [comment]
我是用命令行编译的，并没有使用HBuilderX

**Comment by buuing** [comment]
哦, 那你用cli重新创建一个项目试试, 因为uniapp已经修复过这个问题了

如果新项目可以, 建议你按照新项目的依赖版本去升级一下旧项目

**Comment by elfman** [comment]
把uniapp所有相关的包都升级到 `2.0.1-34720220422002` 后就正常了

**Comment by buuing** [comment]
ok, 新版是好的
