### ISSUE TITLE
插件在微信小程序2.24.4不显示奖品内容

### ISSUE THREAD

**Issue by 17608494941** [buuing/lucky-canvas#279]
- 你当前是什么框架(必填)：原生微信小程序

- 你使用的是哪个包(必填)： "@lucky-canvas/mini": "0.0.6",

- 你当前插件的版本(必填)： "@lucky-canvas/mini": "0.0.6",

- 当前环境是小程序还是浏览器(选填)：微信小程序

- 详细描述你的bug：微信开发工具选择基础库为2.24.4

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by 17608494941** [comment]
bug

**Comment by buuing** [comment]
有代码片段没

**Comment by buuing** [comment]
`0.0.6`好像确实有个bug

- `npm i @lucky-canvas/mini@0.0.7`

**Comment by buuing** [comment]
奇怪, 你是怎么安装0.0.6的, 因为我是半个月前更新的0.0.7
