### ISSUE TITLE
官网的老虎机抽奖无法停止

### ISSUE THREAD

**Issue by teaim** [buuing/lucky-canvas#280]
官网100px的老虎机抽奖无法停止

看了下是this.$refs.myLucky.$lucky.stop(A)这行报错

对着github上面的源码没找到对应位置

是不是官网的代码好久没更新了

**Comment by buuing** [comment]
给个链接

**Comment by buuing** [comment]
你改成这样试试`this.$refs.myLucky.stop(A)`

**Comment by buuing** [comment]
我今晚更新一下, 因为完整案例很久没动了, 基础示例都没问题的
