### ISSUE TITLE
官网以及项目的cdn地址无法使用

### ISSUE THREAD

**Issue by XiaoRIGE** [buuing/lucky-canvas#281]
cdn.jsdelivr.net下域名下的资源访问不到，demo无法加载出来

**Comment by buuing** [comment]
还真是, jsdelivr感觉最近很不稳定, 今晚我替换成unpkg吧, 感谢反馈

**Comment by XiaoRIGE** [comment]
我看到文档里的cdn地址已经改了，demo里还没有。
![image](https://user-images.githubusercontent.com/33147011/172754320-a2bfa1a9-1221-439f-b26b-7e0c018d71a3.png)
例如这些cdn地址应该改为什么呢

**Comment by XiaoRIGE** [comment]
哈喽 ，完整实例的代码可以开放出来吗？希望接葫芦画瓢，完成对应的需求，感激开源大法

**Comment by buuing** [comment]
我刚看了一下, 官网的cdn没问题, 是正确的的
