### ISSUE TITLE
奖品图片以及抽奖按钮图片已经固定，如何通过组件修改圆角borderRadius

### ISSUE THREAD

**Issue by ZhanghaoH** [buuing/lucky-canvas#285]
- 你当前是什么框架(必填)：react

- 你使用的是哪个包(必填)：@lucky-canvas/react

- 你当前插件的版本(必填)：0.1.10

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：奖品和抽奖按钮为图片时，层级最高，设置的 容器圆角被图片覆盖

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
晚上我给你写个demo

**Comment by ZhanghaoH** [comment]
太感谢了 周六正赶工中

**Comment by buuing** [comment]
- **[这个是切割圆角的示例](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlBbMAXgFMAkkgDmUOFADeVLlzqMcALigByABZs2LOptKk6egIYgeAdwB04jOKTicIPvd5JSlli1InF3E%2BNlIrJAAjLEYZcUZ7AE4cADMAdkiABkSARjQAVnzxRLQcnOK0S0S0gDY0NJSAFhBMrLTxcRSa%2BxY%2BGR0AGhVVW1g2PW0dfMyAUkHhrhSeRiRLQ3ioAAowWQBKJQXVRnE2GL4oABlcAgBhSz4ISzovLDYAJR4sPhBt2QGoaa7Q4AX2GoK4vAEQlQV3wKHkUD44lsl2uKDuDye9lhBAA6noOhhNjoAMSoTBowYHVRQUYgcaTADMmUyLAAHvMaQSwDIDEyWezOapIhgePgTFAANqKYTWcB9SY5Vkc-6RSz4GSMT7fSYkgAcNWSKUsOigwIAukMaSIwBIJZLDlwZTsZPabRJpDJLVA1RqtV8QLriuI9SlxKbgVaaUooEtQvaZWxxGy2IqI97fXhNdrA7oSZE9Th8ikAEwRqM0mVxtgJqBJlOTMtmjPqrP%2BnV54Oh8NmiuqKv8GvaaV15Op3SM9Oq1vZgO6gtF0vlx0x6u1%2BvjnSNKc%2Bmft3Okrth5fR1eD9djyb5HeZ2cd0kL4tNyOHS1goFkBjMdjUIA)**

用着顺手别忘点个star支持一下

**Comment by ZhanghaoH** [comment]
> * **[这个是切割圆角的示例](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlBbMAXgFMAkkgDmUOFADeVLlzqMcALigByABZs2LOptKk6egIYgeAdwB04jOKTicIPvd5JSlli1InF3E%2BNlIrJAAjLEYZcUZ7AE4cADMAdkiABkSARjQAVnzxRLQcnOK0S0S0gDY0NJSAFhBMrLTxcRSa%2BxY%2BGR0AGhVVW1g2PW0dfMyAUkHhrhSeRiRLQ3ioAAowWQBKJQXVRnE2GL4oABlcAgBhSz4ISzovLDYAJR4sPhBt2QGoaa7Q4AX2GoK4vAEQlQV3wKHkUD44lsl2uKDuDye9lhBAA6noOhhNjoAMSoTBowYHVRQUYgcaTADMmUyLAAHvMaQSwDIDEyWezOapIhgePgTFAANqKYTWcB9SY5Vkc-6RSz4GSMT7fSYkgAcNWSKUsOigwIAukMaSIwBIJZLDlwZTsZPabRJpDJLVA1RqtV8QLriuI9SlxKbgVaaUooEtQvaZWxxGy2IqI97fXhNdrA7oSZE9Th8ikAEwRqM0mVxtgJqBJlOTMtmjPqrP%2BnV54Oh8NmiuqKv8GvaaV15Op3SM9Oq1vZgO6gtF0vlx0x6u1%2BvjnSNKc%2Bmft3Okrth5fR1eD9djyb5HeZ2cd0kL4tNyOHS1goFkBjMdjUIA)**
> 
> 用着顺手别忘点个star支持一下

必须得，已star，这个是已有属性 没暴露啊

**Comment by ZhanghaoH** [comment]
弱弱的问一下，react里import的  LuckyCanvas怎么拿...

**Comment by buuing** [comment]
```
import { cutRound } from 'lucky-canvas'
import { LuckyWheel } from '@lucky-canvas/react'
```

**Comment by ZhanghaoH** [comment]
好的 谢谢了 看来npm包我也需要恶补

**Comment by buuing** [comment]
这个属性目前还不支持小程序, 所以还没加到文档上

**Comment by xiaoxin0309** [comment]
> ```
> import { cutRound } from 'lucky-canvas'
> import { LuckyWheel } from '@lucky-canvas/react'
> ```

为什么安装了没有生效

**Comment by xiaoxin0309** [comment]
> 



> ```
> import { cutRound } from 'lucky-canvas'
> import { LuckyWheel } from '@lucky-canvas/react'
> ```

为什么安装了，没有生效
