### ISSUE TITLE
老虎机抽奖出现跨域错误

### ISSUE THREAD

**Issue by elfman** [buuing/lucky-canvas#286]
- 你当前是什么框架(必填)：uniapp

- 你使用的是哪个包(必填)：uni

- 你当前插件的版本(必填)：0.0.10

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：把老虎机抽奖嵌入到pc端的iframe页面里渲染，出现错误，Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
转盘和九宫格也是这样引用的，没有出现这个问题

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
晚上我看看

**Comment by buuing** [comment]
没时间啊, 你加我微信吧: `ldq404`

**Comment by MyIsGodOfCode** [comment]
我也是同样的问题，请问您解决了吗

**Comment by MyIsGodOfCode** [comment]
> 晚上我看看

请问您解决了吗

**Comment by buuing** [comment]
> 请问您解决了吗

这浓郁的命令式语气?

**Comment by MyIsGodOfCode** [comment]
> 



> > 请问您解决了吗
> 
> 这浓郁的命令式语气?

没有啊，我也遇到了相同的问题，相同的错误，所以想问一下您有没有解决方法，没有恶意。

**Comment by buuing** [comment]
ok, 你发两遍容易让人误会

**Comment by MyIsGodOfCode** [comment]
> ok, 你发两遍容易让人误会

这个错误我从网上查，大部分说是跨域问题，但是后端却说是配置好了跨域。我也是没有什么方向，所以想请教下

**Comment by MyIsGodOfCode** [comment]
> ok, 你发两遍容易让人误会

但是确实，我谷歌配置下跨域的话就能加载出图片不报错，不配置的就会报这个错误，加载不出奖品图片

**Comment by buuing** [comment]
好的我看一下, 之前忙忘了

**Comment by MyIsGodOfCode** [comment]
> 好的我看一下, 之前忙忘了

谢谢，期待您的回复，如果需要代码，我明天去公司拿到贴一下

**Comment by buuing** [comment]
我想起来了, 我本地复现不了这个问题, 你可以发我一个问题demo吗

**Comment by buuing** [comment]
我的微信: `ldq404`, 方便你联系到我

**Comment by MyIsGodOfCode** [comment]
加您了，今天可能不能去公司了，明年我去给您发一个demo

**Comment by buuing** [comment]
最新版已修复该问题

**Comment by MyIsGodOfCode** [comment]
> 最新版已修复该问题

感谢作者，辛苦
