### ISSUE TITLE
12121212

### ISSUE THREAD

**Issue by mrtychen** [buuing/lucky-canvas#289]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：lucky-canvas/vue

- 你当前插件的版本(必填)：0.1.11

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
121212121

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
32232322
// 代码结束
```

**Comment by mrtychen** [comment]
用的是老虎机

**Comment by buuing** [comment]
自己去看文档

**Comment by buuing** [comment]
我给你们提供插件, 提供文档, 然后你不看文档跑过来问我属性怎么调, 你是程序员吗? 你拿着这份工资, 然后想让我给你把活干了? 你想的挺美啊
