### ISSUE TITLE
uniapp编译h5【偶现】lucky-wheel显示错误

### ISSUE THREAD

**Issue by Yukiball** [buuing/lucky-canvas#291]
大大我又来了

- 你当前是什么框架(必填)：uniapp

- 你使用的是哪个包(必填)：@lucky-canvas/uni

- 你当前插件的版本(必填)：@lucky-canvas/uni:0.0.10   "lucky-canvas":1.7.22

- 当前环境是小程序还是浏览器(选填)：h5

- 详细描述你的bug：点开始抽奖之后左上角在转。
<img width="273" alt="image" src="https://user-images.githubusercontent.com/29480878/174999170-2806016b-1bb3-4909-8687-919906a7fad4.png">
有的时候正常，有的时候是这样

- 问题代码(重要)：用https://100px.net/usage/uni-app.html这里面的demo跑的h5,完全复制粘贴没有改代码

**Comment by Yukiball** [comment]
@dcloudio/uni-h5：2.0.0-31920210709003 版本

**Comment by buuing** [comment]
- [#278 大转盘出现奇怪的形状，不知是哪里配置错了](https://github.com/buuing/lucky-canvas/issues/278)
