### ISSUE TITLE
一个小需求：转盘文字展示方式

### ISSUE THREAD

**Issue by peirm** [buuing/lucky-canvas#292]
![1655973694809](https://user-images.githubusercontent.com/30795612/175256866-d5ea6d7d-285e-4da0-9ed9-fb2fac101094.jpg)

一个小需求：转盘文字展示方式

1. 抽奖文字的展示方式可以是纵向展示，且超出时淡出（我遇到的需求，觉得这种方式也挺好的）
2. css画的文字渐出，在safari浏览器上面展示会有问题(网上查了很多资料，都没有得到解决，所以决定来学习使用canvas是否能解决这个bug)，如下图：
<img width="335" alt="Snipaste_2022-06-23_16-49-48" src="https://user-images.githubusercontent.com/30795612/175258443-25d8de7a-5f56-4701-9ded-32f0c0c8c581.png">

**Comment by buuing** [comment]
1. 文字的纵向展示目前没有很好的思路来配置
2. 文字淡入淡出这个效果有点多余, 几乎没人有这种需求, canvas可以做, 你弄一个矩形, 矩形从左到右的rgba中的a从0递增, 然后把这个矩形盖在文字上就能实现这个效果了
