### ISSUE TITLE
vue框架下，我看vue版本是通过window区分的，使用服务端渲染会找不到window.Vue

### ISSUE THREAD

**Issue by TristZz** [buuing/lucky-canvas#293]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
服务端渲染我还真没尝试过, 如果你这里始终无法渲染, 可以使用源码包

- [在 JavaScript 中使用](https://100px.net/usage/js.html)
