### ISSUE TITLE
uniapp运行微信小程序到PC端奖品图片无法显示

### ISSUE THREAD

**Issue by skytkcn** [buuing/lucky-canvas#294]
- 你当前是什么框架(必填)：uniapp

- 你使用的是哪个包(必填)：uniapp

- 你当前插件的版本(必填)：0.0.10

- 当前环境是小程序还是浏览器(选填)：uni-app 微信小程序

- 详细描述你的bug：
- 奖品图片在微信小程序PC端无法显示，其他端都正常

![image](https://user-images.githubusercontent.com/39985229/176342130-8ae6eb7a-9478-44d9-9e7b-0ee6473f699e.png)

- 问题代码(重要)：
```
<view class="set-bg">
	<image class="set-bg-img" src="http://qiniuyun.hxxd.tv/image/2022/04/02/2.gif" mode=""></image>
	<LuckyWheel ref="myLucky" width="635rpx" height="635rpx" :blocks="blocks" :prizes="prizes"
	:buttons="buttons" :defaultStyle="defaultStyle" @start="startCallBack" @end="endCallBack" />
</view>
```
```
getActivityDetail() {
	let data = {
		activity_id: this.id
	}
	this.sign = this.$GlobalApi.sign(data)
	this.prizes = []
	this.$api.getActivityInfo(data, true, res => {
		if (res.activity_prize.length > 0) {
		   for (var i = 0; i < res.activity_prize.length; i++) {
			this.prizes.push({
				fonts: [{
				  text: res.activity_prize[i].name,
				  top: '10%',
				  fontColor: '#FF302D',
				  fontSize: '30rpx'
				}],
				imgs: [{
					src: res.activity_prize[i].img,
					width: '40%',
					top: '40%'
					}],
				background: '#FFFCEF'
				})
			}
		}
	}, err => {})
}
```

**Comment by buuing** [comment]
你这个背景图是用的img标签, 奖品图片打印一下我看看长什么样

你配置域名白名单了吗!

**Comment by skytkcn** [comment]
奖品图片也是与背景图片同样使用的七牛云的图片链接，除了pc端以外其他端显示都正常





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 中午11:18
***@***.***&gt;;
抄送:&nbsp;"A cloudy ***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] uniapp运行微信小程序到PC端奖品图片无法显示 (Issue #294)





 
你这个背景图是用的img标签, 奖品图片打印一下我看看长什么样
 
你配置域名白名单了吗!

**Comment by buuing** [comment]
有没有可能是PC端的canvas渲染有bug, 微信干这事也不是一两次了

**Comment by buuing** [comment]
不对??? 你这是 http ?? 不应该是 https 吗

**Comment by skytkcn** [comment]
![image](https://user-images.githubusercontent.com/39985229/176352704-a5c9e2c3-9450-4342-b5cc-520a47e63739.png)
即使写死https也没用，仅仅在pc没用

**Comment by buuing** [comment]
- https://vkceyugu.cdn.bspapp.com/VKCEYUGU-f184e7c3-1912-41b2-b81f-435d1b37c7b4/5a7f902b-21a7-4822-884f-925219eacc4b.png

首先我想确认两点

1. 这个地址是你随便复制的链接, 还是你们正在使用的域名
2. PC端小程序有报错显示吗

**Comment by buuing** [comment]
我看了一下微信小程序的文档社区, 感觉PC端canvas渲染图片的功能, 他们目前还没支持

**Comment by skytkcn** [comment]
貌似是不支持canvas 2d渲染，但是echarts有解决方案，不知道是咋整的

**Comment by buuing** [comment]
你的奖品文字不是渲染了吗, 奖品文字也是canvas绘制的一部分, 我看只是图片没显示

**Comment by skytkcn** [comment]
不知道啥原因，我看dom节点是有的

![image](https://user-images.githubusercontent.com/39985229/176362319-6a84d996-93e8-4011-8672-46d6bf85d5e4.png)

**Comment by skytkcn** [comment]
![image](https://user-images.githubusercontent.com/39985229/176362204-af6fe104-803f-4a82-af40-8eb94793986e.png)

**Comment by buuing** [comment]
那个没用, 是我用来触发onload回调的

**Comment by skytkcn** [comment]
那就不知道啥原因了，如果不支持canvas type 2d渲染按理来说整个canvas都是无法显示的

**Comment by buuing** [comment]
图片实际的渲染是在canvas里面

**Comment by buuing** [comment]
去年PC端整个canvas都是无法显示的, 今年我看可以显示绘制内容了, 可能图片尚未支持

**Comment by buuing** [comment]
等一下, 你的PC是发的体验版看的, 还是开发者工具预览看的

**Comment by skytkcn** [comment]
我PC用开发工具和线上版本都是一样的

**Comment by buuing** [comment]
`开发者工具预览`和`发布体验版`是不一样的, 你发布体验版看一下, 估计整个canvas都不显示

**Comment by skytkcn** [comment]
我这儿看着都是一样的显示文字不显示图片

**Comment by buuing** [comment]
那就没办法了, 我看你在文档社区提了个问题, 看看官方回复吧

**Comment by skytkcn** [comment]
我即使用https写死都不行





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 中午11:23
***@***.***&gt;;
抄送:&nbsp;"A cloudy ***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] uniapp运行微信小程序到PC端奖品图片无法显示 (Issue #294)





 
不对??? 你这是 http ?? 不应该是 https 吗

**Comment by buuing** [comment]
还是pc端吗
