### ISSUE TITLE
修改样式不方便

### ISSUE THREAD

**Issue by liuyang920** [buuing/lucky-canvas#296]
- 你当前是什么框架(必填)：
vue

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：
0.1.11

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：
不是代码的问题，样式问题自由修改度太低了，九宫格抽奖想要改每个格子的样式，添加border和内边框之类的无法做到

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
你可以列举想要修改的样式, 后续 2.0 的版本会考虑这些内容

**Comment by liuyang920** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/68577177/177506273-ac3e771c-85ac-4525-a31d-a5a18dda54e9.png">
这样的边框我看到完整的实例里面有，但是没有代码展示，在文档中没有看到能够设置转动时边框样式的
<img width="263" alt="image" src="https://user-images.githubusercontent.com/68577177/177506631-91657543-c421-41dd-8cac-0f42a89bfa84.png">

**Comment by buuing** [comment]
哦, 你是PC端还是小程序啊

**Comment by liuyang920** [comment]
app内的H5页面使用

**Comment by buuing** [comment]
他这个边框是利用图片实现的..............不过代码应该也可以画出来, 我晚上看看

**Comment by liuyang920** [comment]
好的 感谢

**Comment by buuing** [comment]
我做了一个临时方案, 你可以先拿去用, 后续 2.0 重构的时候会考虑增加更多的css样式

- [示例地址](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlBABTAGYBDLBjYBlRjihwoAchAS2EgFxgkEgOYjSLPvoDcAIwl0RANgAsAGgBKABgwBxAPIARDAAsAQQBFQIAhQIBJQJjYwIAFUiSUAAkAVgiAUTjAgBkc8JjsmMiw5xiARhUqLl4BIQkcNkgReUVlNQ1tXQMjE3MrGwcXd28-INCI6ILE5PSsnPyciMDiqLKYgCZq2v5BKDEeRkMQSKR9JSgAbxquKDoFLWFxKRk2x1uuRuaIVseob4td6fA5HPRsNgiRhQAAUun0AEpriCuGAxLD4QA6B7tODKUSSaRyBRIxgiNhYRh8GDnFFQDDkqAAbUcUFZAHdWf4ALqXNj%2BMB0TGGNgeEQ8JDk5g4eKMHgsKFsFAwpmuVlqqAVVkVbkIul1fY4CR8CDWS4gHg4LCSvhsTFMEQaESZBk2tgwlRGk3WFR6u53L2moXs2D8y7s-XGoOY-wiMD6fxCZT%2BfV7IRNAAel0D1mF5IAwvxIRn3SpNiBfan6tcoCxmAAvESBMkSVkgOusgD6BNeciVDKgAF8%2BQK6FX9lcoBYjqJGM4JOAsHQntDh8puy8ibJ%2ByJx0Is8oUJcNfFIpcALIafyY0-6tgZzEWET6MB8eJXmF%2B-3ce%2BYsRgDAMG3FABw6ABiVxIJ2b9M0xDBXxEAB1UN-EuNI7wfeC%2BBEAApHhX0uFQ5SwPgKwwuCEPzCQWEI4jSOg-1YKfF83w-L9GN-JAeF%2BAAVHgYUYdV2IDX8JAUGEswAaigdkoDQKBBKgI9pMUxS0FPKBSCgTYhPIsScAkqBpNk%2BTFOUqBUNM1lFJPM8tM2YTalE8SpIU1lzMstyvI0%2BzWVPRyfwffTDJU9yjK8xTT1ZdS7O0gLYJwDAeBsd9%2BU-cjBDlPARHS78FPJSlqVyXACCo70hStNhnB4EiQBhHM6Gs4TB1uFrdmrVBivwI9lGw2SutKqNcwGlAPGYOqVDA1BMBKlAVFZG5-RDEB%2BSeFQAGZIJYDN5pBWN40TNbNtcbbdv9OV2WXbSPkYngMCunSQQsJL8Cupk6UnFgF3AUw1oqE6dtZKx8H0OiQDWsCAA5bAAThwSQVCHG7v0%2B77X30P6AfmqdGjwUGatIiGRBhkRIbEEREcHZGuG5anawbEQ3o%2BqAMyeDUUDZ1l4Tew5jhEU5zl5KnmdZzV3M5ml9B5o4TjOfQhbprhJ1FrUlKeVXuaeJledlwWkZFiWObFyXpb5gX5f1-1aZBQFfmAhknkW79gbxsGIYsSGcDSMRthBYX-R7Lcd0dulDltWQwEbI6scV0FbULJLGAhsQxFsCxbCqWOw7YRC4wTNgngAdkg2OXfx2r3c973ff9f27kDmRCz4f8MeRPK6AVfn1b95HBy-JIoEAAH1AGnNW5OtmzEWAwCRlT1MgGGYdhqCAA)

这样做比较复杂, 我其实更推荐你把边框拆成一个 active 图片
