### ISSUE TITLE
老虎机的奖品超过10个在苹果手机下报错

### ISSUE THREAD

**Issue by zhou94** [buuing/lucky-canvas#297]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
应该是超出了canvas画布的大小限制, 别放那么多奖品

**Comment by zhou94** [comment]
@buuing 是指离屏绘制的canvas的大小吗

**Comment by buuing** [comment]
是的, 一般别最多就放五六个, 你放太多, 用户也是无感知的, 因为转的快图片都是模糊的

**Comment by zhou94** [comment]
> 是的, 一般别最多就放五六个, 你放太多, 用户也是无感知的, 因为转的快图片都是模糊的

有没有较好的解决办法，目前确实会配到十个，离屏的canvas等比缩小 这个方案可行吗

**Comment by buuing** [comment]
截图我看看你的设计稿

**Comment by zhou94** [comment]
> 

![image](https://user-images.githubusercontent.com/30468240/177713478-71d8c210-a61e-471e-b5e0-3a8d44ad8d8f.png)
跟demo基本差不多 所以再想离屏绘制的时候判断下 控制canvas大小等比小于3000，在drawImage的时候再去把离屏canvas当前帧还原回来，不知道可不可行

**Comment by zhou94** [comment]
> 截图我看看你的设计稿

大佬帮忙看看下面这种方案可行吗

**Comment by buuing** [comment]
没看懂, 你自己试试吧

**Comment by buuing** [comment]
如果你无法说服产品的话, 你可以试试说服UI, 改成5列插槽试试 (插槽列数越多, 我使用的canvas就越小)

不过我还是建议不要放太多奖品, 华而不实的需求, 3列插槽的奖品控制在10个以内

**Comment by zhou94** [comment]
> Owner

看了下源码 主要还是ios下面 canvas大小限制比较小，最后折中处理了下，外部动态根据设备类型和奖品数动态传入dpr

**Comment by buuing** [comment]
好主意, 我记得dpr好像是可以传入的, 然后我会优先使用传入的dpr, 虽然这样会损失一些清晰度, 但也是一种解决方案

**Comment by buuing** [comment]
我做了个传入dpr的demo, 供后面的人使用, [点击链接可跳转](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlFQAZXAShwofAKYB3KGPwoAwgEM%2BENXQB0AZQw82AWTU4AFmFkAKAN5UuXCgFEMMpDL5sAXFBA8cLA8vHQBHLBlGFD0ZNxw2HkZrAHIAYlRMcRRkgEoAGgdHEBZGXwBGKFJSKEBN%2BMAZxMAseUB-eUAKV0ACeUBTRUAQt2LGQoBfPKh7Ryg5WDZzX2SAJgAWAAYWAA9kgtHzGTAAc3MfKGSygA4l1fXHACNDfDpfAG1C0dsoFjUQcD5t6bLTtagLsx4baMHhYPggaapI4ANgAnDgAGZqZJQQaPRzPV7vKxfA4-FZ-AH4YGg8GQmSwmRHBEyFFo0YAXXOXDohjYtygD1GXGeiRAkXuCyGZSGMyZfjAjBk8TA-HKqOZGKgfIFnJFUBmQwW4vAUplcqgaAq9O5vMY-NKnM1UCFUDKOsl0rYsr48pNXCZ6JKYAAXjIOVzTVAEfx2fdnmwZMt9skFn8EixvgBWACkdIZCvRPODoYDEajMbK8Z4ibxqfTme5wxzXjzUEj0emM2LpcO5dRGfdUE9o35SKwGDYejYKDcvhG3KJQJBYIhB1SRKTMlpiq4Ia8el9MmmAGYZgTVzW2CoeIZLWkd5fkuiu321APj-wETtx1moCC5HpXjgcU3fofeAwL8zF-PFfhvRVPBAKBrG9P0cmGN8qm4fg6FPGQdEMbZYOYeCbwGHJaFIBhmHYaggA)
