### ISSUE TITLE
打包时，访问报错： 无法获取CanvasContext2D 

### ISSUE THREAD

**Issue by ranxiaoli** [buuing/lucky-canvas#298]
- 你当前是什么框架(必填)：
vue2

- 你使用的是哪个包(必填)：
- lucky-canvas/vue@latest

- 你当前插件的版本(必填)：
0.1.11

- 当前环境是小程序还是浏览器(选填)：
浏览器

- 详细描述你的bug：
1、本地开发环境可以，linux打包能成功，页面访问就报：无法获取到 CanvasContext2D 
2、代码应该没问题，安装lucky依赖的时候感觉路径不对，是跟node版本有关吗， 目前本地node版本是14.19.1， linux环境node版本14.17.1
   - 本地的node_moudles的路径lucky-canvas
![图片](https://user-images.githubusercontent.com/34293156/177918134-fb2f9e0f-1cd9-4da2-9645-cbcfde5d1534.png)
  - linux的node_moudles的lucky-canvas路径：
  - 
![图片](https://user-images.githubusercontent.com/34293156/177919498-44f04979-c28b-4c13-9912-f31f0321a533.png)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗


// 代码结束
```

**Comment by ranxiaoli** [comment]
这应该时我cnpm 安装包时出了问题，我用npm install 去安装时可以的，抱歉，打扰了~~~

**Comment by buuing** [comment]
没事, 尽量使用 npm 或 yarn 去安装插件, 用着顺手可以点个star支持一下
