### ISSUE TITLE
react-native 无法使用

### ISSUE THREAD

**Issue by guofuchegn** [buuing/lucky-canvas#302]
- 你当前是什么框架(必填)：react-native

- 你使用的是哪个包(必填)：lucky-canvas

- 你当前插件的版本(必填)："lucky-canvas": "^1.7.26",

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：无法使用 undefined is not an object (evaluating 'this.version = "1.7.26"')

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
不用怀疑, 这个包确实无法在 rn 里面使用

**Comment by buuing** [comment]
除非你在 rn 里套个 webview , 因为我这个包是基于浏览器环境开发的

**Comment by guofuchegn** [comment]
@lucky-canvas/react 这个呢?

**Comment by buuing** [comment]
都是浏览器环境, 要是能用我为啥不说给你? 我还能藏着掖着?

**Comment by buuing** [comment]
还有, 不要重复开一堆issues
