### ISSUE TITLE
react大转盘组件play后不转，但是调用stop有反应

### ISSUE THREAD

**Issue by cathats** [buuing/lucky-canvas#309]
- 你当前是什么框架(必填)：vite-react-app

- 你使用的是哪个包(必填)："@lucky-canvas/react": "^0.1.11"

- 你当前插件的版本(必填)：
   "lucky-canvas": "^1.7.20"
   "react": "^18.2.0"
   "vite": "^3.0.0"

- 当前环境是小程序还是浏览器(选填)：Chrome浏览器

- 详细描述你的bug：
完全按照 https://100px.net/usage/react.html 写的，但是无法转动

- 问题代码(重要)：和 https://100px.net/usage/react.html 一样

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
可否复现一个小demo发给我

**Comment by cathats** [comment]
https://pan.baidu.com/s/1skc0faeZEqz5X7rhfwxZRw 提取码: g9ru

**Comment by buuing** [comment]
是挺奇怪, 我看到问题了, 我研究一下

**Comment by cathats** [comment]
好的，谢谢

**Comment by buuing** [comment]
为了不影响你使用, 你可以先按照原生js的方式, 我测试这样使用没问题

1. **安装 `npm i lucky-canvas`**

2. **复制如下代码**

```tsx
import React, { useState, useRef, useEffect } from 'react'
import "./App.css";
import { LuckyWheel } from "lucky-canvas";

function App() {
  const divRef = useRef<HTMLDivElement>();
  useEffect(() => {
    const myLucky = new LuckyWheel({
      divElement: divRef.current,
    }, {
      width: '300px',
      height: '300px',
      blocks: [{ padding: "10px", background: "#869cfa" }],
      prizes: [
        { background: "#e9e8fe", fonts: [{ text: "022" }] },
        { background: "#b8c5f2", fonts: [{ text: "122" }] },
        { background: "#e9e8fe", fonts: [{ text: "2" }] },
        { background: "#b8c5f2", fonts: [{ text: "3" }] },
        { background: "#e9e8fe", fonts: [{ text: "4" }] },
        { background: "#b8c5f2", fonts: [{ text: "5666" }] },
      ],
      buttons: [
        { radius: "40%", background: "#617df2" },
        { radius: "35%", background: "#afc8ff" },
        {
          radius: "30%",
          background: "#869cfa",
          pointer: true,
          fonts: [{ text: "开始", top: "-10px" }],
        },
      ],
      start: function () {
        // 开始游戏
        myLucky.play()
        // 使用定时器模拟接口
        setTimeout(() => {
          // 结束游戏
          myLucky.stop(0)
        }, 3000)
      }
    })
  }, [])
  return (
    <>
      <div ref={divRef}></div>
    </>
  );
}

export default App;
```

**Comment by cathats** [comment]
刚刚使用纯js写完可以用，在修改样式的时候发现有两个转盘的canvas，于是尝试删除React.StrictMode，删除后按照Lucky React示例可以正常使用。

**Comment by buuing** [comment]
感谢反馈哈, 用着顺手可以点个 star 支持一下

**Comment by dora1995** [comment]
> 直接使用纯js写完就可以用了，在修改样式的时候发现有几个转盘的canvas，这样就可以删除React.StrictMode，删除后按照Lucky React示例就可以正常了。

定位后原因：抽奖组件的componentDidMount被触发了两次，导致页面上生成了两个抽奖，因为有设置宽高还有overflow，第二个被创建的抽奖组件被隐藏了（但是实际起作用的是第二个）。正因如此，才会在页面上看不到转盘转动但有结果输出

是react的版本（v18）导致：https://www.cnblogs.com/520BigBear/p/16370941.html

解决方案：代码修改组件的componentDidMount，在已经有实例的情况下就不再走initLucky

已经提交pr了，等作者大大验证后发版吧：）

**Comment by erdang** [comment]
求发版

**Comment by buuing** [comment]
在健身房，晚上到家就发版，别急

**Comment by buuing** [comment]
最新版 `@lucky-canvas/react@0.1.12` 已发布, 试一下吧
