### ISSUE TITLE
小程序引用老虎机组件报错

### ISSUE THREAD

**Issue by liuhui1999** [buuing/lucky-canvas#313]
- 你当前是什么框架(必填)：taro 

- 你使用的是哪个包(必填)："@lucky-canvas/taro"

- 你当前插件的版本(必填)： "^0.0.12",

- 当前环境是小程序还是浏览器(选填)：taro 

- 详细描述你的bug：
小程序引用老虎机组件报错

![image](https://user-images.githubusercontent.com/71832496/185342753-31b7aab0-9d47-4fc2-bb23-f6b73001ebc6.png)

![image](https://user-images.githubusercontent.com/71832496/185342790-ae1f8038-ba25-47d8-a4a5-0d264a0e2fd4.png)

- 问题代码(重要)：

export default SlotMachiner;
// 代码开始, 别再放歪了行吗
import React, { Component } from 'react';
import { SlotMachine } from '@lucky-canvas/taro/react'
import { View } from '@tarojs/components';
class SlotMachiner extends Component {
    myLucky: any
    constructor(props) {
        super(props);
        this.myLucky = React.createRef()
    }
    playGame = () => {
        this.myLucky.current.play()
        setTimeout(() => {
            // 假设 4 种结果
            const res = [
                [9, 9, 6],
                [0, 0, 7],
                [6, 6, 6],
                [8, 8, 8]
            ]
            // 随机取一组数据
            const index = res[Math.random() * 4 >> 0]
            // 调用 stop 方法停止游戏
            this.myLucky.current.stop(index)
        }, 500);
    }
    render() {
        return (
            <>
                <SlotMachine
                    ref={this.myLucky}
                    width={240}
                    height={180}
                    blocks={[
                        { padding: '10px', background: '#617df2' },
                        { padding: '10px', background: '#869cfa' },
                        { padding: '10px', background: '#afc8ff' },
                        { padding: '10px', background: '#e9e8fe' },
                    ]}
                >
                </SlotMachine>
                <View onClick={() => this.playGame()}>开始抽奖</View>
            </>
        );
    }
}

export default SlotMachiner;
// 代码结束
```

**Comment by buuing** [comment]
我都服了, 你看不到代码块的开始和结束吗, 这也能放歪?

**Comment by liuhui1999** [comment]
> 我都服了, 你看不到代码块的开始和结束吗, 这也能放歪?

问题不大 咋回事老哥

**Comment by buuing** [comment]
问题很大, 你重新编辑一下, 这代码都扭曲到一起了怎么看

**Comment by liuhui1999** [comment]
> 问题很大, 你重新编辑一下, 这代码都扭曲到一起了怎么看
ok

**Comment by buuing** [comment]
顺便提供taro的版本信息, 小程序基准库, 最好是发个能复现问题的demo

**Comment by liuhui1999** [comment]
> 顺便提供taro的版本信息, 小程序基准库, 最好是发个能复现问题的demo

https://github.com/liuhui1999/Lucky-demo

**Comment by buuing** [comment]
你这代码写的是什么？你在箭头函数里使用this？你在搞笑？

**Comment by liuhui1999** [comment]
> 你这代码写的是什么？你在箭头函数里使用this？你在搞笑？

![image](https://user-images.githubusercontent.com/71832496/185523085-aad79656-36ae-45d7-afd7-03eb679c0970.png)
![image](https://user-images.githubusercontent.com/71832496/185523104-e0fb412f-80c3-40d7-9d59-043ee4259885.png)

**Comment by buuing** [comment]
嗯? 还报错? 奇怪

**Comment by buuing** [comment]
说一下你taro的版本和小程序基准库的版本

**Comment by liuhui1999** [comment]
> 说一下你taro的版本和小程序基准库的版本

"dependencies": {
		"@babel/runtime": "^7.7.7",
		"@lucky-canvas/taro": "^0.0.12",
		"@tarojs/components": "3.5.2",
		"@tarojs/extend": "^3.4.7",
		"@tarojs/plugin-framework-react": "3.5.2",
		"@tarojs/react": "3.5.2",
		"@tarojs/runtime": "3.5.2",
		"@tarojs/taro": "3.5.2",
		"dayjs": "1.9.6",
		"react": "^17.0.0",
		"react-dom": "^17.0.0",
		"taro-code": "^3.5.2",
		"taro-ui": "^3.1.0-beta.3"
	},
	"devDependencies": {
		"@babel/core": "^7.8.0",
		"@tarojs/mini-runner": "3.5.2",
		"@tarojs/webpack-runner": "3.5.2",
		"@types/react": "^17.0.2",
		"@types/webpack-env": "^1.13.6",
		"@typescript-eslint/eslint-plugin": "^4.15.1",
		"@typescript-eslint/parser": "^4.15.1",
		"babel-preset-taro": "3.5.2",
		"eslint": "^6.8.0",
		"eslint-config-taro": "3.5.2",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-react-hooks": "^4.2.0",
		"stylelint": "^14.4.0",
		"taro-iconfont-cli": "^3.3.0",
		"typescript": "^4.1.0"
	}



![image](https://user-images.githubusercontent.com/71832496/185525915-4bdb1c10-74e1-4fd8-ba70-0e06d829880d.png)

**Comment by buuing** [comment]
排查完毕, `width={240}`改成`width={'240px'}`, height同理

但是这种数字的方式也可以支持一下, 今晚会发个新版兼容一下
