### ISSUE TITLE
想问一下在vue2中用axios请求成功后在success函数里面调用停止函数，动画会立即停止，而且指针位置也不对，不放在请求里面就没事

### ISSUE THREAD

**Issue by D-xhao** [buuing/lucky-canvas#314]
- 你当前是什么框架(必填)：vue2

- 你使用的是哪个包(必填)：@lucky-canvas/vue

- 你当前插件的版本(必填)："@lucky-canvas/vue": "^0.1.11",

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：在vue2中用axios请求成功后在success函数里面调用停止函数会立即停止，而且指针位置也不对，不放在请求里面就没事

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
 // 点击抽奖按钮会触发star回调
//html
  <LuckyWheel
    ref="myLucky"
    width="90vw"
    height="90vw"
    :prizes="prizes"
    :blocks="blocks"
    :buttons="buttons"
    @start="startCallback"
    @end="endCallback"
  />

//js
//引入方式
import {LuckyWheel} from '@lucky-canvas/vue'
//组件使用
  components:{
    [LuckyWheel.name]:LuckyWheel
  },
//开始按钮
    startCallback () {
        this.$axios.post({
          url: `xxx`,
          success: (res) => {
             //此时调用会立即停止转动动画
             this.$refs.myLucky.stop(0)
          }
      })
//如果是放在这里（接口请求外面），动画正常
      this.$refs.myLucky.stop(0)  //转动动画正常
}
// 代码结束
```

**Comment by buuing** [comment]
可否在 [这个demo里](https://100px.net/playground.html?vue=DwFwpgtgDgNghuAfAKAASuAGQK4GMDWAngOoAWYYMa6qATmAGYC8ARBITgYS9egO4BLACYhSrAMwAGSVAAePGqnICA5qRATpchTQBcUWgIBeYAM6sDxszvS6ARjAD2BcywfP8pm6nvYQIRwA7Vzs-AODvAAFTEDhaDRYYuJAAYTgYGDs4AiiwQKFWPKE0jKyc6gB6FGAK8Gh4JGRkYFNcQygQFDBZKEd41CFGOGwYEFQAb2ohBDhUAAoASgneOjAQbFpA5cV0dxddVABtFcVx1Cg4ISEBQJUDgHIARhlZe4AaVDL8FVpHbHyHgBiAAcADYAJy4Bhwe6oAC%2BJ1QAF03ojLCZTAdjjsaGcvj8-gDUPdAWBwWBgQwwO9UAwgiBMUczuBZCAHpJYXCkfDUTj0Hjst9fv8hEC7MDcABWBgAJhpdMCDKxzO6bOJj053LhvL5AoIBJFQLJFKp8vpjMOKtZDzl8K1OpxeqFhNFxMB4qlsrNiotVrV93Emp5iP5n0FBqJJONlOpHwVSqZqBZ-oALEHtSGJmH9cLI%2B6JdK5XHzcqk6qHpL0w6aCjEaF-EELZmzrRLgJsIz7inJABSGn43Oukmgx4AdiEXuDfKzreuHYe4klfY%2BA5dQLgDFwlIYnOrp0z6Fn7c7UmX2edhrdYMh0PeB-Ojhu4FoBxAtGwYD3O3jvrL1uJgAA%2BoA05o0gEUAPAAtM8ciapmCI4kiKzwVOqAQGspCOEIjKTIoFQVKggCdDoA34qAL1GgBqmoAkMaAHUpgBY8oAZ5GAIvKSS0IAe2qAMAxKzMak6SZIK8xLDhOx4agbGABSu5GACN%2BgBvcoAIW6wHAhCAJ2mgCrNsBgAcdoA8EaIqIAimAAdAAJPQDD6ewnBEHp8mEIsiLCYAhFaAPtGYmAKXGgDHyoAQPqAKbW5GIqYawACoCGhfwgHMiyoEwiDbHywmAOIKgB90YAcCqAPdegAr8SxMmALRyZGAES%2BgCo%2BoA9GaSJmuCNmMNyDLIEWoMV07CWJMSOFAgA6CoARtaANOmgA28YAbnqAATygBICdl%2BWZjp%2BlGYwpkcHgFmNVAcwVd0CyItqqBSNIS2KBmuH4eRgDLfoA%2Bub0QxRTsSsRQlLxBDzOiYACYipXBI4MBgHpTgqHMN0bTQW3wsgCI1K07SdEAA) 用定时器模拟复现一下这个bug吗

**Comment by D-xhao** [comment]
在demo里面的定时器是可以的，但是到了真正的请求success函数里面调用就会立即停止，
// 点击抽奖按钮会触发star回调
&nbsp; &nbsp; startCallback () {
&nbsp; &nbsp; &nbsp; if (!this.hasPhone) {
&nbsp; &nbsp; &nbsp; &nbsp; this.$emit('showPhone')
&nbsp; &nbsp; &nbsp; &nbsp; return
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; if (this.luckyData.user_draw_times < 1) {
&nbsp; &nbsp; &nbsp; &nbsp; this.$toast('没有抽奖次数了')
&nbsp; &nbsp; &nbsp; &nbsp; return
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; // 调用抽奖组件的play方法开始游戏


&nbsp; &nbsp; &nbsp; this.$refs.myLucky.play()

&nbsp; &nbsp; &nbsp; this.$axios.post({
&nbsp; &nbsp; &nbsp; &nbsp; url: `/a/lucky/${this.$route.query.luckyid}/draw`,
&nbsp; &nbsp; &nbsp; &nbsp; success: (res) =&gt; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; console.log(res)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; this.resultobj = res.data
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; let arr = []
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for(let i = 0 ; i < 8 ; i++){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if(this.prizes[i].id == res.data.prize_id){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; arr.push(i)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
            //arr的数据格式： arr=[0,1,2,3]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; arr = this.shuffle(arr)
              //这里是不行的，动不到半秒钟就直接停止动画了
              // this.$refs.myLucky.stop(arr[0])
              //如果放在定时函数里面可以转动，但是时间一到就重现上面的问题了，直接停下来，没有缓动的结束效果以及位置也不对
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // setTimeout(()=&gt;{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // this.$refs.myLucky.stop(arr[0])
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // },2000)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; setTimeout(()=&gt;{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; this.$emit('setResult', this.resultobj)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },2000)
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; error:(e)=&gt;{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; this.$toast(e.error)
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; })
       //如果放到这里是可以的
&nbsp; &nbsp; &nbsp; // setTimeout(()=&gt;{
&nbsp; &nbsp; &nbsp; // &nbsp; this.$refs.myLucky.stop(0)
&nbsp; &nbsp; &nbsp; // },1000)
&nbsp; &nbsp; },




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "buuing/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [buuing/lucky-canvas] 想问一下在vue2中用axios请求成功后在success函数里面调用停止函数，动画会立即停止，而且指针位置也不对，不放在请求里面就没事 (Issue #314)





 
可否在 这个demo里 用定时器模拟复现一下这个bug吗

**Comment by buuing** [comment]
我就这么说, 100%是你代码的问题, 如果是这个包的旋转逻辑有问题, 这个项目每个月上千的下载量, 早炸锅了, 你还是仔细检查你的代码吧

**Comment by BaoXianSheng** [comment]
我也碰到相同的问题了，出现的概率很大

**Comment by BaoXianSheng** [comment]
startCallback中根本无法调用请求方法，只要请求了，大概率会出现立即停止，指针位置错误，然而用setTimeout却没有问题，我用的是vue3的版本
