### ISSUE TITLE
大转盘组件加载完成后没有点击就触发了end回调

### ISSUE THREAD

**Issue by CodeGodV** [buuing/lucky-canvas#316]
- 你当前是什么框架(必填)：vue3

- 你使用的是哪个包(必填)：@lucky-canvas/vue

- 你当前插件的版本(必填)：0.1.11

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：刷新页面，即加载完成就触发了end回调

- 问题代码(重要)：请原谅，公司级别代码，无法提供

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
谁家代码不是公司级别的.......又不是让你把项目发出来, 不提供代码也行, [点击这个链接](https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlFQAZXAShwofAKYB3KGPwoAwgEM%2BENXQB0SggHUAFjJkYAFAHIAxKkziUlgDRQA3lS5c5sNkYBcUJYATAAMISwAHs4eniZgAOZGbAHBYZHRnlAARhg8%2BHQBANquUCxqIOB88SkAjOFRLllq%2BPGMPFh8ICnWABwAbACcOABmapZQAL4Auk4xXCzMAF4yBVCFc54lTS1tHV2B1jIDMj3DMs5Qw-xsq8VQbDIRyYEh49OTs5lcW814re2dbpZHo4ACswyCFyufBuRRKDyetTeUw%2BG2%2B2V%2B-z23SOJzOUOut3hj2ewWRqK%2BbgxOwB%2BxswLBEIJMKJ9xJKQAzOSJp8vj8adiDrjTucXNDYWtiYjAgAWbm8zL8v67QEHBngyFiwlwtnSyyg%2BUbGYbLJYNhsfi3NFUxjlMBYVaWGUhACkF22ytp3T6NQA7CAmRS%2BVBbeAHZzQW7GpiVXTrGphjhTsM3grNtauKH7Y6Oa73TGvQd%2BkNRhlKaUeGAYTJGAE2IwsDI05lxayEaTAAD6gGnNC4WlgpNB1dKTKbWnlGtOCNSMZ7DDo4NhgfjmACUbmtpFIUG7gA47QDwRtbRA4dCwMGoUKuN1vAOIKgD7owClxoBj5UAIW6Ad%2BjAEI2gHwEwBleoB6MxqdDWnQMhsAAKmASAyO0bDmAA%2BpIRDruWUCblAgA6CoARtb7hmwgoPoKA6IIPAsOYIQrmOLh1GE5GZOOmQyKqc58AuS58OYCxgMsa4lKh%2B6YYAb6aAGeRgCLytaagYDWMGWIAtgaADmqgC0coAapopFAADUpRLDIOitoUIRTDo7Y0Z4EwxBM5FkAwzDsNQQA), 把问题复现一下发我

**Comment by buuing** [comment]
[vue的可以点这个链接](https://100px.net/playground.html?vue=DwFwpgtgDgNghuAfAKAASuAGQK4GMDWAngOoAWYYMa6qATmAGYC8ARBITgYS9egO4BLACYhSrAMwAGSVAAePGqnICA5qRATpchTQBcUWgIBeYAM6sDxszvS6ARjAD2BcywfP8pm6nvYQIRwA7Vzs-AODvAAFTEDhaDRYYuJAAYTgYGDs4AiiwQKFWPKE0jKyc6gB6FGAK8Gh4JGRkYFNcQygQFDBZKEd41CFGOGwYEFQAb2ohBDhUAAoASgneOjAQbFpA5cV0dxddVABtFcVx1Cg4ISEBQJUDgHIARhlZe4AaVDL8FVpHbHyHgBiAAcADYAJy4Bhwe6oAC%2BJ1QAF03ojLCZTAdjjsaGcvj8-gDUPdAWBwWBgQwwO9UAwgiBMUczuBZCAHpJYXCkfDUTj0Hjst9fv8hEC7MDcABWBgAJhpdMCDKxzO6bOJj053LhvL5AoIBJFQLJFKp8vpjMOKtZDzl8K1OpxeqFhNFxMB4qlsrNiotVrV93Emp5iP5n0FBqJJONlOpHwVSqZqBZ-oALEHtSGJmH9cLI%2B6JdK5XHzcqk6qHpL0w6aCjEaF-EELZmzrRLgJsIz7inJABSGn43Oukmgx4AdiEXuDfKzreuHYe4klfY%2BA5dQLgDFwlIYnOrp0z6Fn7c7UmX2edhrdYMh0PeB-Ojhu4FoBxAtGwYD3O3jvrL1uJgAA%2BoA05o0gEUAPAAtM8ciapmCI4kiKzwVOqAQGspCOEIjKTIoFQVKggCdDoA34qAL1GgBqmoAkMaAHUpgBY8oAZ5GAIvKSS0IAe2qAMAxKzMak6SZIK8xLDhOx4agbGABSu5GACN%2BgBvcoAIW6wHAhCAJ2mgCrNsBgAcdoA8EaIqIAimAAdAAJPQDD6ewnBEHp8mEIsiLCYAhFaAPtGYmAKXGgDHyoAQPqAKbW5GIqYawACoCGhfwgHMiyoEwiDbHywmAOIKgB90YAcCqAPdegAr8SxMmALRyZGAES%2BgCo%2BoA9GaSJmuCNmMNyDLIEWoMV07CWJMSOFAgA6CoARtaANOmgA28YAbnqAATygBICdl%2BWZjp%2BlGYwpkcHgFmNVAcwVd0CyItqqBSNIS2KBmuH4eRgDLfoA%2Bub0QxRTsSsRQlLxBDzOiYACYipXBI4MBgHpTgqHMN0bTQW3wsgCI1K07SdEAA)
