### ISSUE TITLE
开始按钮在pc浏览器上有小问题

### ISSUE THREAD

**Issue by 284099857** [buuing/lucky-canvas#317]
开始按钮在pc浏览器上有小问题
鼠标移动到开始按钮上无法显示点击图标
就是css里的cusor:pointer 估计插件内部没有实现这个

**Comment by buuing** [comment]
本来就没有, 这个功能我认为没必要, 就没加

2.0版本里可以考虑一下

**Comment by 284099857** [comment]
好吧  能给个快速加上这个效果的方法么

**Comment by buuing** [comment]
很遗憾, 当初设计的时候, 没有对外提供关于鼠标移动的扩展方法

但是我有个折中的方案, 你可以用dom元素写一个按钮, 然后盖在我的按钮上面, 然后你把start回调绑定在dom上

**Comment by 284099857** [comment]
好的
