### ISSUE TITLE
文档官网进不去，看不清楚数据结构该怎么传

### ISSUE THREAD

**Issue by zmc89** [buuing/lucky-canvas#319]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by zmc89** [comment]
11

**Comment by buuing** [comment]
国内没有可以免费托管的服务, 文档部署在 github pages 上面, 你都能上 github, 那文档也能进去, 多刷新几次吧

**Comment by buuing** [comment]
或许你会疑惑, 作者为啥不自己买个服务器绑定域名, 因为作者没钱......再加上这个项目没有收入来源, 所以只能选择免费资源部署官网

**Comment by zmc89** [comment]
好的，我使劲刷新有时候能进去
