### ISSUE TITLE
引入LuckyWheel编译后报错could not resolve

### ISSUE THREAD

**Issue by hansondy** [buuing/lucky-canvas#324]
- 你当前是什么框架(必填)：基于vue3+ts 的uniapp

- 你使用的是哪个包(必填)：@lucky-canvas/uni/lucky-wheel

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：微信小程序

- 详细描述你的bug：使用npm install @lucky-canvas/uni后在页面引入 import LuckyWheel from '@lucky-canvas/uni/lucky-wheel'，
- 执行npm dev编译后报错 Could not resolve '../../lucky-canvas' from node_modules/@lucky-canvas/uni/lucky-wheel.vue

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
奇怪, 可能依赖安装失败了, 你再安一下依赖就行了

```
npm i lucky-canvas
```

**Comment by hansondy** [comment]
谢谢，已解决，要安装lucky-canvas ***@***.***/uni 两个包才可以&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 下午4:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [buuing/lucky-canvas] 引入LuckyWheel编译后报错could not resolve (Issue #324)





 
奇怪, 可能依赖安装失败了, 你再安一下依赖就行了
 npm i lucky-canvas

**Comment by buuing** [comment]
不用, 只安装 `@lucky-canvas/uni` 就行, 依赖会自动安装, 你这个不过是依赖安装失败罢了

**Comment by buuing** [comment]
用着顺手可以点个star支持一下
