### ISSUE TITLE
奖品 - prizes的item的background不支持背景图片吗

### ISSUE THREAD

**Issue by 742087271** [buuing/lucky-canvas#325]
- 你当前是什么框架(必填)：vue3

- 你使用的是哪个包(必填)："@lucky-canvas/vue": "^0.1.11"

- 你当前插件的版本(必填)：0.1.11

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：奖品 - prizes的item的background不支持背景图片吗

- 问题代码(重要)：暂时没有

```
暂时没有

// 代码结束
```

**Comment by buuing** [comment]
用`imgs`
