### ISSUE TITLE
可以不均匀分布，设置角度吗？

### ISSUE THREAD

**Issue by xlfhy** [buuing/lucky-canvas#331]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
1.x不可以, 这个打算放到2.x里去做

**Comment by xlfhy** [comment]
需要多久

**Comment by buuing** [comment]
今年没戏了

**Comment by xlfhy** [comment]
可以给个更改区域吗 我去改下源码

**Comment by buuing** [comment]
你直接fork不就得了, 但是牵涉代码很多, 因为连带着canvas的文字换行以及图片宽度百分比计算都得改, 还有停止位置的计算
