### ISSUE TITLE
使用的vue 通过script引用，lucky-wheel组件设置defaultConfig里面的offsetDegree不生效

### ISSUE THREAD

**Issue by xlfhy** [buuing/lucky-canvas#333]
![1664260465426](https://user-images.githubusercontent.com/44394567/192451535-1c185b30-f19d-46dd-8845-62794d742605.jpg)
![1664260465430](https://user-images.githubusercontent.com/44394567/192451544-204db4b0-ae83-4fa4-8030-1b01a75988fe.jpg)

**Comment by buuing** [comment]
排查完毕, 语法错误
