### ISSUE TITLE
能否增加奖品文字里设置图标的功能

### ISSUE THREAD

**Issue by a4521** [buuing/lucky-canvas#334]
- 你当前是什么框架(必填)：VUE

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：0.1.11

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：在prizes的fonts中能否传图标

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
什么图标, 举例

**Comment by a4521** [comment]
![image](https://user-images.githubusercontent.com/112801586/192926521-e981041e-21a2-40d7-a307-9fb8167397a9.png)
这种的

**Comment by buuing** [comment]
你用imgs不行吗?

**Comment by a4521** [comment]
我在prizes的fonts里加的imgs，没效果

**Comment by buuing** [comment]
????????????? 你可真会想

**Comment by a4521** [comment]
那加在哪里

**Comment by buuing** [comment]
你去点个star我告诉你

**Comment by a4521** [comment]
点了哇

**Comment by buuing** [comment]
加在prizes的imgs
