### ISSUE TITLE
大转盘使用gif做灯效,然后只渲染了gif的第一帧

### ISSUE THREAD

**Issue by zb1843** [buuing/lucky-canvas#335]
- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
目前不支持gif图片格式, 改用img加绝对定位

**Comment by zb1843** [comment]
好的

**Comment by buuing** [comment]
用着顺手可以点个star支持一下

**Comment by zb1843** [comment]
已点

**Comment by zb1843** [comment]
好的,我发现不使用blocks属性也可以自己组装,谢谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月8日 11:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [buuing/lucky-canvas] 大转盘使用gif做灯效,然后只渲染了gif的第一帧 (Issue #335)


目前不支持gif图片格式, 改用img加绝对定位

―
