### ISSUE TITLE
uniapp app端 大转盘开始抽奖旋转会有卡顿现象 版本： 1.3.9

### ISSUE THREAD

**Issue by liumingjie-jojo** [buuing/lucky-canvas#337]
> 

https://user-images.githubusercontent.com/63400909/196084436-6aa8aa88-99f3-454b-8757-2c1ef45633f7.mp4

https://user-images.githubusercontent.com/63400909/196084467-942495e0-4fda-4429-a4a6-b9ebfe38bd70.mp4

- 你当前是什么框架(必填)：

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
uniapp暂不支持app端

**Comment by liumingjie-jojo** [comment]
好的，谢谢
