### ISSUE TITLE
uniapp移动web在安卓机显示正常，ios端就一片空白

### ISSUE THREAD

**Issue by XjiangSail** [buuing/lucky-canvas#338]
![微信截图_20221021110923](https://user-images.githubusercontent.com/75155358/197102472-30c0bca3-4890-4066-ad4e-48448b491151.png)

![微信截图_20221021110952](https://user-images.githubusercontent.com/75155358/197102518-175f9c69-d6f0-4c2c-8d8f-34b7b07be1cc.png)

**Comment by buuing** [comment]
参考这个 issues https://github.com/buuing/lucky-canvas/issues/329

**Comment by XjiangSail** [comment]
> 参考这个 issues #329

用的@lucky-canvas/uni@0.0.13

我看源码里边也有获取dpr呀，不知道怎么改了
![image](https://user-images.githubusercontent.com/75155358/197159888-50835c8b-23fb-4f58-acc5-ea3fc3630028.png)


![image](https://user-images.githubusercontent.com/75155358/197160148-6074f90d-0052-4c48-a518-264ffebd1c1e.png)
![image](https://user-images.githubusercontent.com/75155358/197160234-12b84885-aee2-4f1d-91e1-e43c89e13466.png)
![image](https://user-images.githubusercontent.com/75155358/197160310-9eb143b2-77c5-4b9e-9385-fdc7be6926bf.png)
![image](https://user-images.githubusercontent.com/75155358/197160761-7b114799-4878-4020-b1bc-379894877d87.png)

**Comment by buuing** [comment]
改成`const dpr = this.dpr = 1`不就得了

**Comment by XjiangSail** [comment]
> 改成`const dpr = this.dpr = 1`不就得了

感谢，解决了
