### ISSUE TITLE
uniapp转盘在ios真机调试上出现固定定位问题

### ISSUE THREAD

**Issue by 974854447** [buuing/lucky-canvas#339]
- 你当前是什么框架(必填)：uniapp

- 你使用的是哪个包(必填)：h5 app 微信小程序

- 你当前插件的版本(必填)：v0.0.10_4

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：无论是app h5 还是微信小程序 在iOS真机调试都会出现转盘呈现固定定位，导致滑动页面时转盘不跟随页面滚动
- 安卓真机不存在这种问题

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
`真机调试`还是`体验版`???

**Comment by buuing** [comment]
真机调试的话请忽略, 以体验版为准
