### ISSUE TITLE
请问源码里的刻舟求剑方法是啥意思？为什么叫刻舟求剑？

### ISSUE THREAD

**Issue by coderhsw** [buuing/lucky-canvas#344]
源码位置： https://github1s.com/buuing/lucky-canvas/blob/HEAD/packages/core/src/lib/grid.ts#L510

![image](https://user-images.githubusercontent.com/33214701/201467251-6c7f78d5-d01f-47d7-b3d1-06d13d30caa4.png)

**Comment by buuing** [comment]
用来测速的
