### ISSUE TITLE
PC小程序九宫格图标不显示

### ISSUE THREAD

**Issue by PickClass** [buuing/lucky-canvas#345]
- 你当前是什么框架(必填)：
- 原生微信小程序 PC

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(选填)：
- 小程序PC

- 详细描述你的bug：
- PC小程序九宫格图标不显示 编辑器和手机没有问题
具体就是我设置了 一个背景还有背景经过改变    奖品图标在PC端显示不出来
![Uploading image.png…]()

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
       imgs: [{
                            src: '/packageD/images/img_product_border@2x.png',
                            activeSrc: '/packageD/images/img_product_border_selected@2x.png',
                            width: '100%',
                            height: '100%',
                        },
                        {
                            src: '',
                            width: '124rpx',
                            height: '',
                            top: '7rpx'
                        },
                    ],
// 代码结束
```
![Uploading 1669018896980.jpg…]()

**Comment by PickClass** [comment]
![image](https://user-images.githubusercontent.com/35389878/203083261-351fadf2-e9d5-46b3-80e8-11f69640b738.png)

**Comment by buuing** [comment]
是这样的, 我没调过PC端的兼容, 因为之前小程序是不支持PC端开始canvas type2d的

所以不清楚, 也没关注过小程序PC端对canvas的支持程度
