### ISSUE TITLE
大转盘有办法给每个button都加上一层阴影吗？

### ISSUE THREAD

**Issue by ztcaoll222** [buuing/lucky-canvas#349]
- 你当前是什么框架(必填)：react 

- 你使用的是哪个包(必填)：lucky-canvas

- 你当前插件的版本(必填)：1.7.27

- 当前环境是小程序还是浏览器(选填)：浏览器

大转盘有办法给每个button都加上一层阴影吗？

在这里提前谢谢作者

**Comment by buuing** [comment]
什么阴影? 举个例子我看看
