### ISSUE TITLE
请问完整事例的代码还会放出来吗？

### ISSUE THREAD

**Issue by mistyrain-jiangnan** [buuing/lucky-canvas#350]
- 你当前是什么框架(必填)：uni-app

- 你使用的是哪个包(必填)：@lucky-canvas/

- 你当前插件的版本(必填)：v0.0.10_4

- 当前环境是小程序还是浏览器(选填)： 浏览器

- 详细描述你的bug：请问完整事例的代码还会放出来吗？

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
  请问完整事例的代码还会放出来吗？
// 代码结束
```

```

**Comment by buuing** [comment]
明年吧, 主要是 playground 里的代码都要手写, 得花费一两天的时间, 优先级比较低, 就一直懒得加

**Comment by mistyrain-jiangnan** [comment]
> 直懒得加

好的

**Comment by juukee** [comment]
+1

**Comment by ken678** [comment]
+1

**Comment by skyfranky** [comment]
+1
