### ISSUE TITLE
老虎机奖品太多渲染不出来

### ISSUE THREAD

**Issue by 284099857** [buuing/lucky-canvas#351]
框架：普通html页面
js：new LuckyCanvas.SlotMachine
bug:
70个奖品以内可以渲染出来 超过70个直接白板，也不报错

**Comment by buuing** [comment]
太多了, 超出画布限制了

**Comment by buuing** [comment]
参考[常见问题](https://github.com/buuing/lucky-canvas/issues/181)第一个

**Comment by 284099857** [comment]
有好法子 我们这个是116个姓名滚动的

**Comment by buuing** [comment]
听上去像是年会抽奖

**Comment by buuing** [comment]
很遗憾, 我这个抽奖插件不是为年会这种场景设计的

**Comment by 284099857** [comment]
pc谷歌浏览器的

**Comment by 284099857** [comment]
哈哈 是的 就是公司年会 抽名字  好吧  谢谢你了 自己想想办法

**Comment by 284099857** [comment]
参考https://github.com/buuing/lucky-canvas/issues/297
根据这个改小dpr 虽然清晰度稍稍小问题，但是老板说解决了就行 谢谢大佬指点

**Comment by buuing** [comment]
没事, 用着顺手可以点个star支持一下
