### ISSUE TITLE
装盘奖品数量多的时候文字放不下，可不可以优化下，文字竖着放置

### ISSUE THREAD

**Issue by wenleixyn** [buuing/lucky-canvas#354]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：

- 你当前插件的版本(必填)：0.1.11

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：装盘奖品数量多的时候文字放不下，可不可以优化下，文字竖着放置

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
直接换行不就得了

**Comment by wenleixyn** [comment]
换行的话文字也是横着的，想文字是旋转90°显示

**Comment by buuing** [comment]
目前不提供文字旋转的功能, 你可以把文字贴在图片里, 然后把图片配置在大转盘里

**Comment by wenleixyn** [comment]
如果在源码里改，是不是的在文字绘制的地方改文字方向

**Comment by buuing** [comment]
魔改我代码的话请自便, 这里不提供对应的技术支持
