### ISSUE TITLE
uniapp支付宝小程序真机调试显示有问题

### ISSUE THREAD

**Issue by jinyalong** [buuing/lucky-canvas#357]
uniapp vue2使用
支付宝开发小程序显示如下：
<img width="1151" alt="截屏2023-01-01 22 51 25" src="https://user-images.githubusercontent.com/53113006/210174880-3f031043-f5d0-4752-af99-c88a0bfbd083.png">
手机上调试如下：
![image](https://user-images.githubusercontent.com/53113006/210174921-0ca3d720-eef8-4431-a519-11ca9392559a.png)

**Comment by buuing** [comment]
额, 首先我没调过支付宝小程序的兼容, 其次真机调试有bug, 我通常建议直接看体验版

**Comment by jinyalong** [comment]
嗯嗯，我现在已经发布了体验版本，也存在一样的问题😂，我发现是两种比较固定的显示bug，在一些别的手机上还有其他显示bug类型

**Comment by buuing** [comment]
支付宝小程序的用户量比较小, 不太想维护这个, 想使用的可以自己调兼容😂
