### ISSUE TITLE
React如何设置dpr

### ISSUE THREAD

**Issue by qqqrr** [buuing/lucky-canvas#358]
- 你当前是什么框架(必填)：
React

- 你使用的是哪个包(必填)：
Lunck-canvas/react

- 你当前插件的版本(必填)：
0.1.13

- 当前环境是小程序还是浏览器(选填)：
浏览器

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
切换到`lucky-canvas`这个包即可设置dpr
