### ISSUE TITLE
canvas动画导致小程序页面缓存过高崩溃

### ISSUE THREAD

**Issue by Xuzhanglao** [buuing/lucky-canvas#361]
- 你当前是什么框架(uniapp)：

- 你使用的是哪个包( https://ext.dcloud.net.cn/plugin?id=3499)：

- 你当前插件的版本(必填)：

- 当前环境是小程序还是浏览器(小程序)：

- 详细描述你的bug：canvas动画缓存过高导致小程序会崩溃，然后会杀掉微信

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
用的哪个抽奖? 好像没听过这个问题哎
