### ISSUE TITLE
九宫格抽奖点击非交互的宫格时希望能有个回调函数返回该宫格的所有信息，比如图片信息，宫格位置等

### ISSUE THREAD

**Issue by LeeMiu** [buuing/lucky-canvas#364]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：lucky-canvas/vue

- 你当前插件的版本(必填)："@lucky-canvas/vue": "^0.1.11",

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：点击非交互的宫格时希望能有个回调函数返回该宫格的所有信息，比如图片信息，宫格位置等

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by LeeMiu** [comment]
[提问 & 建议 📢]

**Comment by buuing** [comment]
这个逻辑很简单, 你可以自行实现, 我之所以内部没有这个逻辑, 是小程序不支持这个api, 所以为了统一就都没加

**Comment by buuing** [comment]
你的九宫格大概率是规则图形, 所以你可以自行添加一个点击时间, 判断一下鼠标点击的位置, 并且, 奖品是你自己填充进去的, 所以你可以通过点击的位置获取到对应的奖品

**Comment by LeeMiu** [comment]
get it
