### ISSUE TITLE
提问：怎么保证prizes中的imgs里面的src图片展示不拉升不挤压。ps:服务器传回的图片可能是不同尺寸的

### ISSUE THREAD

**Issue by LeeMiu** [buuing/lucky-canvas#365]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：lucky-canvas/vue

- 你当前插件的版本(必填)：@lucky-canvas/vue": "^0.1.11

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
![image](https://user-images.githubusercontent.com/29720692/217139072-a61b7853-b259-4cbc-8a72-a29e9fd6afa6.png)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
文档有写, 只设宽度

**Comment by LeeMiu** [comment]
多谢多谢
