### ISSUE TITLE
九宫格可以设置自动动画慢旋转嘛？点击按钮时再快速抽奖，结束后再恢复慢动画

### ISSUE THREAD

**Issue by LeeMiu** [buuing/lucky-canvas#370]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)：lucky-canvas/vue

- 你当前插件的版本(必填)："@lucky-canvas/vue": "^0.1.11"

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
目前需求想默认会自动慢旋转，点击抽奖时快速旋转抽奖。
个人想到：可以在dom加载后执行play()函数动起来，然后点抽奖按钮改变speed，然后停止。弹窗显示结果后再次play慢旋转动起来。
issue：先执行play函数后，点击抽奖按钮却无法执行onStart回调

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
先设置速度为1, play开始游戏, 然后init重置, 设置速度为20, 开始正常抽奖流程

**Comment by LeeMiu** [comment]
play开始游戏后，点中间的抽奖开始按钮怎么或者这个点击事件呢？

**Comment by LeeMiu** [comment]
> 先设置速度为1, play开始游戏, 然后init重置, 设置速度为20, 开始正常抽奖流程

play开始游戏后，点中间的抽奖开始按钮怎么或者这个点击事件呢？

**Comment by buuing** [comment]
不是说了吗, init重置啊, 你的代码逻辑自己解决, 想重新渲染也行, 随你

**Comment by LeeMiu** [comment]
> 不是说了吗, init重置啊, 你的代码逻辑自己解决, 想重新渲染也行, 随你

不好意思，上面描述有问题。我想问的是，在play过程中，要怎么知道我点击的是中间开始按钮？只能通过监听点击时位置嘛？我要知道是点击了中间开始按钮才进行init充值然后再正常抽奖，如果点到其他地方那我就不管依旧按照原来play慢旋转。所以这块有点不明白，请教下

**Comment by buuing** [comment]
strat回调

**Comment by LeeMiu** [comment]
> strat回调

play过程中，点击中间开始按钮，我这边不会触发start回调

**Comment by buuing** [comment]
哦对, 我想起来了, 我屏蔽掉了

**Comment by LeeMiu** [comment]
当时考虑是担心快速点击是嘛？

**Comment by buuing** [comment]
不是, 是因为你在游戏中了, 就没必要再触发开始回调了

那你可以这样, 别用我的按钮了, 你自己做个div盖在按钮上面, click逻辑你自己就能随便定义了

**Comment by LeeMiu** [comment]
嗯嗯，好的

**Comment by LeeMiu** [comment]
> 


> 先设置速度为1, play开始游戏, 然后init重置, 设置速度为20, 开始正常抽奖流程

再请教一下，这个init重置后，设置速度为20，这个怎么设置？我用一个vue响应式数字变量存这个速度speed也没有效果，标识游戏中时为20，其他默认speed为1的慢速也没有效果。
![image](https://user-images.githubusercontent.com/29720692/217701928-4a91d238-e7db-4d31-a93d-4a40ac428e28.png)

**Comment by LeeMiu** [comment]
> > 
> 
> > 先设置速度为1, play开始游戏, 然后init重置, 设置速度为20, 开始正常抽奖流程
> 
> 再请教一下，这个init重置后，设置速度为20，这个怎么设置？我用一个vue响应式数字变量存这个速度speed也没有效果，标识游戏中时为20，其他默认speed为1的慢速也没有效果。 ![image](https://user-images.githubusercontent.com/29720692/217701928-4a91d238-e7db-4d31-a93d-4a40ac428e28.png)

就想要在init初始化同时配置中的speed也为20，这种效果

**Comment by LeeMiu** [comment]
> > > 
> > 
> > 
> > > 先设置速度为1, play开始游戏, 然后init重置, 设置速度为20, 开始正常抽奖流程
> > 
> > 
> > 再请教一下，这个init重置后，设置速度为20，这个怎么设置？我用一个vue响应式数字变量存这个速度speed也没有效果，标识游戏中时为20，其他默认speed为1的慢速也没有效果。 ![image](https://user-images.githubusercontent.com/29720692/217701928-4a91d238-e7db-4d31-a93d-4a40ac428e28.png)
> 
> 就想要在init初始化同时配置中的speed也为20，这种效果

给整个组件加一个以speedNum组装的字符串key可以实现，但是在点击时可能有一个更换组件key的闪烁的过程。

**Comment by AixLeftY** [comment]
您好，楼主解决了吗？我也有这个需求

**Comment by LeeMiu** [comment]
> 您好，楼主解决了吗？我也有这个需求

解决了。首先通过ref进行绑定。加了key（一个跟speed关联的变化字符串），设置变量speed，默认初始状态一个1.5低速的speed调用play()函数让他自己慢动画。点击抽奖按钮时，变化speed为20高速的值并执行init函数再初始化一下，然后再执行play()函数快速转起来，通过stop(idx)定位到奖品弹窗后关闭弹窗(或者接口报错后也要stop)；再重更新设置speed为1.5低速值并执行init函数再初始化一下，然后再执行play()函数慢速转起来。
