### ISSUE TITLE
9宫格如何动态设置activeSrc

### ISSUE THREAD

**Issue by webnoble** [buuing/lucky-canvas#371]
- 你当前是什么框架(必填)：taro 

- 你使用的是哪个包(必填)：@lucky-canvas/taro

- 你当前插件的版本(必填)：0.0.14

- 当前环境是小程序还是浏览器(选填)：小程序

- 详细描述你的bug：

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗

// 代码结束
```

**Comment by buuing** [comment]
取决于你如何使用
