### ISSUE TITLE
vue中使用包，与设置css变量的问题

### ISSUE THREAD

**Issue by purplecolor** [buuing/lucky-canvas#390]
- 你当前是什么框架(必填)：vue

- 你使用的是哪个包(必填)： "@lucky-canvas/vue": "^0.1.11",

- 你当前插件的版本(必填)： "@lucky-canvas/vue": "^0.1.11",

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：离开使用抽奖组件的页面后，进入另页面，该页面内有使用document.documentElement.style.setProperty设置css变量，此时会报错 Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-3.62693) is negative。该设置css变量的功能涉及一个项目的主要皮肤功能。是否包确有该冲突。

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
https://github.com/purplecolor/luckyWheel.git
// 代码结束
```

**Comment by purplecolor** [comment]
已找到问题，抽奖组件没有传宽高，而是使用class类名写的样式，谢谢

**Comment by buuing** [comment]
怎么可能跟document有冲突....
