### ISSUE TITLE
TypeError: (void 0) is not a funciton

### ISSUE THREAD

**Issue by kratospan** [buuing/lucky-canvas#407]
- 你当前是什么框架(必填)：Nuxt2(基于vue2)

- 你使用的是哪个包(必填)： @lucky-canvas/vue

- 你当前插件的版本(必填)："@lucky-canvas/vue": "^0.1.9"

- 当前环境是小程序还是浏览器(选填)：浏览器 SSR

- 详细描述你的bug：我并没有使用到这个包提供的相关的组件，仅仅只是引入了这个包就报错了。当将这个包给去掉之后，项目就正常了、
- 
![image](https://github.com/buuing/lucky-canvas/assets/46380968/60e04067-d922-4214-b343-278e13fb3247)
![image](https://github.com/buuing/lucky-canvas/assets/46380968/a83e4c94-0ddc-4a85-9c7d-ce2e3bbbfb7e)

- 问题代码(重要)：
因为压根没有用到这个相关的组件，所以只能提供引入的代码，但我估计没什么用

```
import Vue from 'vue';
import VueLuckyCanvas from '@lucky-canvas/vue';
import water from 'vue-waterfall2';
import {
  Cascader,
  Select,
  Rate,
  Upload,
  Modal,
  DatePicker,
} from 'ant-design-vue';
import showToast from '~basic/utils/showToast';

// 抽奖工具
Vue.use(VueLuckyCanvas);
Vue.use(water);
// antd 组件
Vue.use(Cascader);
Vue.use(Select);
Vue.use(Rate);
Vue.use(Upload);
Vue.use(Modal);
Vue.use(DatePicker);
Vue.prototype.$showToast = showToast;

export default context => {
  context.$showToast = showToast;
};

```

我们的项目之前使用这个包的时候，都是能正常运行的，昨天生产环境的代码都是没问题。今天发布了新的代码之后就报这个错误了，所以只能在生产环境里面将这个包给下下来了。

**Comment by buuing** [comment]
奇怪的错误, void 0会得到一个undefined, 肯定不是function

你这样吧, 直接按照[在js中使用]的方法, 用dom去渲染吧

**Comment by kratospan** [comment]
> 奇怪的错误, void 0会得到一个undefined, 肯定不是function
> 
> 你这样吧, 直接按照[在js中使用]的方法, 用dom去渲染吧

那好，那我试一下
