### ISSUE TITLE
转盘抽奖-背景图和buttons图片不显示当前项目的静态图片（但是可以显示网页链接的外部图）

### ISSUE THREAD

**Issue by liurich666** [buuing/lucky-canvas#414]
- 你当前是什么框架(必填)：react

- 你使用的是哪个包(必填)："@lucky-canvas/react": "^0.1.13",

- 你当前插件的版本(必填)：yarn v1.22.17

- 当前环境是小程序还是浏览器(选填)：微信公众号开发，在微信小程序上进行调试

- 详细描述你的bug：转盘抽奖背景图和buttons图片不显示当前项目的静态图片

- 问题代码(重要)：
![image](https://github.com/buuing/lucky-canvas/assets/53335446/7029c60d-e084-4047-a7f2-94821676e721)
![image](https://github.com/buuing/lucky-canvas/assets/53335446/4b4daead-4cbf-45c9-bbff-5b287aef09bf)

**Comment by guawazi233** [comment]
请问怎么解决的，我的react的block的背景图就无法展示了
