### ISSUE TITLE
TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by vvizden** [buuing/lucky-canvas#456]
- 你当前是什么框架(必填)：taro react

- 你使用的是哪个包(必填)：@lucky-canvas/taro

- 你当前插件的版本(必填)：^0.0.14

- 当前环境是小程序还是浏览器(选填)：小程序

- 详细描述你的bug：
TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': 3 arguments required, but only 1 present.

追踪源码到这行：

![image](https://github.com/buuing/lucky-canvas/assets/32644183/7ca03d6a-e396-4b2b-a513-3ec0bd44ffb4)

rectInfo 长度是 4，slice(4, 6) 的话，putImageData 后面两个参数自然就缺失了

- 问题代码(重要)：https://github.com/buuing/lucky-canvas/blob/096b39ba753a6a4db51b0e4ecce140ebeff4e59b/packages/core/src/lib/lucky.ts#L263C43-L263C54

尝试在 taro-react 中使用图片圆角，formatter 函数时发现了这个问题

**Comment by buuing** [comment]
我想看看你的formatter是怎么用的, 因为理论上小程序是无法使用这个属性的吧

**Comment by vvizden** [comment]
> 我想看看你的formatter是怎么用的, 因为理论上小程序是无法使用这个属性的吧

```js
{
  width: '80%',
  top: '20%',
  src: 'https://xxx/WechatIMG2720230111102023.jpeg',
  formatter(img) {
    const { width, height } = img
    const canvas = Taro.createOffscreenCanvas({
      type: '2d',
      width,
      height,
    })
    const ctx = canvas.getContext('2d') as any
    roundRectByArc(ctx, 0, 0, width, height, 50)
    ctx.clip()
    ctx.drawImage(img, 0, 0, width, height)
    return canvas
  },
},
```
理论上我也不知道行不行，就是按你的例子尝试写的

**Comment by buuing** [comment]
我的例子是给pc端用的...小程序我没调试过, 估计有问题, 他参数都不一致, 缺斤少两的很正常, 所以我基本都放弃维护小程序了

**Comment by vvizden** [comment]
> 我的例子是给pc端用的...小程序我没调试过, 估计有问题, 他参数都不一致, 缺斤少两的很正常, 所以我基本都放弃维护小程序了

了解🫡
