### ISSUE TITLE
奖品背景图是否支持动图

### ISSUE THREAD

**Issue by FlashWo1f** [buuing/lucky-canvas#470]
- 你当前是什么框架(必填)：Vue2

- 你使用的是哪个包(必填)：@lucky-canvas/vue 

- 你当前插件的版本(必填)：@0.1.11

- 当前环境是小程序还是浏览器(选填)：Webview 

- 详细描述你的bug：奖品背景图的 url 是动图，但是 canvas 渲染出来图不能动

**Comment by FlashWo1f** [comment]
看了下源码，只看到了常规图片的 drawImage 方法，没有对 gif 有额外处理。
是吗，哥哥

**Comment by buuing** [comment]
是的, 哥哥没做gif的渲染, 因为这玩意需要逐帧绘制, 有点耗费性能

**Comment by FlashWo1f** [comment]
那.. 这个可能有一定的需求，有没有可能后续加上这个功能哇

**Comment by buuing** [comment]
暂时封板了, `1.x`的版本不再新增功能了, `2.x`暂无开发计划
