### ISSUE TITLE
九宫格在部分手机 webview中适配有问题

### ISSUE THREAD

**Issue by GitHubYuzai** [buuing/lucky-canvas#503]
- 你当前是什么框架(必填)：react

- 你使用的是哪个包(必填)：@lucky-canvas/react

- 你当前插件的版本(必填)：0.1.13

- 当前环境是小程序还是浏览器(选填)：

- 详细描述你的bug：九宫格在部分手机 webview中适配有问题，会被放大
![WechatIMG375](https://github.com/user-attachments/assets/9fe59213-2378-42c2-9aca-5f4ff8103688)
正常是下面这样
![WechatIMG1891](https://github.com/user-attachments/assets/cd7bf61a-ebf8-412f-9077-9474bcd307a1)

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
  <LuckyGrid
                    rows={3}
                    ref={ref}
                    onEnd={onEnd}
                    width={`5.86rem`}
                    height={`5.86rem`}
                    prizes={prizes}
                    defaultConfig={{
                        gutter: ".12rem",
                        speed: 10,
                        accelerationTime: 2000,
                        decelerationTime: 2000
                    }}
                />
// 代码结束
```

**Comment by buuing** [comment]
这很奇怪, 你看一下canvas的大小和位置变形了吗

**Comment by GitHubYuzai** [comment]
canvas跟外层div的宽高都被放大了，rem计算出来的值变大了

**Comment by GitHubYuzai** [comment]
只有在三星手机中会有这个情况

**Comment by buuing** [comment]
那就是根标签的fontsize有问题了, 别用rem了, 先换成vw试试

**Comment by GitHubYuzai** [comment]
也怀疑过是fontsize不对，但是页面其他布局单位都是正常，也是用的rem，我先试试vw看看

**Comment by buuing** [comment]
其他dom的rem是自动计算的, rem改变时,实时变化, 我这个是js控制的计算, 没有追踪fontsize变化的能力, 说白了就是, 我担心可能你用的库在三星手机上动态计算fontsize了?

**Comment by GitHubYuzai** [comment]
动态计算fontsize是没有的，在三星手机app的webview就不行，浏览器是正常的，有可能是webview有地方影响了，我先排查下，非常感谢回复

**Comment by buuing** [comment]
好的, 我这边也只能是猜测, 毕竟能影响rem的也只有根标签的fontsize了

**Comment by GitHubYuzai** [comment]
用vw单位解决了这个问题

<LuckyGrid
                    rows={3}
                    ref={ref}
                    onEnd={onEnd}
                    width={`78.13vw`}
                    height={`78.13vw`}
                    prizes={prizes}
                    defaultConfig={{
                        gutter: ".12rem",
                        speed: 10,
                        accelerationTime: 2000,
                        decelerationTime: 2000
                    }}
                />
