### ISSUE TITLE
React是否可以设置转盘

### ISSUE THREAD

**Issue by guawazi233** [buuing/lucky-canvas#508]
- 你当前是什么框架(必填)：React

- 你使用的是哪个包(必填)：lucky-canvas/react

- 你当前插件的版本(必填)："@lucky-canvas/react": "^0.1.13",

- 当前环境是小程序还是浏览器(选填)：浏览器

- 详细描述你的bug：
- react转盘设置图片不生效，但是有挤开边距，试过同路径下的图片和线上图片

- 问题代码(重要)：

```
// 代码开始, 别再放歪了行吗
const [blocks] = useState([
    {
      padding: '12px',
      imgs: [{
        // src: './wheel-border.jpg',
        scr: 'https://d3r48att5ocy3q.cloudfront.net/t/240827/92a99bb1f26a47ea8c7685eb55365d80.jpg',
        width: '100%',
        height: '100%',
      }],
      // background: '#869cfa',
    },
    // {
    //   padding: '0px',
    //   background: gutterColor,
    // },
  ]);

// 代码结束
```

**Comment by guawazi233** [comment]
<img width="567" alt="image" src="https://github.com/user-attachments/assets/19cb4037-ff76-4799-a36f-7fb4f8e51c52">
当换成我线上图片链接报错

**Comment by buuing** [comment]
百分百你代码有问题, 自己排查

**Comment by guawazi233** [comment]
<img width="916" alt="image" src="https://github.com/user-attachments/assets/b8a664d5-3599-4379-9f5f-0bc7d8a221cc">
用的你的那个例子添加的，线上图片地址https://i-blog.csdnimg.cn/direct/734f113b1b844672b6edae2528e797ec.jpeg#pic_center

**Comment by guawazi233** [comment]
https://100px.net/playground.html?code=DwEwlgbgBGILwCIC2BPAtAGwK4GMDWKCAfMAPTgREBQVwAzjgE5gAOALtVFDgPYB2dNlFQAZXAShwofAKYB3KGPwoAwgEM%2BENXQB0SggHUAFjJkYAFAHIAxKkziUlgDRQA3lS5c5sNkYBcUJYATAAMISwAHs4eniZgAOZGbAHBYZHRnlAARhg8%2BHQBANoxme6ZmSxqIOB88SkAjEHpTiXlYEjxBVCFZeWZdIw4KaSCamxgOKTtnaRyJmZoWTyMIDKMOgBWLPEZfZ6kpFAMjClJbCwFByAAzIwALAAcY2wArHko1wCOOji5WCAAM0Y-DYOlkbFIEKCdxCDyCAHZSABOIJqJFIrJZeoAoIANjUd3hMjUDxw8NxDxeMiyLxe11xLxADxCm22uz2UAORyYfksZwufgOYEWuXiPzoID40x%2BfHIYEYMhwEPh1zuAPq9WuWKyDzud1x8KCWVxMhAahkQReQQeMnhSKJOFZMni1hYEwA%2BjgZHw2Gt2XtvCBfA0wgBSf19OKJZKBephyytTIAXwAui0OVysmp8PFgVg%2BCAUtYHrikTgAWoI1Ak%2BnygdAH3RgDt-QChioBO%2BMAORmAJyDE24e1xKtUwLUUuEorW%2Blmc3mCykFSAqzXWmnWixmAAvGRdYp9VzZbN4XM8fOFwLWGRImQPAEyZzZZarE6BF6RI48DCwKBzyzV8eeXeTg9pxPGwdRwF4cVvJYVjWFJnwiV93xAT9TW-Rcdz3KcjxnU9z0va9IPvGCnxfOg3w-L8fx7f990PY8i1A8CggI6DH0sOCEPIlDKPQgDaOwmxcKvG8XCgh9YJIsikIotDymozC6NPBiIJEwjWPY0jEOQ%2BduM8ZdMlWCssAwNgVH4AEEgCXpMniLA2F9Vj6nSVokxiJMAEpaBGJhWA4KggA

例子地址

**Comment by guawazi233** [comment]
确实看到图片加载失败了，我再看看
