### ISSUE TITLE
vite创建项目使用LuckyWheel报错

### ISSUE THREAD

**Issue by xzg168** [buuing/lucky-canvas#53]
import LuckDraw from "vue-luck-draw/vue3";
createApp(App).use(router).use(store).use(Antd).use(LuckDraw).mount('#app')

<LuckyWheel
      ref="LuckyWheel"
      width="500px"
      height="500px"
      :blocks="blocks"
      :prizes="prizes"
      :buttons="buttons"
      @start="startCallBack"
      @end="endCallBack"
    />

控制台报  Failed to resolve component: LuckyWheel
是抛出有问题么？

**Comment by buuing** [comment]
看上去应该是有问题, 我还没用过 `vite`

**Comment by xzg168** [comment]
恩恩，我也是试着玩下vite，用了下报错了，有时间研究下，这玩意启动打包确实快

**Comment by buuing** [comment]
但目前来说 `vite` 还是个玩具😂

**Comment by xzg168** [comment]
哈哈哈哈。。。这个倒是赞同

**Comment by mxismean** [comment]
vite2.0正式版已经发布了

**Comment by mxismean** [comment]
大佬有时间了可以考虑兼容一下

**Comment by mxismean** [comment]
太棒了, 必须给个🌟

**Comment by buuing** [comment]
> 大佬有时间了可以考虑兼容一下

嗯, 感觉这个用的人不多啊😂, 有空研究一下

**Comment by mxismean** [comment]
👍👍👍, vite确实很快, 相信vue3慢慢普及以后, vite使用量应该会上去

**Comment by Xutaotaotao** [comment]
> import LuckDraw from "vue-luck-draw/vue3";
> createApp(App).use(router).use(store).use(Antd).use(LuckDraw).mount('#app')
> 
> <LuckyWheel
> ref="LuckyWheel"
> width="500px"
> height="500px"
> :blocks="blocks"
> :prizes="prizes"
> :buttons="buttons"
> @start="startCallBack"
> @EnD="endCallBack"
> />
> 
> 控制台报 Failed to resolve component: LuckyWheel
> 是抛出有问题么？


vite版本是什么，单独使用LuckDraw是否有问题，我本地测试没有问题，可以正常使用
